### ISSUE TITLE
Radar Chart with 5 points Misaligned/Tilted

### ISSUE THREAD

**Issue by gcornhill** [recharts/recharts#1019]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
Since version 1.0.0-alpha.0, when there is a Radar chart with 5 points, the radar chart appears tilted.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/qbmg1567/).
Here's a demo of it tilted with latest version:
https://codepen.io/choucorn/pen/wPrLEr

Versus normal in old version:
https://codepen.io/choucorn/pen/xPXomK?q=recharts&limit=all&type=type-pens

## What is the expected behavior?
I expect with 5 points the chart to not tilt.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Starting in 1.0.0-alpha.0 this happened. Before that version it worked.

**Comment by gcornhill** [comment]
@xile611 Is this fixed in latest release? I just tried and it's still misaligned?
<img width="443" alt="screen shot 2017-11-22 at 9 31 18 pm" src="https://user-images.githubusercontent.com/5075482/33159024-85e4040c-cfcc-11e7-939a-e6efedca823f.png">

**Comment by balthazar** [comment]
Hey @xile611 I'm also interested in this 😃 

Do you mind telling me if there is any extra step to take in order to remove this tilting behavior? Do we need to calculate the `startAngle` and `endAngle` ourselves or is it something that should be done automatically?

Also little note, I believe you made an oversight in the docs since it currently stipulate the default `startAngle` is `90`, which you changed to `360` 🙂 

Thanks for your time!

**Comment by gcornhill** [comment]
@balthazar I did a temp workaround below: 
![screen shot 2017-11-27 at 12 16 19 pm](https://user-images.githubusercontent.com/5075482/33284766-5da7b43a-d36d-11e7-93f5-c81643d7094c.png)

**Comment by balthazar** [comment]
Thanks for the example Genevieve 😃!  I just don't see myself doing it for each different length, since it's not only 5-lengths that are tilted 🙁 (at least for me)
