### ISSUE TITLE
BarChart: Tooltip is broken since beta.3

### ISSUE THREAD

**Issue by jochenberger** [recharts/recharts#1039]
See:
http://jsfiddle.net/ad071owf/
Same Fiddle with beta.2:
http://jsfiddle.net/ad071owf/1/

If you hover over one of the bars, there is a gray rectangle shown at the left side.
I tried a `git bisect` to find the commit that introduced the issue, but I cannot reproduce it in the demo.

**Comment by xile611** [comment]
@jochenberger I can't reproduce it in my local project too. jsfiddle seems very strange now. I can't select texts correctly too.

**Comment by jochenberger** [comment]
Seems to work again with beta.4: http://jsfiddle.net/ad071owf/2/

**Comment by jochenberger** [comment]
No, I must have missed something. It's still wrong in beta.4.

**Comment by jochenberger** [comment]
Beta 5 too: http://jsfiddle.net/ad071owf/3/

**Comment by mkreim** [comment]
Hi,

I am observing the same problem for the bar charts. A good example can be seen here:
expected behavior: http://recharts.org/#/en-US/examples/SimpleBarChart
buggy behavior: http://jsfiddle.net/v8gxrbyu/
For me it looks like the coordinates of the tooltip are always 0,0. So the tooltip is not moving around and the cursor shows a gray box at the left side of the chart.

Also this issue seems to be a duplicate of https://github.com/recharts/recharts/issues/1079

Thanks an best regards

Michael

**Comment by Golodhros** [comment]
This seems to be the case also with the line chart and its tooltip:
![fullscreen_12_30_17__10_59_am](https://user-images.githubusercontent.com/190833/34456655-cf516a20-ed50-11e7-8529-23ff2b088a7d.png)

It's funny how the version of the docs works fine.

**Comment by mpodlasin** [comment]
I use beta.10 version and I am experiencing this exact issue as well.

**Comment by anthony2025** [comment]
I am using 1.1.0 and still having this issue. It is only affecting BarCharts on my project though,  LineCharts work beautifully.

**Comment by JohnStarich** [comment]
I ran into this on the latest version as well (1.6.2). I've opened a PR that fixes my issue: https://github.com/recharts/recharts/pull/1811
I've reversed the order of the rendered elements, placing the tooltip toward the back. Not the greatest solution, but it seemed to do the trick for me.
