### ISSUE TITLE
yarn install warning 

### ISSUE THREAD

**Issue by alexeikaratai** [recharts/recharts#1048]
warning " > recharts@1.0.0-beta.5" has unmet peer dependency "react-transition-group@^2.2.1".

node 8.9.1
yarn 1.3.2
npm 5.5.1
react 16.1.1

**Comment by yadomi** [comment]
Any update on this ?

This is a problem when using an older version of `react-transition-group` when I shrinkwrap since it's declared as a `peerDependecies`.

What I don't understand is that `react-transition-group` [is not used anywhere](https://github.com/recharts/recharts/search?utf8=%E2%9C%93&q=react-transition-group&type=) and was also removed in [1.0.0-alpha5](https://github.com/recharts/recharts/blob/97f840601c880ad90f3b348a9e9fca7ce92ce47e/CHANGELOG.md#100-alpha5sep-16-2017).

Is this a typo or something ? 

Thanks

**Comment by alexraginskiy** [comment]
Bump
