### ISSUE TITLE
Bug? in radial bar chart - start/end angle ignored?

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#1089]
## Do you want to request a feature or report a bug?
bug

## What is the current behavior?
![image](https://user-images.githubusercontent.com/685316/33975332-82390e28-e053-11e7-980e-af37a8e2a86d.png)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
1. It appears that startAngle/endAngle props are ignored.
2. The order of the bars on the chart is inverted. Can the order be specified?

The JSON below is the source of what is processed by our software, which directly creates React ReCharts components. This mechanism is not in question--it works fine under both versions of ReCharts. I've included it to show you the ReCharts components that are being created and the values of the props being set.

```
 {
      "component": "RadialBarChart",
      "container": "chart",
      "data": "traffic",
      "innerRadius": "10%",
      "outerRadius": "80%",
      "components": [
         {
            "component": "RadialBar",
            "dataKey": "waiting",
            "clockwise": true,
            "startAngle": 135,
            "endAngle": -135,
            "minAngle": 15,
            "maxAngle": 255,
            "cornerRadius": 10,
            "background": {
               "fill": "#eee"
            }
         },
         {
            "component": "Legend",
            "layout": "vertical",
            "align": "left",
            "verticalAlign": "middle",
            "iconType": "circle"
         },
         {
            "component": "Tooltip"
         }
      ]
   }
```

## What is the expected behavior?
![image](https://user-images.githubusercontent.com/685316/33975336-85af362c-e053-11e7-95a1-aea61d75bc8d.png)

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Current (broken): 1.0.0-beta.6
Prior (working): 0.21.2

**Comment by xile611** [comment]
@Eric24 
Because only one group of bar is supported in Recharts 0.x. We want to support multi groups of bar in 1.0+ just like BarChart, so we move the props startAngle, endAngle to RadialBarChart.

![image](https://user-images.githubusercontent.com/6111424/32935928-306bc4e2-cbad-11e7-9310-a00313d35bd3.png)

And If you have specified the props `starAngle`, `endAngle`, `clockWise` is no longer needed, so this props is removed.

The props minAngle and maxAngle are used to specify the domain of PolarAngleAxis, so they are removed too. Try to set the range of PolarAngleAxis.

All the changes have been updated in [recharts.org](http://recharts.org/#/en-US/api/RadialBar).

**Comment by Eric24** [comment]
Do you have an example of using PolarAngleAxis with a RadialBarChart?

**Comment by carcruz** [comment]
@xile611 Can you give us and example of how to use PolarAngleAxis with a RadialBarChart?

**Comment by svarlamov** [comment]
@carcruz Not sure if you're still here, but I ended up tracking down a solution via #1100 and posted a comment there as well... Just in case...

**Comment by carcruz** [comment]
Thanks @svarlamov !
