### ISSUE TITLE
ResponsiveContainer for multiple items.

### ISSUE THREAD

**Issue by alexchern** [recharts/recharts#1130]
Hi,

I'm trying to create something similar to BubbleChart demo but need it automatically resized to fit the page. I tried to use the **ResponsiveContainer**, but it only works if I have no more than one <ScatterChart.../> inside.

For example,  in BubbleChart  demo I tried to replace the <div> that contains all the ScatterCharts  with the ResponsiveContainer. If I remove all but one - it works, otherwise it doesn't. Trying to add <div> or using ResponsiveContainer inside ResponsiveContainer didn't work.

What am I doing wrong?

Thanks,

Alex

**Comment by christiancho** [comment]
I took at a the source code. `ReponsiveContainer` uses `React.cloneElement`, which doesn't support multiple elements. You can request a feature to allow for multiple responsive children. In the mean time, you can wrap each separate `BubbleChart` with its own `ResponsiveContainer`.

**Comment by alexchern** [comment]
Thanks. Actually, that's what I did. I rely on "resize" event and dynamically change the width / height.

Alex

**Comment by brandigardner** [comment]
@christiancho Help! So I have component that has 3 parts: a mui box (div can be used) that has a few pieces of data in it along with 2 responsive containers with a bar chart in each. My issue is that I need the charts to display next to each other and not on top of each other but from what I can see, you can't wrap ResponsiveContainer in anything because it's a parent element but then how do I style multiples? any ideas? also the layout i want for the container is the box centered on the top like a title and the two graphs below.
