### ISSUE TITLE
ComposedChart, Scatter, and Line - is it possible?

### ISSUE THREAD

**Issue by iehdk** [recharts/recharts#1156]
For some reason it seem not possible to include Scatter in a ComposedChart. Is that correct and why may that be?

**Comment by ErenKaya** [comment]
hi, i have solution in this case but i am not sure is way correct or not [https://github.com/ErenKaya/code-practices/blob/4bc592b093844421558ddcf80654ee8cc69297e5/course-books/react-course-mead/indecision-app/src/components/ReComposedChartSpecItemTest.js](here)  you can check out thats file maybe it's helps to you. In this case i have problem which is in scatter data because scatter data doesnt't allow from composed data so i push to data each scatter its seems correct but i have a sorting bug which is you have render each scatter comp with own data so if your component render that data you cannot sort that components. if you find any correct solution please share me 
Best Regards.

**Comment by stefan2718** [comment]
I figured this one out, and got my graph to look like this with version `1.8.5`: 
![alt](https://i.imgur.com/MCG1MD0.png)

Here is my code:

```javascript
const data = [
  {
    "newMarkersClustered": 10000,
    "mcp": 1643,
    "wasm": 790
  },
  {
    "newMarkersClustered": 1666,
    "mcp": 182,
    "wasm": 42
  },
  {
    "newMarkersClustered": 625,
    "mcp": 56,
    "wasm": 11
  },
  {
    "newMarkersClustered": 300,
    "mcpSlope": 0
  },
  {
    "newMarkersClustered": 10000,
    "mcpSlope": 1522
  },
  {
    "newMarkersClustered": 600,
    "wasmSlope": 0
  },
  {
    "newMarkersClustered": 10000,
    "wasmSlope": 678
  }
];

export const Graph = () => {
  return (
    <ResponsiveContainer className="graph-wrapper" width="100%" height="90%" >
      <ComposedChart data={data} >
        <XAxis dataKey="newMarkersClustered" type="number"/>
        <YAxis unit="ms" type="number"/>
        <Scatter name="MCP" dataKey="mcp" fill="red"/>
        <Scatter name="Wasm" dataKey="wasm" fill="blue"/>
        <Line dataKey="wasmSlope" stroke="blue" dot={false}/>
        <Line dataKey="mcpSlope" stroke="red" dot={false}/>
      </ComposedChart>
    </ResponsiveContainer>
  )
}
```


Here is the trick:
The first 3 points in the data array are the scatter plot points, where `newMarkersClustered` is the `x` value and `mcp` and `wasm` are different sets of `y` values.

The next 4 points are the start and end points of the trendlines for each data set. I had to calculate their values myself using 'line of best fit' math.

**Comment by karlkovaciny** [comment]
I want to note for Googlers that if you have 3 or more points at the same X-axis location, this solution breaks ToolTip -- only the top and bottom points can appear, and it's based on which side of the line you're on rather than where you're hovering. So I ended up going with ScatterChart plus ReferenceLine.

I added two points to the example sandbox above to demonstrate this: https://codesandbox.io/s/composed-chart-with-best-fit-forked-43ufj

**Comment by stevenmasci** [comment]
> I want to note for Googlers that if you have 3 or more points at the same X-axis location, this solution breaks ToolTip -- only the top and bottom points can appear, and it's based on which side of the line you're on rather than where you're hovering. So I ended up going with ScatterChart plus ReferenceLine.
> 
> I added two points to the example sandbox above to demonstrate this: https://codesandbox.io/s/composed-chart-with-best-fit-forked-43ufj

I started doing the ScatterChart plus ReferenceLine approach as well but then I noticed there is a "line" prop on the Scatter component https://recharts.org/en-US/examples/JointLineScatterChart
