### ISSUE TITLE
Curves

### ISSUE THREAD

**Issue by troyblank** [recharts/recharts#121]
Hello,

My team is between using c3 and recharts. We want to use recharts as our project is react and it works a lot better with our technology. BUT a lot of people see the curves on the spline line graphs on recharts to be a problem. I wanted to bring this to you and see what you think.

Ignore the other styles; but as you see in the image below that c3 (the image on the bottom). Has more smoothed out curves if you look closely.

![unnamed](https://cloud.githubusercontent.com/assets/996725/16209682/c683c286-36fd-11e6-8551-4218e09724b8.jpg)

I know this is a very nebulous ask, but was wondering if you would consider making the curves that recharts use more smooth. Thanks for recharts; it's great.

**Comment by xile611** [comment]
@troyblank 
 
The interpolation that C3 use to generate smooth curve is *Cardinal*. And  you can use *Cardinal* in Recharts too, just like the example: <http://jsfiddle.net/hqe9c1uk/>.

But I recommend to use *Monotone* interpolation. Because curve may across the boundary when you use *Cardinal*  interpolation.
![image](https://cloud.githubusercontent.com/assets/6111424/16217403/bff1f728-37a5-11e6-9c94-1e6483653f88.png)

 Ps: You can see more about interpolation [here](https://github.com/d3/d3-shape#curves).

**Comment by troyblank** [comment]
This is great information!

I didn't see you could add your own custom d3 interpolation in your [documentation](http://recharts.org/api/#Line). But that is awesome. I will definitely be using this, thanks again and sorry for missing that.

**Comment by xile611** [comment]
@troyblank Our document is not perfect yet. I'll add this feature in the document.

**Comment by troyblank** [comment]
@xile611  Hello, this is working great for us but there is something I have noticed that you should be aware of. I get this warning when using a custom d3 interpolation.

```
warning.js?8a56:44Warning: Failed propType: Invalid prop `type` of value `function cardinal(context) {
      return new Cardinal(context, tension);
    }` supplied to `Area`, expected one of ["linear","monotone","step","stepBefore","stepAfter"]. Check the render method of `ComposedLineAreaChart`.
```

Just a heads up as if recharts is allowing a custom type this warning seems to be a tad misleading. Thanks!

**Comment by xile611** [comment]
@troyblank  Yeah, I should fix the PropTypes of `type` in `Area`. Thank you!
