### ISSUE TITLE
Tooltip not working for Treemap for elements where depth >1

### ISSUE THREAD

**Issue by Hem-Bhatt** [recharts/recharts#1278]
The JS Fiddle Link- https://jsfiddle.net/Ldvvz2ak/60/

As you can see in the demo, the  tooltip works for the axis element, but gets messed up for other elements.

**Comment by kennylam** [comment]
The issue is the `none` this line:
`fill: depth < 2 ? colors[Math.floor(index / root.children.length * 6)] : 'none',`

Anything with a depth greater than one gets a fill of `none`, so basically the svg is empty except for the stroke, which is why those will trigger the hover. You can set a transparent color in there to fix.

https://jsfiddle.net/Ldvvz2ak/154/

**Comment by Hem-Bhatt** [comment]
Thanks! that works! :)
