### ISSUE TITLE
affect by font-size of <html>  

### ISSUE THREAD

**Issue by zhaoyihong** [recharts/recharts#129]
I want to use rem in my css ,but I find line chart become strange.
I found that when font-size of html element changed,  most of  axis ticks are hidden and height of chart become smaller.
For example, I change the style of SimpleLineChart (http://recharts.org/examples#SimpleLineChart) 
to  
`body {
  margin: 0;
  font-size:100px;
}
#container {
  font-size:16px
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  padding: 10px;
  width: 800px;
  height: 800px;
  background-color: #fff;
}`

this  phenomenon above will happen.

**Comment by zhaoyihong** [comment]
For example, I change the style of SimpleLineChart (http://recharts.org/examples#SimpleLineChart) 
to  
`body {
  margin: 0;
  font-size:100px;
}
#container {
  font-size:16px
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  padding: 10px;
  width: 800px;
  height: 800px;
  background-color: #fff;
}`
this kind of phenomenon has happened.

**Comment by xile611** [comment]
@zhaoyihong  
Thank your.
 There's some bug when calculate the width, height of Legend and Tooltip. Because we insert a hidden DOM to body when calculate the size of Legend, and Tooltip. So your global css will affect the result of the calculation. It's a bug.

And it's normal that global css will affect svg elements, css even have higher priority than presentation attributes of svg elements.  You can look [Here](https://www.w3.org/TR/SVG/styling.html#AlternativesForStyling) for detail.

**Comment by xile611** [comment]
I found that it's very troublesome to solve the problem. Because we want to get the width and height before `componentDidMount`.

So I temporarily solve this problem by a hack method. Thank you !

**Comment by zhaoyihong** [comment]
Thank you very much for your  help !
