### ISSUE TITLE
ReferenceArea disappears on brush movement and zoom.

### ISSUE THREAD

**Issue by Siemko** [recharts/recharts#1292]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
ReferenceArea disappears on brush zooming.
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
https://jsfiddle.net/zq71xrst/
## What is the expected behavior?
ReferenceArea should be visible.
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
1.0.0-beta.10
Opera 52, Edge, Chrome 60.0.3112.78

**Comment by damien916** [comment]
Hi, I experience the same issue, ReferenceArea disappear when x1 or x2 are outside the brush selected area.

**Comment by cbazza** [comment]
Was having the same issue and a workaround is to set ifOverflow to 'visible':
`<ReferenceArea ifOverflow="visible" x1={t0} x2={t1} y1={0}   y2={greenMax}  fill="green" fillOpacity={0.1} />`

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.

**Comment by k-one-o-two** [comment]
The issue happens to me in 2.0.9. We're using ReferenceAreas to make borders outside the bars in chart rather than in the middle. So there's one ReferenceArea for every record - looks like this: 
![image](https://user-images.githubusercontent.com/10806393/123605002-1349bb00-d804-11eb-9b0d-a4f36cf27efe.png)
(If this can be achieved another way, pls suggest).

When the brush is in another part of the chart, width and x positions of the area are NaN, but they are not recalculated after moving the brush.
![image](https://user-images.githubusercontent.com/10806393/123604931-fd3bfa80-d803-11eb-8040-156d557fad58.png)
as a result I get only horizontal lines from the CartesianGrid component
![image](https://user-images.githubusercontent.com/10806393/123605132-2d839900-d804-11eb-9c63-28939ed52149.png)

Am I doing something wrong?

**Comment by bakydev** [comment]
> The issue happens to me in 2.0.9. We're using ReferenceAreas to make borders outside the bars in chart rather than in the middle. So there's one ReferenceArea for every record - looks like this: ![image](https://user-images.githubusercontent.com/10806393/123605002-1349bb00-d804-11eb-9b0d-a4f36cf27efe.png) (If this can be achieved another way, pls suggest).
> 
> When the brush is in another part of the chart, width and x positions of the area are NaN, but they are not recalculated after moving the brush. ![image](https://user-images.githubusercontent.com/10806393/123604931-fd3bfa80-d803-11eb-8040-156d557fad58.png) as a result I get only horizontal lines from the CartesianGrid component ![image](https://user-images.githubusercontent.com/10806393/123605132-2d839900-d804-11eb-9c63-28939ed52149.png)
> 
> Am I doing something wrong?

Do you solve you problem?
