### ISSUE TITLE
Vertical Brush when a bar chart is vertical

### ISSUE THREAD

**Issue by aakashsigdel** [recharts/recharts#1303]
## Do you want to request a feature or report a bug?
- Feature
## What is the current behavior?
- There is no way to make the <Brush /> vertical
## What is the expected behavior?
- There is a option to make <Brush /> vertical

**Comment by xile611** [comment]
Sorry. This feature seems strange.

**Comment by MateuszTrN** [comment]
> Sorry. This feature seems strange.

how is this strange? when your y-axis acts as an 'category' it's totally normal thing to want to be able to brush it according that axis. Consider a chart like that: 
![image](https://user-images.githubusercontent.com/4653046/152940524-2146f410-5afd-4ec4-b0fb-551ecbb5abae.png)

Because there is no vertical brush, it doesn't scale automatically as it does in vertical chart:
![image](https://user-images.githubusercontent.com/4653046/152940958-2f62a837-618b-4f8b-903e-6ea9ebe4e063.png)
