### ISSUE TITLE
Hide points outside of domain

### ISSUE THREAD

**Issue by farhan-sauce** [recharts/recharts#1329]
## Do you want to request a feature or report a bug?
- Probably bug

## What is the current behavior?
- Point is displayed outside of domain of X-Axis.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
[JSFiddle demo](https://jsfiddle.net/69cejfpm/)

## What is the expected behavior?
- Rechart should ignore the point which is outside of domain

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
- Latest version of Recharts, Chrome browser MacOS

**Comment by ppseprus** [comment]
`allowDataOverflow={true}`
https://jsfiddle.net/69cejfpm/6/

**Comment by farhan-sauce** [comment]
Thanks @ppseprus !
It works well!

**Comment by ppseprus** [comment]
No problem! : )

**Comment by dandrei** [comment]
Hi @ppseprus 

I don't want to open another ticket because this one is on the same topic.
I have the following fiddle: `https://jsfiddle.net/dandrei/a7cqjytv/`.

On `YAxis` I set the following:

```
allowDataOverflow={true}
domain={["dataMin + 1000000", "dataMax - 1000000"]}
```

This should clip the chart at both extremes, right? But that doesn't happen.
Can you please take a look? Thanks!
