### ISSUE TITLE
[DOCS] Opening new tab or subpage from a link gives 404 error

### ISSUE THREAD

**Issue by ppozniak** [recharts/recharts#1395]
This is an issue with http://recharts.org site.

Opening anything in a new tab will end up in 404.
The same thing happens if you try to open up any sub page from a link, for example: http://recharts.org/en-US/guide/getting-started

**Comment by sauravazad** [comment]
It is because Browser history API is used and there is no server side code to handle dynamic routes, They should have used hashrouter . 

https://reacttraining.com/react-router/web/api/HashRouter.

https://stackoverflow.com/questions/27928372/react-router-urls-dont-work-when-refreshing-or-writting-manually/36623117#36623117

**Comment by ppozniak** [comment]
I'll move that to https://github.com/recharts/recharts.org/issues recharts.org repo.
