### ISSUE TITLE
Labels not displaying when data is from props

### ISSUE THREAD

**Issue by MerApelsin** [recharts/recharts#1500]
So I can't get labels to display when getting the data in as prop but using local/an array that's outside the class works, why?
`const { data } = this.props;` in render() doesn't help either and it's not like I can access the prop data outside the class either, so I'm kinda stuck on how to proceed. Thanks

**Comment by kgregory** [comment]
Ran into this too, it's almost as though `isAnimationActive` isn't being set to false.

If I explicitly disable the animation the labels appear.  If I resize browser so that my flexbox layout shifts, the animation seems to finish and labels appear.  Tried to create a reproduction of this in codesandbox, but it works there.

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please open a new issue according to the issue guide.
