### ISSUE TITLE
Add className prop to <Cell />

### ISSUE THREAD

**Issue by iamjdimitrov** [recharts/recharts#1573]
## Do you want to request a feature or report a bug?
Feature

## What is the current behavior?
Currently, classnames can't be appended to the outputted <path>s such as .recharts-rectangle or .recharts-sector. The only way to give color to a <Cell /> is through directly adding its fill.

## What is the expected behavior?
We want to be able to append a custom className to any Cell, so a <path class="recharts-rectangle cell-something-green"> can be colored in green in any chart automatically through CSS, instead of passing it as a fill every time when initializing the component in JS. Imagine a scenario with 500 subjects that should always have the same color... Cheers!

**Comment by PaulieScanlon** [comment]
I'd also quite like a bit more control with className. I'd like to add a material style box-shadow to a pie chart / donut chart to help lift it from it's background. 

![screen shot 2019-01-14 at 21 09 43](https://user-images.githubusercontent.com/1465706/51141324-c72b7b80-1840-11e9-857a-2c7bbff7da2c.png)

**Comment by PaulieScanlon** [comment]
I had  a play and i've partly got something working see here 👉 https://jsfiddle.net/9yt3upr7/9/

![screen shot 2019-01-15 at 10 13 41](https://user-images.githubusercontent.com/1465706/51173852-44d9a080-18ae-11e9-8590-f84b81a3c270.png)

This uses the `activeShape` prop http://recharts.org/en-US/examples/CustomActiveShapePieChart.

It's not quite what i wanted because
1. It could only apply a new style to the active shape not all shapes (which is understandable as it's using the 'ACTTIVE' shape method)
2. I was only able to add a stroke. I tried adding a filter / blur / drop shadow but it wasn't looking right.

I'd love to see if anyone else has any thoughts on this.

Ideally there would be a method to render a shadow svg under this segmented one that is just a full circle which i could either style using an svg filter or by adding a className. 

Apologies if this isn't quite in line with you original query @iamjdimitrov
