### ISSUE TITLE
BarChartStackedBySign - Is it possible to show same entity on both side of Y axis ?

### ISSUE THREAD

**Issue by gargroh** [recharts/recharts#1575]
## Do you want to request a feature or report a bug?
- Feature 

## What is the current behavior? 
- Unable to find requesting feature

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
- https://jsfiddle.net/59ugdj1t/

I asked this question on stackoverflow, but didn't got answer, so posting it here....

In BarChartStackedBySign of Recharts, i want to compare the given entities for current and previous year representing that on bar graph.

The issue is re-charts treats them as different entity if provided via two different objects.

In the fiddle shared we can see each fruit is represented two times on x-axis, i want each fruit comes only one time on x-axis and data for current year gets represented on +y axis and previous year data on -y axis.

Fiddle link - https://jsfiddle.net/59ugdj1t/

**Comment by sarafaman53** [comment]
Hi, 

The reason graph is rendering two ticks for same key is because they are present in two different objects in your data list. 

The graph is not smart enough to gauge a same x axis key for rendering the bar / line. May be the original developers doesn't want to intend it this way. 

What you can do is , You can create an object which contains both present year and current year data . 
Somewhat like, 

```
const data = [
      {name: 'Apple', men_2018: 4000, women_2018: 2400,  men_2017: -4000, women_2017: -2400},
];
```

And then use these keys in your bar chart like  : 

       ```
<Bar dataKey="men_2018" fill="#8884d8" stackId="stacka" />
       <Bar dataKey="women_2018" fill="#82ca9d" stackId="stacka" />
        <Bar dataKey="men_2017" fill="#8884d8" stackId="stackb" />
       <Bar dataKey="women_2017" fill="#82ca9d" stackId="stackb" />
```

If you notice carefully, I've used two stack Id's for each year.  If you want both previous year and present year on same bars, you can have a single stack id for all the four bars.  This is upon your requirement. 

I hope this helps :)
