### ISSUE TITLE
Last point not shown in LineChart

### ISSUE THREAD

**Issue by jcald1** [recharts/recharts#1577]
I have a simple LineChart and last point/line segment is not shown.  I added some right margin and now the last XAxis label is shown but not the last line/point.

I'm using Recharts 1.4.1 with React 16.3.1.

jsfiddle: https://jsfiddle.net/jcald1/5rnpextf/10/

The image is showing some labels that are highlighted, but that was due to selecting in the browser:
![capture](https://user-images.githubusercontent.com/5595867/49188166-9b9b1300-f31e-11e8-8ede-fc9e314d7179.PNG)

**Comment by sarafaman53** [comment]
The last line is already plotted. 

By specifying a **dy** and **angle** at same time, you have first shifted the label position downward by 40 and then rotated it negatively by 65, due to which labels appears shifted from its ticks. 

**Solution :**

  <XAxis interval={0}  angle={-65} dataKey="timestamp"  textAnchor = "end" />
