### ISSUE TITLE
Legend onClick does not provide serie info

### ISSUE THREAD

**Issue by wokier** [recharts/recharts#1617]
### Feature Request
Be able to detect which serie have been clicked, in order to filter it out, or provide extra navigation options.

### Legend allows to detect click but does not provide any event information.
http://recharts.org/en-US/api/Legend#onClick

### Jsfiddle
https://jsfiddle.net/mrw75va6/

**Comment by xile611** [comment]
@wokier we have provided necessary parameters to the event handlers. Because arrow function doesn't have arguments, so you can't get the parameters by arguments.

![image](https://user-images.githubusercontent.com/6111424/52617715-b7eb2c80-2ed7-11e9-93d6-fab5d3837d6a.png)

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

![image](https://user-images.githubusercontent.com/6111424/52617787-eb2dbb80-2ed7-11e9-8df7-762451686ab7.png)

**Comment by wokier** [comment]
The screenshot shows arguments reading, but i am still not able to do it.
Could you update the jsfiddle to see the full implementation ?

**Comment by xile611** [comment]
> The screenshot shows arguments reading, but i am still not able to do it.
> Could you update the jsfiddle to see the full implementation ?

https://jsfiddle.net/alidingling/hebdfw7a/
