### ISSUE TITLE
Add cornerRadius and other properties to API documentation

### ISSUE THREAD

**Issue by anikolaev** [recharts/recharts#1764]
There is nothing about `cornerRadius` here: http://recharts.org/en-US/api/RadialBar
I had to make a google search to find this functionality. It looks like there are also additional properties like `cornerIsExternal ` and `forceCornerRadius` not explained anywhere except issues. Please update the doc. It would be nice to have examples too.

**Comment by xile611** [comment]
Thanks! PR to [recharts.org](https://github.com/recharts/recharts.org) is welcome.

**Comment by elbugs** [comment]
Why is this closed? I went crazy for the need for having radial corner in pie chart, until I saw in stackoverflow it's a property super easy to use. I didn't know that because it's not in the docs. I'll do a PR but do not know how exactly works, which components more are there, and cant find any docs anywhere. Thanks for the work.
