### ISSUE TITLE
Tooltip and XAxis

### ISSUE THREAD

**Issue by rrdlpl** [recharts/recharts#1810]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?

Tooltip doesn't display the correct values on mouse hover if XAxis has scale="time" and type="number"  properties on it. If you comment this properties in the sandbox the correct values will be diplayed.

https://codesandbox.io/s/nivoscatterplot-extra-layer-s261q

## What is the expected behavior?
Tooltip should display the correct values

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Chrome: Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by mKlooney** [comment]
I have the same problem!

**Comment by Priceincoding** [comment]
Same issue, a typical example for me associates with use of data series.
https://jsfiddle.net/rdjeLw3v/

**Comment by Priceincoding** [comment]
For me it seems to be the problem of
`activeIndex`
that is used to get the payload for the tooltip as all series of data seem to share one activeIndex.
Another problem is that when one serie has a null point, it displays a duplicated data of another serie,

**Comment by gndelia** [comment]
I think the issue here is that if you set xAxis as `category='number'` it will expect numbers for the data set in the dataKey, however, you're sending plain dates.

One option could be to use `getTime()` over each date, and then just update the timeFormatter to recover the proper formatting in the displayed value in the xAxis.

In order to recover the proper value in the tooltip, you might have to create a customTooltip too, I left that part for you

See working example https://codesandbox.io/s/nivoscatterplot-extra-layer-xpqwj
