### ISSUE TITLE
LineChart with y and x datakeys?

### ISSUE THREAD

**Issue by pcmaffey** [recharts/recharts#183]
Is it possible to create a LineChart (and AreaChart) with numeric data values for both x and y axis? I want a Line calculated with both dataKeys (so that x-axis values are not evenly distributed).

I see how to do this for a ScatterChart (and even connect with linear line), but I want a curved line, and gradients, and options available only with Line/Area charts.

Or is the only option to input connected Null points to simulate that spacing between values?

PS. Great work!

**Comment by xile611** [comment]
@pcmaffey Thank you! I'll try to support Area in ScatterChart. And you can check [this issue](https://github.com/recharts/recharts/issues/154) for the discussion of two numeric axes.

**Comment by kujon** [comment]
Both this issue and https://github.com/recharts/recharts/issues/154 highlight a few of shortcomings:
1) While almost all line/area charts can be drawn with x-axis being categorical, the problem occurs if you'd like to use axis' domain (imagine a line chart, where you want to draw 2 overlapping lines with different x-axes, both of which have different domains - currently impossible). Then, if you start supporting domains for categorical axes, what should happen if the domain is wider than the categories provided?
2) Replicating this scenario using scatter chart is not possible either, since it doesn't support multiple axes (and it wouldn't make much sense for it to do so).
3) Mocking numerical x and y values with scatter chart is also different in terms of behaviour - in scatter chart you interact with data points only, whereas in line/area chart you can be scrolling through their x-axis and the tooltip is always going to show something.
