### ISSUE TITLE
API documentation missing info about date (time axis)

### ISSUE THREAD

**Issue by wisyr** [recharts/recharts#1846]
This is quite common case, why there's nothing about adding date to x axis in docs? Would be pretty helpful. Thanks

**Comment by stephenrs** [comment]
You can accomplish this pretty easily by using millisecond timestamps instead of dates as your time /date attribute. Make sure your data is sorted by the timestamp attribute, and use a custom XAxis renderer to display the dates.

Something like this worked for me:

```
        const renderCustomAxisTick = ({ x, y, payload }) => {
            return (
              <g transform={`translate(${x},${y})`}>
                <text x={0} y={0} dy={16} textAnchor="end" fill="#666" transform="rotate(-35)">{new Date(payload.value).toLocaleDateString()}</text>
              </g>
            );
        };

        <LineChart style={styles.plChart} width={600} height={350} data={payload}>
                    <Line type="monotone" dataKey="value" stroke="#8884d8" />
                    <CartesianGrid strokeDasharray="5 5"  />
                    <XAxis dataKey="ts" height={75} tick={renderCustomAxisTick} />
                    <YAxis />
        </LineChart>
```

I used the hints in this documentation example to figure out the formatting and rotation of the date labels: http://recharts.org/en-US/examples/CustomizedLabelLineChart

Hope this helps!

**Comment by barbalex** [comment]
Looks like it is done accordingly in react-vis: https://github.com/uber/react-vis/blob/master/showcase/plot/linemark-chart.js

**Comment by xile611** [comment]
Thanks! PR to [recharts.org](https://github.com/recharts/recharts.org) is welcome.
