### ISSUE TITLE
Performance in IE10/11

### ISSUE THREAD

**Issue by bluespore** [recharts/recharts#186]
Hey folks, 

Recharts looks perfect for a new project I'm working on, but the one thing holding me back right now is IE10/11 have considerably worse performance with larger data sets.

It's very possible our customers will require charting with 365 points for a years worth of data, in a combination chart. What we've found interesting is that [Morris.js](http://morrisjs.github.io/morris.js/) seems to perform fine (obviously we'd rather with a React-based library if possible, though) on those browsers.
- Is it possible the performance on these browsers is due to poor React render operations? 
- Is this something you've looked at before?

Cheers,
Sean.

**Comment by xile611** [comment]
@bluespore We have looked at a lot of chart libraries before, like echarts, highcharts, c3, nvd3, chartist, dc.js, and so on. Morris.js is also one of them. Most of these chart libraries can't meet our  various requirements.  That's why we develop recharts.
And we'll try to find the performance problem of recharts. Thank you !

**Comment by bluespore** [comment]
Thanks @xile611 -- Recharts looks fantastic, we just need to ensure our customers on IE10 aren't getting left out, when comparatively, other libraries seem to perform better. We'd love to use Recharts. :)

**Comment by billneff79** [comment]
One of the performance issues we've run into is that the XAxis (and subsequent formatting of all ticks, which can be not-free with date formatting) is re-computed/rendered on every render, which is super expensive with large data sets.  

https://github.com/recharts/recharts/blob/38269105832e2ab3a353e091ddb874b2c39adcfb/src/chart/generateCategoricalChart.js#L614

Really need to update the Axis so that they are pure components that don't re-render if the props don't change, and defer formatting of the ticks into the component itself rather than formatting them prior to sending them as a property the component

**Comment by billneff79** [comment]
I submitted pull request #277.  That should help with some of the large dataset performance issues.  Still need to fix it so that it doesn't format every tick on every render...

**Comment by thienanle** [comment]
@billneff79 I noticed in the PR you said
> we've effectively abandoned recharts for our project

I'm curious what you replaced recharts with?

**Comment by billneff79** [comment]
We ended up writing our own wrapper library that uses d3's rendering methods as well as it's math methods, but makes it all accessible via react components (technically, we use preact). 

For example, instead of re-writing an area chart component from scratch like recharts did, we created an <Area> component that takes in as props the scales for the x-axis and y-axis generated using d3-scale methods, as well as the full data array.  

All <Area>'s render method does is render a `<g/>` tag.  The magic happens in componentDidMount where we use the d3-shape library to create a new `area` function and we apply that function to our <g> tag.  componentDidUpdate updates the `area` function and reapplies it to the same <g> tag from the render method.

We applied that same pattern to create XAxis, YAxis (using d3-axis), Area (d3-shape), Line (d3-shape), Brush (d3-brush), and Zoom (d3-zoom).  We created our own ReferenceLine, Tooltip and other handy stuff using straight react/preact code as we didn't need any magic from d3 for rendering other than the data from the scales.

In the end, our component definition ends up looking something like this.  The <Chart> component takes those scaleDefs props, creates d3 scales from them, and passes it as an array to all of it's children - that's where a lot of the magic lies in addition to just calling d3's rendering functions.

We may open-source our project some day, but it's not quite ready for open-source prime-time yet - it's still a little too specific to our use case.

````
<div class={style.stockChart} >
	{ /* MAIN AREA CHART */ }
	<div>
		<Chart
			class={style.mainChart}
			border
			width={width}
			height={300}
			startIndex={startIndex}
			endIndex={endIndex}
			scaleDefs={[
				{ scaleId: 'mainXScale', type: TimeScale, data, startIndex, endIndex, dataSelector: xAxisSelector },
				{ scaleId: 'zoomXScale', type: TimeScale, data, dataSelector: xAxisSelector },
				{ scaleId: 'mainYScale', type: LinearScale, data, startIndex, endIndex,
					dataSelectorFactory: isPercentChange ? priceChangeSelectorFactory : false,
					dataSelector: isPercentChange ? false : priceSelector,
					symbols
				},
				{ scaleId: 'volumeYScale', type: LinearScale, data, startIndex, endIndex,
					dataSelector: volumeSelector, symbols, multiplier: 0.3
				}
			]}
		>
			<XAxis
				height={17}
				scaleId="mainXScale"
			/>
			<YAxis
				width={60}
				showGrid
				border
				scaleId="mainYScale"
				tickFormat={isPercentChange ? percentFormatter : priceFormatter}
			>
				<ReferencePill class={style.lastPricePill} value={lastClosingPrice} formatter={priceFormatter} />
			</YAxis>
			<Area
				class={cx(style.price, style[`compare-color-${i+1}`])}
				xScaleId="mainXScale"
				yScaleId="mainYScale"
				symbol={symbol}
			>
					<ReferenceLine value={lastClosingPrice} />
			</Area>
			{/* VOLUME CHART OVERLAYED ON AREA CHART at 30% scale */}
			<Area
				class={style.volume}
				xScaleId="mainXScale"
				yScaleId="volumeYScale"
				curveFunction={curveStepAfter}
				symbol={primarySymbol}
			/>
			<Tooltip
				symbol={primarySymbol}
				referenceLineValue={isPercentChange ? false : priceSelector(primarySymbol)(data[data.length-1])}
				xScaleId="mainXScale"
				yScaleId="mainYScale"
				xFormatter={dateFormatter}
				yFormatter={isPercentChange ? percentFormatter : priceFormatter}
			/>
			<Zoom
				xScaleId="zoomXScale"
				startIndex={startIndex}
				endIndex={endIndex}
				onChange={this.handleIndexChange}
			/>
		</Chart>
	</div>


	{ /* BRUSHABLE CONTEXT AREA CHART  */ }
	<div>
		<Chart
			class={style.contextChart}
			border
			width={width}
			height={50}
			scaleDefs={[
				{ scaleId: 'contextXScale', type: TimeScale, data, dataSelector: xAxisSelector },
				{ scaleId: 'contextYScale', type: LinearScale, data,
					dataSelector: priceSelector,
					symbols: [primarySymbol]
				}
			]}
		>
			<Area class={style.context} xScaleId="contextXScale" yScaleId="contextYScale" symbol={primarySymbol} />
			<XAxis height={0} scaleId="contextXScale" />
			<Brush xScaleId="contextXScale" startIndex={startIndex} endIndex={endIndex}	onChange={this.handleIndexChange} />
		</Chart>
	</div>
</div>
````

**Comment by thienanle** [comment]
@billneff79 Thanks for your very thorough response and the code. Eagerly looking forward to your open source debut!

**Comment by codinronan** [comment]
@billneff79 I'd jump at that. Looking forward to the day.
