### ISSUE TITLE
1.8.3 breaks CartesianAxis ticks text updates

### ISSUE THREAD

**Issue by adesurirey** [recharts/recharts#1914]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-xic2v)

### Steps to reproduce
Pass a `tickFormatter` prop to a `CartesianAxis` then update this prop. In 1.7.1 this works good. Upgrade from 1.7.1 to 1.8.3, the text won't update anymore.

### What is expected?
The ticks should display the new text returned by `tickFormatter` function

### What is actually happening?
Ticks texts stays the same. Spacing and position can change when the text size change, but the text won't update.

| Environment | Info |
|---|---|
| Recharts | v1.8.3 |
| React | react/react-dom 16.10.2 |
| System | macOS Mojave 10.14.6 |
| Browser | Chrome 77.0.3865.120 |

---
When inspecting with react-developer-tools I can see that the `Text` component children is ok, it's the text that should be displayed, but on the screen, it still displays the initial return of `tickFormatter` function.

**Comment by ChrisEddy** [comment]
Can confirm, have same issue.

**Comment by Huuums** [comment]
The same is happening with the Text in the Brush Component. 

I think this is more of an issue with the `Text` component rather than the CartesianAxis.

Ever since the update the value of the `Text` component will stay the same and not update once it is "mounted".

Using the reproduction link from this issue you can reproduce this by inserting some long value into the textfield until some of the ticks disappear. After that remove some characters out of the textfield again and some Ticks will reappear with the new value.

**Comment by adesurirey** [comment]
Looking at the `Text` source, I think this line might prevent `wordsByLines` state update as when inspecting the sandbox I can't see any `width` or `scaleToFit` prop update. 

https://github.com/recharts/recharts/blob/6219664569520afaea74a376de12221fff3ebc84/src/component/Text.js#L61
