### ISSUE TITLE
How to force chart to start at x=0?

### ISSUE THREAD

**Issue by otaviobps** [recharts/recharts#1938]
- [X] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://lightningboost.info/?periodicity=monthly&start_date=2018-11-10&symbol=UBER&investment=500](https://lightningboost.info/?periodicity=monthly&start_date=2018-11-10&symbol=UBER&investment=500)

### Steps to reproduce
Depending on the length of the data array, the chart doesn't start at x = 0 (not at the intersection of x and y) and doesn't finish at the max value of x:

![image](https://user-images.githubusercontent.com/28715087/68558192-2a614c80-0417-11ea-86d1-cc4a9e694588.png)

### What is expected?
Force chart to ocuppy all the chart space

### What is actually happening?
A blank space is being shown at the start and end of the chart

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | react 16.10.2 |
| System | Mac OSX |
| Browser | Firefox |

---
Sorry if this solution is explained somewhere, but I couldn't find it. Thank you

**Comment by antoninklopp** [comment]
Hi @otaviobps , 

I think that this is the type of question that you should ask on [Stackoverflow](https://stackoverflow.com/questions/tagged/recharts), since  this is the place for bugs and feature requests.
Your example can't be reproduced since the reproduction link is not a "code reproduction" with a [Code sandbox](https://codesandbox.io/) for example but an image. 

For your issue, you could look into the **domain** prop from the axis. [example](http://recharts.org/en-US/examples/VerticalLineChartWithSpecifiedDomain)

**Comment by otaviobps** [comment]
Thank you @antoninklopp, I'll close the issue and post on stackoverflow
