### ISSUE TITLE
Add the ability to have chart styles set on the underlying Surface

### ISSUE THREAD

**Issue by jakeorr** [recharts/recharts#195]
I would like the ability to specify styles on the Surface component that is created for a chart. The `styles` prop on a chart gets applied to the containing div (`recharts-wrapper`) here https://github.com/recharts/recharts/blob/cdf194bc10aa5141cdc479b7f91bf5006351401c/src/chart/generateCategoricalChart.js#L760, but I don't see a way to get it to the Surface and the svg it creates.

The Surface component seems to have the capability (https://github.com/recharts/recharts/blob/e39ee8fb9a3256527f1cb8550a4a58ef1051153a/src/container/Surface.js#L33), but I'm unsure if this is exposed anywhere.

Being able to specify the styles on the Surface (and in effect on the underlying svg) would allow me to embed styles on the svg before exporting is as an image. Is this feature currently available or are there plans to implement it?

Thanks!

**Comment by xile611** [comment]
@jakeorr We'll support it in the next version.

**Comment by jakeorr** [comment]
That is good news, thank you for the response. Do you have an idea when the next version will be released?

**Comment by derrickpelletier** [comment]
Thannks @xile611 

I just tried this out. With some fiddling, I managed to get it to work.

given a structure like:

```javascript
<BarChart
  data={ data }
  >
  <XAxis />
  <YAxis />
  <CartesianGrid />
  <ReferenceLine />
  <Bar />
</BarChart>
```
I would have expected to add the `style={...}` prop onto the `<BarChart>` component, but when doing that, it just ends up on the "bars" portion of the chart, if I want styles to affect the Y-axis, I have to set those individually, so there doesn't appear to be a catch all that applies a style="" directly onto the svg?

Just wanted to confirm that's expected behaviour. Can definitely work with this behaviour if this was the intention though.
