### ISSUE TITLE
can't set static string tick values in Xaxis

### ISSUE THREAD

**Issue by amirsaeed671** [recharts/recharts#1965]
![image](https://user-images.githubusercontent.com/43801058/70174554-fe27ab80-16f6-11ea-9b80-f1d2755fac9b.png)

I want to set the static tick values in string like 0:00, 2:00, 4:00.....24:00

I tried <XAxis ticks={['0:00', .....]} /> but it gives blank line on xAxis

**Comment by amirsaeed671** [comment]
right now the data is comming from api and populating the chart, but I want the x axis to be static

**Comment by antoninklopp** [comment]
Hi @amirsaeed671 , 

Please provide a jsfiddle link so that your example can be reproduced. 
I also think that this question should be asked here : [Stackoverflow](https://stackoverflow.com/questions/tagged/recharts). 

What you can do is choose the values you want to display on the Xaxis with the **ticks** parameter ([documentation here](http://recharts.org/en-US/api/XAxis#ticks))

**Comment by amirsaeed671** [comment]
> Hi @amirsaeed671 ,
> 
> Please provide a jsfiddle link so that your example can be reproduced.
> I also think that this question should be asked here : [Stackoverflow](https://stackoverflow.com/questions/tagged/recharts).
> 
> What you can do is choose the values you want to display on the Xaxis with the **ticks** parameter ([documentation here](http://recharts.org/en-US/api/XAxis#ticks))

thanks for the reply but the issue has solved, Yeah I should have ask this on Stakoverflow my bad....
