### ISSUE TITLE
Brush Error: Cannot read property 'range' of undefined 

### ISSUE THREAD

**Issue by avindra** [recharts/recharts#2093]
This is a continuation of Issue #1187 . This issue was re-filed as requested by @xile611 . Thanks to @ZephD for creating the error repro case.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-playground-gqjm4)

### Steps to reproduce
Open the code sandbox, then resize the preview window pane

### What is expected?
It should continue rendering normally

### What is actually happening?
The code crashes, throwing this error:

```
Cannot read property 'range' of undefined
Brush.UNSAFE_componentWillReceiveProps
https://gqjm4.csb.app/node_modules/recharts/lib/cartesian/Brush.js:158:20
callComponentWillReceiveProps
https://gqjm4.csb.app/node_modules/react-dom/cjs/react-dom.development.js:12976:14
updateClassInstance
https://gqjm4.csb.app/node_modules/react-dom/cjs/react-dom.development.js:13178:7
updateClassComponent
https://gqjm4.csb.app/node_modules/react-dom/cjs/react-dom.development.js:17107:20
beginWork
https://gqjm4.csb.app/node_modules/react-dom/cjs/react-dom.development.js:18620:16
HTMLUnknownElement.callCallback
https://gqjm4.csb.app/node_modules/react-dom/cjs/react-dom.development.js:188:14
Object.invokeGuardedCallbackDev
https://gqjm4.csb.app/node_modules/react-dom/cjs/react-dom.development.js:237:16
invokeGuardedCallback
https://gqjm4.csb.app/node_modules/react-dom/cjs/react-dom.development.js:292:31
beginWork$1
https://gqjm4.csb.app/node_modules/react-dom/cjs/react-dom.development.js:23203:7
performUnitOfWork
```

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.5 |
| React | 16 |
| System | Linux |
| Browser | Chrome 80 |

---

**Comment by avindra** [comment]
Thanks for the fix @xile611 , can confirm it works great in v2 beta 6

**Comment by NereonNeo** [comment]
### Error: Cannot read properties of undefined (reading 'name')

Hi everyone! I'm not sure if this will be useful to anyone, but I wanted to share how I solved a similar error.

The issue was that when the data in the Brush component changed, it would completely break and throw an error (Cannot read properties of undefined (reading 'name')). I understood that this error was occurring because the new data might have had fewer elements, causing it to fail when trying to access properties using the old indices. However, I couldn't figure out how to resolve it! Out of desperation, I dove into the Brush component's code and found an interesting snippet:

`var ariaLabelBrush = ariaLabel || "Min value: ".concat(data[startIndex].name, ", Max value: ").concat(data[endIndex].name);
`
it seemed to be expecting ariaLabel, which was odd because there's no mention of ariaLabel in the Recharts Brush documentation ([https://recharts.org/en-US/api/Brush](https://recharts.org/en-US/api/Brush).

In the end, I provided ariaLabel to the Brush component, and everything started working!

Here's the code: 
```
<Brush
  data={data}
  className={cn("brush-custom translate-y-2")}
  padding={{
    left: 5,
    right: 5,
    top: 5,
    bottom: 5,
  }}
  tickFormatter={() => ""}
  height={47}
  alwaysShowText={false}
  traveller={customTraveller}
  travellerWidth={0}
  ariaLabel="Brush"
  onChange={updateBrushIndex}
  startIndex={brushIndex.startIndex}
  endIndex={brushIndex.endIndex}
>
  <BarChart barCategoryGap={0} barGap={0} data={data} barSize={20}>
    {barChartConfig.map(renderBarChartSecond)}
  </BarChart>
</Brush>
```


I will be glad if this helps someone =) Good luck!

**Comment by ckifer** [comment]
@NereonNeo may I ask why you pass `data` directly to `Brush` and don't rely on data to be passed down from the parent chart?

I ask this because in 3.x we're removing `data` as a public property from `Brush` - ideally you are brushing a chart and that chart has the same data as the Brush.

Or was that just for the example?

**Comment by ckifer** [comment]
Added optional chaining to that property access in v2.12.7, shouldn't be an issue anymore

**Comment by NereonNeo** [comment]
> @NereonNeo may I ask why you pass `data` directly to `Brush` and don't rely on data to be passed down from the parent chart?
> 
> I ask this because in 3.x we're removing `data` as a public property from `Brush` - ideally you are brushing a chart and that chart has the same data as the Brush.
> 
> Or was that just for the example?

Hey @ckifer I didn’t notice this, thanks for the warning 🙏, I’ll fix it

**Comment by Yyana22** [comment]
hellow. how i can do I get this behavior with a one element in the array?
![image](https://github.com/recharts/recharts/assets/70588429/30b6be0d-5f1e-441f-9779-3cab66c1ccd1)

**Comment by NereonNeo** [comment]
> hellow. how i can do I get this behavior with a one element in the array?
> 
> ![image](https://private-user-images.githubusercontent.com/70588429/334136048-f8c4bd57-df6e-4a29-8fb0-1f1b262a47c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4OTQwMTgsIm5iZiI6MTcxNjg5MzcxOCwicGF0aCI6Ii83MDU4ODQyOS8zMzQxMzYwNDgtZjhjNGJkNTctZGY2ZS00YTI5LThmYjAtMWYxYjI2MmE0N2M0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDEwNTUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0NjAyYzIyYTc1ZWUwOGI5ZGJmZjdlMjc5NTg4ZjljMGUwM2VmN2I1MzBkOWM1OTQ4YjM3N2Q4OTFmY2Q2ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3Rxf0UxTk18GZqxLiEhKhBAMYHtP13w5T4QCeJLUWTo)

I don't quite understand what you mean, can you get more info about your problem plz

**Comment by ckifer** [comment]
+1. Also this seems unrelated to this closed issue. Please create another one if you'd like help! Thanks
