### ISSUE TITLE
Cannot test <ResponsiveContainer> wrapping another component like <BarChart>

### ISSUE THREAD

**Issue by dgarciasarai** [recharts/recharts#2166]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cool-feather-eo60o?file=/src/App.js)

### Steps to reproduce
Create a React component that uses a chart component, for example, a BarChart and wrap it with a ResponsiveContainer.

### What is expected?
I expect to see the full svg in the snapshot.

### What is actually happening?
The actual output with jest is:
```
<body>
  <div>
    <div
      class="recharts-responsive-container"
      style="width: 100%; height: 400px;"
    >
      <div
        style="position: absolute; width: 0px; height: 0px; visibility: hidden; display: none;"
      />
    </div>
  </div>
</body>
```

| Environment | Info |
|---|---|
| Recharts | v1.8.5 |
| React | 16.12.0 |
| System | macOS |
| Browser | Chrome |

---
I don't know if it's relevant the system or the browser, I don't think so.

**Comment by dbertella** [comment]
Having the same issue, it's quite weird but I guess in jsdom the ResponsiveComponent is not able to set width and height of its child, not sure what a solution could be

**Comment by dbertella** [comment]
Ok so I couldn't live with this (😂) and I made up a couple of solutions/workarounds (both not super nice but I guess ok)

In both cases I'm removing the ResponsiveContainer in case of tests

First of all I'm extrapolating the responsive container and its first child (in this case a line chart) in a separate component

## Solution 1 using env variable
I'm using Create React App so I have `NODE_ENV === 'test'` in my tests and as you can see in this component I'm swapping to a line chart in case o test environment 
```
import React, { FC } from 'react'
import { ResponsiveContainer, LineChart } from 'recharts'
import { CategoricalChartProps } from 'recharts/types/chart/generateCategoricalChart'

type ResponsiveChartProps = Omit<CategoricalChartProps, 'width' | 'height'> & {
  width: string
  height: string | number
}
export const ResponsiveChartWrapper: FC<ResponsiveChartProps> = ({
  width,
  height,
  ...rest
}) => {
  if (process.env.NODE_ENV === 'test') {
    console.log('hey Im a test')
    return <LineChart width={1000} height={300} {...rest} />
  }
  return (
    <ResponsiveContainer width={width} height={height}>
      <LineChart {...rest} />
    </ResponsiveContainer>
  )
}
```

## Solution 2 using a mock file
The same as above but without the part with the env variable since I'm swapping the component using a mock file.
Following this post https://thoughtbot.com/blog/mocking-react-components-with-jest I come up with the following
```
import React, { FC } from 'react'
import { LineChart } from 'recharts'
import { CategoricalChartProps } from 'recharts/types/chart/generateCategoricalChart'

type ResponsiveChartProps = Omit<CategoricalChartProps, 'width' | 'height'>
export const ResponsiveChartWrapper: FC<ResponsiveChartProps> = props => {
  console.log('Im the mock')
  return <LineChart {...props} width={1000} height={300} />
}
```
Both of the solution are a bit clumsy but at least you are able to see something in your tests.
Hopefully those will be helpful for somebody else

**Comment by Cleysond10** [comment]
You can set width as a prop on your chart component, and pass that value to ResponsiveContainer's width property. But there will be a warning in the console terminal because of **ResponsiveContainer**.

```
console.warn node_modules/recharts/lib/util/LogUtils.js:23
      The width(800) and height(500) are both fixed numbers,
             maybe you don't need to use a ResponsiveContainer.
```

To solve this problem use a boolean function to render the **ResponsiveContainer** or not depending if the type of width prop is string. For example:

```
const isWidthString = () => typeof props.width === 'string';
```

Inside the render method be like this:

```
render() {
     return (
     <>
      { isWidthString() ? (
        <ResponsiveContainer width={props.width} height={400}>
          <LineChart data={data} >
            {/* { INSERT CHART CODE HERE } */}
          </LineChart >
        </ResponsiveContainer>
      ) : (
        <LineChart width={800} height={400} data={data} >
          {/* { INSERT CHART CODE HERE } */}
        </LineChart >
      )}
    </>
     )
}
```

If you want a responsive chart, just pass `width="100%"` on props. In the test file, just pass a fixed value on width property like `width={100}` and the warning console will disappear.

This is just a quick fix, but I think it’ll do.

**Comment by sKopheK** [comment]
how come this is closed? i'm having a BarChart wrapped in ResponsiveContainer and nothing get's rendered inside of the ResponsiveContainer, using latest version of everything
```
TestingLibraryElementError: Unable to find an element with the text: Bar. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.
Ignored nodes: comments, script, style
<body>
  <div>
    <div
      class="recharts-responsive-container"
      style="width: 100%; height: 400px;"
    />
  </div>
</body>
```

test:
```jsx
test('renders a BarChart within a ResponsiveContainer', () => {
    const data = [
      { name: 'A', value: 10 },
      { name: 'B', value: 20 },
      { name: 'C', value: 30 },
    ];

    render(
      <ResponsiveContainer width="100%" height={400}>
        <BarChart data={data} title="Bar">
          <XAxis dataKey="name" />
          <YAxis />
          <Tooltip />
          <Legend />
          <Bar dataKey="value" fill="#8884d8" />
        </BarChart>
      </ResponsiveContainer>
    );

    expect(screen.getByText('Bar')).toBeInTheDocument();
  });
```

**Comment by ckifer** [comment]
What do you want us to action on here @sKopheK ?

jsdom doesn't support measurements of any kind since nothing is actually rendered. We don't render the SVG if it's height and width are 0. So you'll have to mock in order to get results like mentioned above.

**Comment by ckifer** [comment]
See this issue over on jsdom for why https://github.com/jsdom/jsdom/issues/653

I'd recommend E2E tests (Cypress, Puppeteer, etc) that open the browser when testing things that rely on screen measurements
