### ISSUE TITLE
I want to customize xaxis tick with a components

### ISSUE THREAD

**Issue by MariaFerBR** [recharts/recharts#2201]
I want to customize xaxis tick with a react component, for example, I import a file with labels, img and other thing for xaxis tick. I pass props for that component because need it.

I have my xaxis tick:
```
      <XAxis 
           dataKey="month" tickLine={false}
           tick={<CustomizedAxisTick />}
       />
```
And in other file I have that component:
```
class CustomizedAxisTick extends Component {
     state = {...}
     componentDidMount() {...}
     componentDidUpdate() {...}
      render() {
           return (
                <Fragment>
                     <Col>...</Col>
                     <label>...</label>
                </Fragment>
           )
      }
}
```
 I have been reading about custom xaxis and they say that xaxis tick only receive `<svg> <Text> <text>`.

**I want to xaxis has a carousel (like image 👇), when I press a button, it has carousel in all graph, but I don't know if that possible. Is it possible?**

![xaxis](https://user-images.githubusercontent.com/49174971/87752756-be658e00-c7c6-11ea-928c-2a4c631955e9.PNG)

**Comment by Valindo** [comment]
Hey @MariaFerBR , so you pass a component to `tick` but the components needs to return a svg tag since the chart expects it.
If you do want to use custom HTML to display data, you should consider using `foriegnObject` in svg.
Here is a really nice guide to do so.
[https://medium.com/@gaurav5430/exploring-recharts-using-foreignobject-to-render-custom-html-5c6b75d6207e](https://medium.com/@gaurav5430/exploring-recharts-using-foreignobject-to-render-custom-html-5c6b75d6207e)
