### ISSUE TITLE
ReferenceLine x/y value not working with float numbers

### ISSUE THREAD

**Issue by comatory** [recharts/recharts#2240]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/flamboyant-pond-9q5cx?file=/src/CustomChart.js)

### Steps to reproduce
Run the sandbox and render `CustomChart` component

### What is expected?
Second reference line labeled "Ref 2" should be rendered.

### What is actually happening?
Second reference line labeled "Ref 2" is not rendered.

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.6 |
| React | 16.13 |
| System | macos |
| Browser | Chrome 74 |

---
Float numbers don't seem to work for positioning reference lines along x or y axis.

**Comment by ckifer** [comment]
@comatory If you change the ReferenceLine to `y={1.5}` that works. It is because of your scale. You use the same values for both X and Y. The Y axis is rendering correctly but the X Axis actually has a value of the elements index. Set `x={18}` on your second line and see it move to the 18th element on the x-axis even though you have your dataKey set to `value`

**Comment by comatory** [comment]
OK I think maybe I wasn't clear in what I'm trying to achieve. Basically I only want to have vertical line visible in graph (which is why I'm not specifying y-axis). I put the second reference line only as an example.

So x value of reference line is always index of data? Because I'm trying to draw a line anywhere in-between values. I guess this is not what is `ReferenceLine` is used for. Is there a way to draw vertical line inside the graph and position it how I want?

**Comment by ckifer** [comment]
@comatory understood, I was giving that as an example where floats work.

No not from my understanding, but right now the scale is treating your axis as categorical with the values as categories and placing the `ReferenceLine` at index instead of value. 

If you set `<XAxis dataKey="value" type="number" />` then you get the line you want and can place it anywhere between your min and max values. Not sure if this is the graph you're expecting though.

**Comment by comatory** [comment]
@ckifer No not the graph I'm expecting. I basically want to simulate progress by showing vertical line animating from left to right. X axis is time and Y is speed, it's not linear. I have a way to calculate by which amount of px in time to move the line, however those pixel values can be fractions so it does not work with `ReferenceLine`. This component wasn't probably designed to be animated.
