### ISSUE TITLE
I want to use interval of axis and show last value in the axis same time.

### ISSUE THREAD

**Issue by Kei-Ta** [recharts/recharts#2253]
![image](https://user-images.githubusercontent.com/53590732/91032028-5b281080-e63c-11ea-9439-9759f2a93e24.png)

I want to custom the xaxis.
I want to show the axis value after an 6 interval and show last value.
But, i can't.
Tell me the good method.

**Comment by ckifer** [comment]
@Kei-Ta can you make a CodeSandbox or jsfiddle and provide a demo link to what you currently have?

**Comment by Kei-Ta** [comment]
> @Kei-Ta can you make a CodeSandbox or jsfiddle and provide a demo link to what you currently have?

I created by CodeSandbox.
https://xhobs.csb.app/
Can you see the code?

**Comment by ckifer** [comment]
> > @Kei-Ta can you make a CodeSandbox or jsfiddle and provide a demo link to what you currently have?
> 
> I created by CodeSandbox.
> https://xhobs.csb.app/
> Can you see the code?

Hey @Kei-Ta 

So I just looped over your data and added the ticks manually.

https://codesandbox.io/s/dreamy-fast-0hwjf

That isn't probably exactly what you want because the ticks are overlapping, you'll have to make a custom tick component with `tick={<CustomTick />}` that adjusts the positioning of that last tick to the right a bit.

**Comment by Kei-Ta** [comment]
Thanks!
I was able to resolve my problem!

**Comment by ckifer** [comment]
@Kei-Ta awesome, no problem. Can you close this? :)

**Comment by Kei-Ta** [comment]
Yes!
