### ISSUE TITLE
<YAxis ticks={[1,2,3,4,5]} /> is causing graph to unnaturally extend

### ISSUE THREAD

**Issue by PejmanPoh** [recharts/recharts#2294]
## Do you want to request a feature or report a bug?
Report a bug

## What is the current behavior?
A Y-axis below 8 doesn't shrink the graph (see image below).

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

Fiddle: https://jsfiddle.net/j05zfb1v/2/
![image](https://user-images.githubusercontent.com/14014629/94995973-1465f880-05a2-11eb-9a73-541af7f076c0.png)

```
<ResponsiveContainer width="100%" height={400}>
      <LineChart data={data}>
        <Tooltip />
        <Line
          type="monotone"
          dataKey="frequency"
          stroke="#FF0000"
          name="Frequency"
          strokeWidth={3}
        />
        <Legend verticalAlign="top" height={36} />
        <CartesianGrid stroke="#ccc" />
        <XAxis dataKey="date" />
        <YAxis ticks={[1, 2, 3, 4, 5]} />
      </LineChart>
    </ResponsiveContainer>
```

## What is the expected behavior?

The Y-axis is unnaturally extended. I only need the scale from 0 to 5. 

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Recharts 1.8.5. 
Latest Chrome and Firefox. All OS.

**Comment by felquis** [comment]
In your example, given the data
```js
const data = [
      {name: 'Page A', uv: 4},
      {name: 'Page B', uv: 2},
      {name: 'Page C', uv: 2},
      {name: 'Page D', uv: 2},
      {name: 'Page E', uv: 1},
      {name: 'Page F', uv: 2},
      {name: 'Page G', uv: 3},
];
```

You need to find what is the biggest number and add one to it:
```js
const max = data.reduce((prev, current) => Math.max(prev, current.uv) , 0)
const tickCount = max + 1
```

It will look like this for exemplo:
```js
<YAxis ticks={[1, 2, 3, 4, 5]} tickCount={6} />
```

Now in the YAxis, use the tickCount value in the [tickCount property](https://github.com/recharts/recharts/blob/5988b9e78ff7284dd2e247bf8667ff73fba9ece1/src/cartesian/YAxis.tsx#L44).

- Demo without tickCount https://jsfiddle.net/j05zfb1v/2/
- Demo fixed with tickCount https://jsfiddle.net/5huncgvx/

It helped me 💯 

💡 Fun fact, as of today `tickCount` prop is not mentioned in the [YAxis published doc](https://recharts.org/en-US/api/YAxis#:~:text=tickCount)
