### ISSUE TITLE
Style applied to Scatter doesn't reach the Symbols

### ISSUE THREAD

**Issue by susanafcosta** [recharts/recharts#232]
If we want to format the symbols, besides the fill, applying a style to the Scatter, won't affect the symbols.

Also the properties `tickLine` and `axisLine` on `X/YAxis` don't work in the ScatterChart context like it does for `AreaChart`

**Comment by xile611** [comment]
@susanafcosta Can you give an example ?

**Comment by susanafcosta** [comment]
```
.scatter-point {
  stroke: rgb(0, 157, 249);
  stroke-width: 1px;
  fill-opacity: 0.25;
  fill: rgb(0, 157, 249);
}

const data = [{x: 1, y: 2}, {x : 1, y: 12}, {x: 0.132, y: 19}, {x: 1,y: 1}, {x: 0.17,y: 14}]

<ScatterChart width={600} height={300}>
  <XAxis dataKey="x" tickCount={4} tickLine={false} axisLine={false}  />
  <YAxis dataKey="y" tickCount={4} tickLine={false} axisLine={false}  />
  <CartesianGrid strokeDasharray="1 1" />
 <Scatter data={data} className="scatter-point" />
</ScatterChart>
```

With this example you will see that the style won't be applied to the dots.

**Comment by Rainethief** [comment]
`tickSize` and `tick` on `X/YAxis` don't work too for the same case.

**Comment by xile611** [comment]
@susanafcosta Because we set some default  values of`fill` and `stroke` in `Scatter`, `Symbol` and some other components, so the style you set in css can't be applied to the dots. It's recommended to set such props, like `fill`, `stroke` and so on, in attributes just like svg element.

```jsx
<Scatter stroke="rgb(0, 157, 249)" strokeWidth={1} fillOpacity={0.25} fill="rgb(0, 157, 249)" />
```
Meanwhile I should remove some needless default props to make overwriting style much easier.
See #210 for more discussion.

**Comment by xile611** [comment]
@Rainethief `tickSize` and `tick` work fine. Do you have any demos ?
