### ISSUE TITLE
Slider X-axis range selection

### ISSUE THREAD

**Issue by paul-vd** [recharts/recharts#2382]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
- A slider will help select a range between point A and B on the x-axis. 
- It could be a improved implementation of the [HighlightAndZoomLineChart](http://recharts.org/en-US/examples/HighlightAndZoomLineChart) example. 
- It should also have draggable handles to select the start range and end range.

### What does the proposed API look like?
```tsx
<Chart width={600} height={400} data={data} >
    <Slider end={12} />
</Chart>
```

[example](https://bizcharts.net/product/BizCharts4/category/62/page/109) from bizcharts

**Comment by dillonreedy** [comment]
While this is a great idea, I think recharts should stick to strictly chart components, and should stay away from building custom slider components. I say this because, if we implement a slider component in the library, then potentially next week another developer could want zoom functionality that hooks up to a button-group component, then next month a switch component, etc. You can see how this can slowly get out of hand.

The way it is now, you can build a custom slider component using whatever library you want, and hook it up to custom "zoom-in"/"zoom-out" functions that you define.

So in the spirit of "Customize However I Want", I made a codesandbox that does exactly that:
[![Edit Zoomable line chart with recharts (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zoomable-line-chart-with-recharts-forked-kob6y?fontsize=14&hidenavigation=1&theme=dark)

I use the rc-slider package from NPM, and I can customize this slider however I want with some CSS. When you move the slider all the way to the right, you can see that the line-chart slightly zooms in, while moving it back to the left zooms it back out.

With a little more work, you can modify this zooming functionality to be a lot more accurate.

**Comment by ckifer** [comment]
Going to close this as stale/out of scope for recharts
