### ISSUE TITLE
content prop for Label does not work with ReferenceLine

### ISSUE THREAD

**Issue by lucasturci** [recharts/recharts#2405]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-ht35x?file=/src/index.js)

### Steps to reproduce
1. Go to sandbox
2. See the result

### What is expected?
The label content ("This should appear") should be visible. 

### What is actually happening?
The label content is not visible.

| Environment | Info |
|---|---|
| Recharts | v2.0.3 |
| React | react v16.3.1 |
| System | Linux Mint 19 Tara |
| Browser | Chrome v83.0.4103.61 |

---
Checking the HTML result, I see that the Label becomes:
```
<p content="[object Object]" viewBox="[object Object]"> This should appear </p>
```
I think that this `[object Object]` indicates something suspicious there...

**Comment by ckifer** [comment]
Hi @lucasturci 
This is because a `p` tag is not an SVG element and it is attempting to render inside an SVG.
You can use a `text` element like so: https://codesandbox.io/s/recharts-issue-template-forked-uj8w0?file=/src/index.js
Or you can wrap your `p` tag in a `foreignobject` tag like so: https://codesandbox.io/s/recharts-issue-template-forked-uj8w0?file=/src/index.js
