### ISSUE TITLE
Add minBarSize prop to BarChart

### ISSUE THREAD

**Issue by Morantron** [recharts/recharts#2441]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When there are very tiny bars (specially in a stacked bar chart), some of them are invisible.

![tiny-bars](https://user-images.githubusercontent.com/3304507/108060729-95a4c000-7057-11eb-984a-58e4d8547c61.gif)

### What does the proposed API look like?
It would be cool to add a minBarSize similar to the minAngle prop in PieChart

**Comment by xile611** [comment]
you can use `minPointSize` in <Bar/>

**Comment by Haraldson** [comment]
@xile611 This causes each segment to get at least `minPointSize`’s value as their width – but there’s still an issue with overlapping segments. If the segment you want to appear with a minimum size is before one that has an actual value, the latter will render above the former. This can’t really be solved by reversing rendering order (equivalent to reversing z-index) as we can’t really know what position an otherwise invisible segment has in the stack.

I think a better solution, than just letting the `minPointSize` value trickle down into each segment’s props, would be to take its value into account when calculating each segment’s width as a part of the whole bar. I could do this manually if each `shape` callback function’s props contained the data for all other segments, but to me it looks like I can only do logic for one and one in isolation.

This behavior would of course make the bar chart less accurate, so it should probably be some kind of opt-in via a prop, but in most cases I think this is preferable over not seeing the segment at all.
