### ISSUE TITLE
Your website dont work correctly!

### ISSUE THREAD

**Issue by mix0000** [recharts/recharts#2474]
### Reproduction image
![Error Image](https://user-images.githubusercontent.com/43841223/110520393-757c9400-811f-11eb-8efd-d07ceb02c25e.png)

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | ^16.12.0 |
| System | Windows |
| Browser | Chrome Latest |

**Comment by GuillaumeDesforges** [comment]
API reference is hardly readable right now because of this. It's quite urgent.

**Comment by iPegii** [comment]
Could it be this, API-calls are HTTP instead of HTTPS (from DevTools-console):

Mixed Content: The page at 'https://recharts.org/?p=/en-US/api' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600|Roboto%20Mono|Oswald:300'. This request has been blocked; the content must be served over HTTPS

**Comment by GuillaumeDesforges** [comment]
> Could it be this, API-calls are HTTP instead of HTTPS (from DevTools-console):
> 
> Mixed Content: The page at 'https://recharts.org/?p=/en-US/api' was loaded over HTTPS, but requested an insecure stylesheet '[http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600|Roboto%20Mono|Oswald:300](http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600%7CRoboto%20Mono%7COswald:300)'. This request has been blocked; the content must be served over HTTPS

Indeed the computed font seems to be `sans-serif` because of the request error.
This font might have another width/spacing than expected?

The workaround for now is to change the `width` of `.sidebar` to `255px` in the devtools for instance.

**Comment by GuillaumeDesforges** [comment]
I'll be rude, but I think the matter is urgent enough.

Poke @xile611
