### ISSUE TITLE
ResponsiveContainer crushes on IOS version <13.1 (undefined is not a constructor)

### ISSUE THREAD

**Issue by sandbox4013** [recharts/recharts#2491]
Main problem you're using 
`import ReactResizeDetector from 'react-resize-detector';`
in
`src/component/ResponsiveContainer.tsx`
while react-resize-detector [docs](https://www.npmjs.com/package/react-resize-detector) suggests to use 
`import ResizeObserver from 'react-resize-detector/build/withPolyfill';`

For IOS <13.1 ResponsiveContainer crushes, because it uses ResizeObserver, which available only after 13.1 IOS

I've tested on your demos

![image](https://user-images.githubusercontent.com/49528851/110792125-0f5d5180-8284-11eb-866d-31cdf0b39ac4.png)

**Comment by sandbox4013** [comment]
There's similar problem, I think
https://github.com/recharts/recharts/issues/2486

**Comment by sandbox4013** [comment]
For temporary workaround
```
npm i resize-observer-polyfill
```
```
import ResizeObserver from 'resize-observer-polyfill'

if (!window.ResizeObserver) {
  window.ResizeObserver = ResizeObserver
}
```

**Comment by timtucker** [comment]
polyfill.io is another option

**Comment by ckifer** [comment]
We've upgrade to 7.1.2 in `recharts` and it still seems to be an issue as per https://github.com/maslianok/react-resize-detector/issues/141. The import path change for `import ResizeObserver from 'react-resize-detector/build/withPolyfill';` no longer exists so there is nothing for us to do here.

The above workaround by installing the polyfill yourself is the preferred solution for consumers since 95% of browsers support `ResizeObserver`.

https://github.com/maslianok/react-resize-detector/issues/141#issuecomment-1315371976

Going to close this issue, please comment back if there are strong concerns.
