### ISSUE TITLE
There is no way to display the XAxis values equidistant for each resolution.

### ISSUE THREAD

**Issue by tobiasAuzmendi** [recharts/recharts#2562]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/determined-easley-vjr7s?file=/src/index.js)

### Steps to reproduce
No steps needed.

### What is expected?
I expect to have at least the first and the latest value on the XAxis always visible independently of the resolution or the container size. 
I also expect to have equidistant XAxis values.

### What is actually happening?
I expect to have at least the first and the latest value on the XAxis always visible independently of the resolution or the container size. 
I also expect to have equidistant XAxis values, sometimes it seems to work inconsistently because there is no logical relation between shown label positions. For example, in the second chart that you can see in the code sandbox I'm providing I expect to see the 1st, 4th, and 7th labels, but I just see the 3rd and 7th, which seems really inconsistent from the user point of view.

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | 17.0.1 |
| System | MacOs |
| Browser | Chrome |

**Comment by nikolasrieble** [comment]
## The current state 

The **interval** property on the CartesianAxis influences the tick positions. 

With the three option: "preserveStart", "preserveEnd", "preserveStartEnd" a single tick is hidden, if it overflow the allowed area. 

If the interval is set to a number, the tick width is not considered at all, but ticks are drawn overlapping. The interval number signifies the amount of ticks to be hidden between two subsequent ticks. 

0 --> show all
1 --> show every second
...

## The enhancement
Instead of changing the behaviour of all existing options, we could add a new option: 

"start-equidistant"

This could later be extended to also support "end-equidistant".

Start equidistant would position all ticks such that:
- no tick is overlapping with another 
- every nTH tick is shown (i.e. equidistant)
- the first tick is always shown. 

How does that sound? @ckifer @proke03 @Yilun-Sun

**Comment by ckifer** [comment]
Released in 2.5!

**Comment by ckifer** [comment]
enhanced in 2.9
