### ISSUE TITLE
Brush does not move if mouse leaves area

### ISSUE THREAD

**Issue by kevinlinxc** [recharts/recharts#2570]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://recharts.org/en-US/examples/BrushBarChart](https://recharts.org/en-US/examples/BrushBarChart)

### Steps to reproduce
Make the brush thinner so that it can be moved horizontally, and then move it horizontally but let your mouse leave the brush area while still holding the button down.

### What is expected?
On most scroll brushes, like the ones on web pages, your mouse can exit the area of the brush while you're holding onto the mouse button and it'll still move the brush. For example, on the left of the minimal reproduction, theres a scroll bar for all the examples, and if you click and drag that bar while exiting the bar's width, the bar still moves properly.

### What is actually happening?
The brush stops responding the instant the mouse leaves the brush, and snaps to the correct position if you enter the brush area.

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | 16.14.0 |
| System | Windows |
| Browser | Firefox 89 |

**Comment by clicktronix** [comment]
Got the same problem

**Comment by moshkainer** [comment]
same here

**Comment by beasteers** [comment]
Yeah I also find this annoying and really difficult to use. 

I'm guessing the fix is to remove mouse move handling on the Layer component:

https://github.com/recharts/recharts/blob/7c463dce9d58df96db6a71581d6f3d818dcfbccb/src/cartesian/Brush.tsx#L541

and to add it to `window` instead

https://github.com/recharts/recharts/blob/7c463dce9d58df96db6a71581d6f3d818dcfbccb/src/cartesian/Brush.tsx#L277-L285

```javascript
// add
window.addEventListener('mousemove', this.handleDrag, true); 
// and 
window.removeEventListener('mousemove', this.handleDrag, true);
// respectively
```
