### ISSUE TITLE
What should I do if I want to to add custom onClick event to LineChart?

### ISSUE THREAD

**Issue by weita0** [recharts/recharts#261]
I only found mouse event interface in bar chart and pie chart

**Comment by xile611** [comment]
@weita0  Can you describe detail what kind of event do you want to bind to LineChart?

**Comment by weita0** [comment]
For example, I would like to do something like showing details right after the user click the vertical line.

**Comment by Hectorhammett** [comment]
I'm using a Line Chart, and i'm in this trouble as well, i need the user to click a point, and i want to grab the information on that specific point so i can query the database to give the user more detailed information.

A onClick event would be greatly appretiated!. 

Excelent package for react btw.

**Comment by Hectorhammett** [comment]
@weita0 I created a fork of Recharts and added a On Click functionality:
https://github.com/Hectorhammett/recharts/tree/package

I've created it until they add a complete functionality, use it if it serves you.

To use it, in the LineChart element, add a prop called onDotClick (The event fires when you click a dot) and pass a function to it.

The function returns in the first parameter, the label on the bottom axis (x axis) and its value.

@xile611 I don't think my code is perfect, but for the moment i can work with these, you have any plans to add this feature in the future?

**Comment by weita0** [comment]
@Hectorhammett  Excellent job!

**Comment by Hectorhammett** [comment]
@weita0  Thanks! 

I could've made m code better but i was focused in fixing my problem, would you like me to ask for a Pull Request? Again, my code right now is not perfect, but if you like it, i could improve it.

**Comment by JasperStam** [comment]
@Hectorhammett 

Making a PR would be awesome as I have the exact same issue!

**Comment by xile611** [comment]
@Hectorhammett Could you submit a PR? Then I can check the changes of your code much clearer.

**Comment by jaredramirez** [comment]
I found an alternative solution, somewhat hacky though.

To accomplish getting data about the specific point clicked, I first set the `activeDot` prop on the `Line` component to false to removed it entirely. Then I created a custom label component with the same shape/styles of `activeDot` component, and added it to `Line`. Because the label has `payload` as a prop, you now have access to the data behind the point!

LineChart component:

`
import LabelAsPoint from './LabelAsPoint.js';

...

<LineChart {/* your props here */} >
    // other components such as <XAxis />, <YAxis />, < Tooltip />, etc
    <Line
        label={ <LabelAsPoint /> }
        activeDot={false}
        type="monotone"
        dataKey={ key }
        stroke={ colors[index] }
    />
/>`

custom label as a point with look/style of active dot:
`
const styles = require('styles.css');

export default class LabelAsPoint extends React.Component {
    onClick = () => {
        const { index, key, payload } = this.props;
        // you can do anything with the key/payload
    }
    render() {
        const { x, y } = this.props;
        return (
            <circle
                className={`${styles.dot}`}
                onClick={this.onClick}
                cx={x}
                cy={y}
                r={8}
                fill="transparent"/>
        );
    }
}`

With styles.css: 

`.dot:hover {
    fill: #2B98F0;
    stroke: white;
    stroke-width: .2em;
}`
