### ISSUE TITLE
"points" attribute showing "[object Object]" for all points in the attribute value (looks like bad serialization)

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#2610]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://recharts.org/en-US/examples](https://recharts.org/en-US/examples)

### Steps to reproduce
Using DevTools, show the DOM element of the SVG of the chart data series (i.e. `<g class="recharts-layer recharts-line">`)

### What is expected?
`points` attribute should not contain "[object Object]"

### What is actually happening?
`points` attribute contains "[object Object]"

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | 16.8.1 |
| System | Mac/Windows |
| Browser | Chrome/Firefox/Safari |

---
```
<path stroke="#8884d8" stroke-width="1" fill="none" points="[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]" width="468" height="383" class="recharts-curve recharts-line-curve" type="monotone" d="M80,296.08C106,315.26829999999995,132,334.4566,158,334.4566C184,334.4566,210,12.660000000000007,236,12.660000000000007C262,12.660000000000007,288,238.3236,314,238.3236C340,238.3236,366,204.16000000000003,392,204.16000000000003C418,204.16000000000003,444,242.46,470,242.46C496,242.46,522,232.88500000000002,548,223.31000000000003"></path>
```

**Comment by pabrodez** [comment]
This error originates in `Curve.tsx`:
![image](https://user-images.githubusercontent.com/18014700/127627827-e0bd180c-b6aa-4975-bf1d-5c59d2ac4189.png)
`filterProps()` is supposed to filter out those keys of the props that are not attributes of the svg element, but I cannot find `points` as a `path` attribute anywhere in the MDN docs. That function uses an array of compiled attributes of all SVG elements. Because `points` is an attribute of other SVG elements, it'll be included in `path` anyways:
![image](https://user-images.githubusercontent.com/18014700/127629174-2a73fac9-439a-4bbd-a761-eb8eac2c2b16.png)

I believe `filterProps()` should be passed an array of attributes to include and not just use a huge general list of all possible SVG attributes. Or even have an object with names of used svg elements for keys and an array of their attribute for values.
