### ISSUE TITLE
Issue with latest 0.15.0 release - labels cut off

### ISSUE THREAD

**Issue by patryk0605** [recharts/recharts#268]
Most examples x-axis labels are being cut off like so: 

![image](https://cloud.githubusercontent.com/assets/7227636/18786771/9c413f3e-816d-11e6-8d3a-da98f69efe70.png)

**Comment by patryk0605** [comment]
@emilebres Yes, I had to downgrade back to 0.14.2 for my project as all my charts had become cut off on both the `YAxis` and `XAxis`.

**Comment by jozsi** [comment]
+1

Before:
![image](https://cloud.githubusercontent.com/assets/840815/18792054/bdc9dc88-81bd-11e6-8e74-b3d128898125.png)

After:
![image](https://cloud.githubusercontent.com/assets/840815/18792070/cc78be2a-81bd-11e6-8bd5-e935db7779d5.png)

**Comment by techniq** [comment]
@xile611 No surprise, this is due to using the new `<Text>` component instead of the standard svg `<text>`.  I overlooked some components passing `dy` explicitly to the labels/ticks based on their `orientation` prop, which now need to use the new `verticalAnchor` prop (which makes it cleaner and gives support for multi-line, etc.

The diff to CartesianAxis is this:

![screen shot 2016-09-23 at 12 04 28 pm](https://cloud.githubusercontent.com/assets/177476/18792839/1dd9d55c-8186-11e6-8e13-a2c0815d413a.png)

I'm currently looking to see anywhere else needs to be updated and will send a PR soon (hopefully).
