### ISSUE TITLE
Line chart looks different for the same data

### ISSUE THREAD

**Issue by dstuff** [recharts/recharts#2682]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/simple-line-chart-forked-t45pj)

### Steps to reproduce
Add 2 lines on the chart. One should has same values, but be trimmed from start and end. In other words, if 1st line has 5 dots with values [1,2,3,4,5] then 2nd should has values [2,3,4]

### What is expected?
The lines should be the same and overlay each other

### What is actually happening?
Lines have a difference between each other

| Environment | Info |
|---|---|
| Recharts | v2.0.8 |
| React | 17.0.2 |
| System | MacOS 11.6 |
| Browser | Chrome 94.0.4606.71 |

---
Perhaps it expected behavior?

**Comment by cle-skov-dk** [comment]
That's due to the behaviour of lineType which is monotone and since the two last data points are null.  See the behaviour of the types here: https://github.com/d3/d3-shape#curves

If the type is set to linear the lines overlaps completely as seen below.
![image](https://user-images.githubusercontent.com/49151515/140727299-092d2f66-c1a5-4e10-9a8d-2f6392faac5b.png)
