### ISSUE TITLE
BarChart - time scale and type number makes bars to be too wide

### ISSUE THREAD

**Issue by louislefebvre** [recharts/recharts#2711]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-time-scale-bars-too-wide-gbcxy)

### Steps to reproduce
- Use Barchart component
- Have type to number, scale to time and a domain on the x-axis
- Tooltip component has to be inside the barchart component
- Have some data with a date key and unix-timestamp value (although any value would work there I guess)
- Test with minimum one item object in the data array, then two, then three. After four items available, bars seems to scale “correctly”, although they still overflow the graph width.

### What is expected?
Bars width should automatically scale and not overflow the graph by being too wide.

### What is actually happening?
- Bars are too wide and not scalling
- Bars width overflow the graph width
- When mouse hovering a bar, the tooltip background is even wider than the bar itself

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 16.14.0 |
| System | Ubuntu 21.04 |
| Browser | Firefox Developer Edition 95.0b4 |

---
I am working on a barchart graph with date on the x-axis, I found out that I had to convert my date iso timestamp (21-11-09T11:00:00Z) to unix time (1636455600) and then format them through tickFormatter.

But also somehow if I remove the type to number, scale to time and a domain on the x-axis, somehow it also works, so I also don't get what the time scale parameter does.
Somehow I feel like I don't understand something with the time scale or like there is something available that allows me to use iso timestamp without converting them to unix time?

**Comment by bozerkins** [comment]
Got the same problem. 

To be honest, recharts is great and creates beautiful charts, except for when you need time-series charts. Unfortunately time-series is the most common use-case for using charts.

**Comment by dubecker** [comment]
Is there a solution to this yet? I have the same problem.

**Comment by bozerkins** [comment]
My solution was moving to https://www.chartjs.org/ where they support this out of the box.

**Comment by ailchenkoDynamo** [comment]
I have the same problem!!!

**Comment by ailchenkoDynamo** [comment]
My example 
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/98591714/212083477-c435dc83-2c76-47fd-b479-a1dbf7d09d76.png">

**Comment by ailchenkoDynamo** [comment]
@ckifer do you need an example for reproduce it?

**Comment by ckifer** [comment]
@ailchenkoDynamo sure that would help - the original sandbox is broken. This issue is from a while ago and I'm seeing it for the first time now (recharts didn't have active contributors for a while, I just got made a maintainer the other week). 

I don't currently have time to take this issue on but if anyone wants to contribute feel free to look into it

**Comment by ailchenkoDynamo** [comment]
@ailchenkoDynamo [Codesandbox](https://codesandbox.io/s/recharts-area-chart-with-date-axis-forked-n872ux?file=/src/App.js:828-876)

**Comment by ailchenkoDynamo** [comment]
I fixed it for my case: [Codesandbox](https://codesandbox.io/s/recharts-area-chart-with-date-axis-forked-n872ux?file=/src/App.js)

**Comment by ckifer** [comment]
time scale is not equivalent to band scale (time vs categorical)

See this SoF for an answer on the data-viz side of things https://stackoverflow.com/a/48279536/8050147 (don't use bars for time series data)

But if you do want to use bars, `padding="gap"` is the correct solution. Just know that your dates will be converted to numbers in order to render correctly

If you do not use the `scale` parameter and do not set `type="number"` your data will be treated as categorical (each date is a category) and will potentially render out of order.

Going to close this. Hoping to support time series more explicitly in the future
