### ISSUE TITLE
Can't change the css of anything

### ISSUE THREAD

**Issue by hrqmonteiro** [recharts/recharts#2785]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/hrqmonteiro/hrqmonteiro.github.io](https://github.com/hrqmonteiro/hrqmonteiro.github.io)

### Steps to reproduce
Just try to change the css classes of anything and nothing happens. I want to change the color of the 'text' on my chart:

![pint](https://user-images.githubusercontent.com/17055027/154147934-5aac9cc8-1783-478d-a113-6cc6109745ff.png)

These are the classes:

![pint2](https://user-images.githubusercontent.com/17055027/154147974-8c572890-2504-4904-b8b9-4b06301f1b61.png)

But, when i try to change in my css:

![pint3](https://user-images.githubusercontent.com/17055027/154147998-2426292f-c19b-4c74-a5e1-b150995b59fa.png)

Nothing changes.

### What is expected?
The CSS changes to actually have an effect.

### What is actually happening?
Not changing?

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 16 |
| System | Linux |
| Browser | Firefox/Chrome |

**Comment by hrqmonteiro** [comment]
Really? Nothing?

**Comment by plxmargaux** [comment]
Hi @hrqmonteiro 

I think you could make a custom component for your items, just as described here https://recharts.org/en-US/examples/CustomizedLabelLineChart 
That way you can change your text colour. However, I was able to change the text colour by targeting the `recharts-cartesian-axis-tick-value` class instead of the `text` HTML tag 

Hope this helps, 

cheers
