### ISSUE TITLE
Fix broken link in examples page

### ISSUE THREAD

**Issue by reburke286** [recharts/recharts#2803]
## Do you want to request a feature or report a bug?
report a bug
## What is the current behavior?
https://recharts.org/en-US/examples/SimpleScatterChart 
when navigating to Try the Demo in the Code Sandbox link it takes you to the SimpleLineChart instead
## What is the expected behavior?
that code sandbox opens with the scatter chart example instead of the line chart example
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
n/a this is recharts.org

**Comment by dillonreedy** [comment]
Hey @reburke286 

I have been developing a storybook for this exact problem. The ScatterPlot charts can be found [here](https://dillonreedy.github.io/recharts-storybook/?path=/story/recharts-scatter-chart--simple).
![image](https://user-images.githubusercontent.com/3454995/162803907-f0d77f7e-5d7a-4ccf-8547-b3ec807d44b3.png)

It's not much right now due to very it being in very early stages, but I'd say change some values on there, look at the code, and if you wanna make a pull request to update the values passed in, you're more than welcome to do so.

**Comment by ckifer** [comment]
Link is fixed, resolving
