### ISSUE TITLE
Performance Issue - Recharts using deep compare instead of shallow compare combined with object re-use

### ISSUE THREAD

**Issue by billneff79** [recharts/recharts#281]
Recharts isn't taking full advantage of React's rendering optimizations for sub-trees. The "shallowEqual" function in PureRender is actually a deep-equal, which is very expensive and re-computed several times on any given event (e.g. mouse moving over the graph).  For a graph with hundreds or thousands of points, this can become very slow.

Part of the reason a deep equality was likely used was that some of the props, like the axis maps and ticks, were being generated as brand new object on every render, even though the data in them was the same, so a shallow equality would have failed.

In order to remedy this situation, a couple of changes are needed
1. modify the shallowEqual function to actually be a shallow equality, only checking one level deep for === equality on all keys in an object
2. ANY object that would be expensive to generate when looping over a large dataset (e.g. axismaps, ticks, etc.) is generated only when necessary and stored in state to be passed down to child components as props. Since the objects will pass === checks in this scenario, child components never re-render unless necessary, and determining necessity is cheap now.

These changes have already been made in pull request #277, so this issue can be marked as resolved when that is complete.

**Comment by abologna-r7** [comment]
Agree... Finding rendering everytime when interacting with the chart on mouseover. I have a dynamic set of Areas inside a AreaChart component, depending on the dataset I get from the server. While I do not rerender unless the data changes on my end, the component still rerenders on mouse over interactions with the chart, which in some sense annoys me a little bit, and potentially can hurt our main component in terms of performance, since we'll be dealing with GBs of data influx each hour.

**Comment by xile611** [comment]
Thanks to @billneff79. This has been fixed in version 0.0.16.
