### ISSUE TITLE
Position ticks around group, not in center.

### ISSUE THREAD

**Issue by gippslandphysiotherapy** [recharts/recharts#2830]
Hello,

I'm trying to position the X-Axis' ticks _around_ the group, instead of directly in the centre, so I can segment the group data more clearly. However, I cannot find anything in the docs on how to do this. I would also like to apply this to the cartesian grid behind the chart.

See the desired positioning in red: 
![Edited](https://user-images.githubusercontent.com/98795000/163283862-014023fc-2a46-4e30-8ccf-bed300a15bc6.jpg)

This is my current code:

	<ResponsiveContainer aspect={3}>
		<BarChart data={data} margin={{ top: 0, left: -2, bottom: 0, right: 0 }}>
			<XAxis dataKey="name" tick={{ fill: "#151515" }} stroke="#ebebeb" tickMargin={7} tickSize={10} />
			<YAxis tick={{ fill: "#151515" }} stroke="#ebebeb" tickMargin={7} tickSize={10} />
			<CartesianGrid stroke="#ebebeb" />
			<GraphTooltip />
			<Bar dataKey="Male" fill="#0404cf" label={{ fill: "#fff", fontSize: 12 }} />
			<Bar dataKey="Female" fill="#ff729f" label={{ fill: "#fff", fontSize: 12 }} />
		</BarChart>
	</ResponsiveContainer>

**Comment by rgallison** [comment]
I am also in need of this

**Comment by petii** [comment]
@gippslandphysiotherapy @rgallison So out of curiosity I played around with this a bit and came up with https://codesandbox.io/s/stacked-bar-chart-forked-ly4ow8?file=/src/App.tsx by hiding the X axis, but still leveraging the calculations there to set up some [customized components](https://recharts.org/en-US/api/Customized).

<img width="524" alt="Screenshot 2023-03-06 at 22 45 40" src="https://user-images.githubusercontent.com/2715418/223240782-f96d0148-6bed-4497-8a6f-31e185d73cf5.png">

## Explanation

According to the docs and examining the props passed to _component_ you can get some help by defining the type for it. Categorical charts have axis maps, from where we can levarage the hidden X axis to get the coordinates in the chart's dimensions and to get the domain elements and the bandSize (that is used for the tooltip area I think) for the x axis.

From there a chart autopsy gives us the required info to be able to set up a `CartesianAxis` with some custom ticks:

```
       Y |
       a |    88
       x |    88   ##
       i | ## 88   ## 
       s | ## 88   ## 88
xAxis.y >+-------+--------
         ^       |
      xAxis.x    |
         |<----->|
          bandSize
```

So with the domain elements indices, the starting coordinate and the bandSize, you can set up the `CartesianTickItem` array (depending on what the actual text that you want to show is) and pass that into a `CartesianAxis` with some additional coordinates as to where to actually render it.

And since we already calculated the coordinates for the ticks, it's essentially free to add a customized `CartesianGrid`, with specified custom `verticalPoints`.

Now the drawback to using the customized component is that you have to manually specify the coordinates and the drawback to using chart internal state is that I'm not sure how stable that interface is, so you need to take extra care when bumping recharts version.

Hopefully this helped!

**Comment by ckifer** [comment]
Change your `XAxis` scale to `scale="band"` and all of this comes for free

<img width="533" alt="image" src="https://github.com/user-attachments/assets/b4f4c83a-7238-42d8-a4ea-d406ea1bcc74">

Going to close this
