### ISSUE TITLE
typescript definition

### ISSUE THREAD

**Issue by MichaelBitard** [recharts/recharts#290]
I wasn't able to find a typescript definition for recharts, is there anyone working on something like that?

**Comment by clementdevos** [comment]
I'd be interested as well, i might do it soon as i'm currently working on it. 
I've already contributed to DefinitelyTyped so it should not take me too much time.

**Comment by tvedtorama** [comment]
If you just want to be able to use `import` instead of `= require(...)` then you can get away with this partial d.ts file:

```
declare module "recharts" {
	export const BarChart: any
	export const Bar: any
	export const Tooltip: any
	export const Legend: any
	export const Area: any
	export const AreaChart: any
	export const LineChart: any
	export const Line: any
	export const XAxis: any
	export const YAxis: any
	export const CartesianGrid: any
	export const ResponsiveContainer: any
}

```

You might have to add further classes to the definitions, as they are not complete.  **Note:** There are no arguments, properties, or anything here - it just helps get the import going.

**Comment by Flavien** [comment]
This issue is closed, but I can't find the type declarations. Can someone point me to the pull request where this was implemented?

**Comment by goldcaddy77** [comment]
For those that still can't find them:

```
`npm install @types/recharts` or
`yarn add @types/recharts`
```

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/recharts
