### ISSUE TITLE
Piechart - accessibility issue

### ISSUE THREAD

**Issue by lakshmihnm** [recharts/recharts#2907]
First section of piechart is not getting read by screen reader.

**Comment by cscrosati** [comment]
Hey @lakshmihnm, can you update your created issue to the guidelines described in https://github.com/recharts/recharts/blob/master/CONTRIBUTING.md

This issue is not actionable without a more thorough description of your problem. Providing a repro on how this is not working for you would greatly help.

Also, screen reader and browser have very different support levels, to a point that some combination works better than others. Can you report which combination is demonstrating your problem?

**Comment by saghan** [comment]
@lakshmihnm In addition to what [cscrosati](https://github.com/cscrosati) said, the issue does not repro in google chrome using the [screen reader](https://chrome.google.com/webstore/detail/screen-reader/kgejglhpjiefppelpmljglcjbhoiplfn?hl=en) made by google. I tried to repro [here](https://recharts.org/en-US/examples/TwoSimplePieChart)

**Comment by mgifford** [comment]
ChromeVox is the only Google screen reader, but it really isn't commonly used. 
It is useful for basic testing @saghan but has flaws. VoiceOver or NVDA are generally the preferred screen readers for testing. Sadly, I'm writing this on a Chromebook at the moment so am not able to do testing with either of those.

See: 
https://webaim.org/projects/screenreadersurvey9/

**Comment by ckifer** [comment]
Going to close this in favor of the broader accessibility improvement issue #2801 as it should be encompassed there. We can reference this later from that issue if needed.

Since the maintainers aren't around it will be tough for any of these issues to be addressed until ownership is transferred (if ever). Sorry!
