### ISSUE TITLE
Make regular javascript the default, Not typescript. 

### ISSUE THREAD

**Issue by pmeaney-sqrt** [recharts/recharts#2933]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Keeping the codebase simple and not overcomplicating it with Typescript.
Javascript is the basis of the Javascript ecosystem, not Typescript.

### What does the proposed API look like?
Javascript, not Typescript.

**Comment by gchartier** [comment]
TypeScript makes working with libraries like this a lot easier due to autocomplete, type checking props to prevent you from misusing the API and just overall allowing you to have a better understanding of the API.

Personally, I wish it leaned into TypeScript even more than it does already for the reasons stated.

**Comment by evbo** [comment]
@pmeaney-sqrt you may be interested in [scala.js](https://www.scala-js.org/): It transpiles without typescript type checking and you can enforce much stronger typing.

everybody wins :)

**Comment by ckifer** [comment]
Going to close this because going from TypeScript to JavaScript is a fundamentally backwards move that nobody gets anything from. 

TypeScript transpiles to JavaScript, it isn't as if TypeScript is an entirely different language. We benefit from TypeScript in refactorability, readability, testability, self-documentation, and much more - even more so that this library has many contributors that come in and make singular changes - JS makes that so much harder.
