### ISSUE TITLE
Clickable custom tooltip for ScatterChart

### ISSUE THREAD

**Issue by swapNXplore** [recharts/recharts#2961]
Hello i tried this click option in ScatterChart and tooltip is getting display on clicking dots, but the tooltip is not getting hide on mouse leave or outside click. It's just get displayed on clicking different dot's.
So i have to do following 2 things

1. I want a default behaviour of tooltip, as it should be display on hover and hide on mouse leave.
2. Clickable link/button in tooltip.

any help would be appreciated!
Thanks in advance!

![clickable tooltip](https://user-images.githubusercontent.com/108389819/188392993-c4a49c5b-e5da-4870-b091-39617493776b.png)

 "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.3.0",
    "react-scripts": "5.0.1",
    "recharts": "^2.1.13"
  },

**Comment by ckifer** [comment]
related to #2967

You can use escape to dismiss the tooltip when `trigger="click"`

Otherwise we'll use #2967 to track dismissing on outside click

the default tooltip should display on hover and behave as described in 1. 2 however, is tricky
Other charting libraries such as [chart.js](https://www.chartjs.org/docs/latest/samples/bar/horizontal.html) do not allow text selection within their tooltips which also means that adding a clickable button would not work either. The mouse move event is continuously attempting to find and show the tooltip for the nearest point to the cursor.

@swapNXplore what is the usecase for having a hoverable, clickable tooltip?

Will label this `pending response`

**Comment by ckifer** [comment]
Going to close this as stale until a response

Links/buttons in tooltips are also not great for accessibility which is another reason for closing this specific request
