### ISSUE TITLE
Display scatter and line series in composedChart with different time frame

### ISSUE THREAD

**Issue by AdamU34** [recharts/recharts#2983]
<img width="1323" alt="Screenshot 2022-09-23 at 13 26 04" src="https://user-images.githubusercontent.com/50705364/191950584-5c8c8eba-a247-4d54-8eac-e88a1e2722fd.png">

"x: 15" is missing in the chart

### What problem does this feature solve?
I want to display real-time data as Scatter and Line series in composedChart. The data includes timestamp and value. However, timestamp can be different sometimes in each series live data. 

### What does the proposed API look like?
Data looks like something like this: 

const lineData = [
  { x: 11, c: 10 },
  { x: 12, c: 20 },
  { x: 13, c: 5 },
  { x: 15, c: 26 },
  { x: 16, c: 30 }
]

const scatterData = [
  { x: 11, b: 17 },
  { x: 12, b: 13 },
  { x: 13, b: 10 },
  { x: 14, b: 30 },
  { x: 16, b: 22 }
]

**Comment by ckifer** [comment]
Hi, sorry this is an issue for you. Without the maintainers around any changes are going to be tough/impossible to get through,
Best bet with this would be to combine the datasets or show two separate x-axes. I took your data and tried to make it look the best I could -- that ends up being one array of objects rather than multiple.

[![Edit recharts-issue-template (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-jeu6u4?fontsize=14&hidenavigation=1&theme=dark)

**Comment by AdamU34** [comment]
Thanks for your help. But, this is not fixing my issue :(

**Comment by ckifer** [comment]
Hi @AdamU34, I'm now a maintainer of the project and can maybe help with this if its still an issue.

I think I'm going to need more of an example of what you want it to look like though. I'm slightly confused on your issue

**Comment by ckifer** [comment]
Going to close this as stale

[![Edit recharts-issue-template (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-2hcks3?fontsize=14&hidenavigation=1&theme=dark)

One more shot at it - adding `connectNulls` to Line seems to get what you want?
