### ISSUE TITLE
Isomorphic app : document is not defined

### ISSUE THREAD

**Issue by piRstone** [recharts/recharts#301]
Hi,
I have a problem with server side rendering.
When I pass data via props to my chart, reload my server and refresh my page, I get an error : 

```
ReferenceError: document is not defined
at Text.calculateWordWidths (/Users/piRstone/Documents/node/dashboard/node_modules/recharts/lib/component/Text.js:101:26)
at Text.updateWordsByLines (/Users/piRstone/Documents/node/dashboard/node_modules/recharts/lib/component/Text.js:81:43)
at Text.componentWillMount (/Users/piRstone/Documents/node/dashboard/node_modules/recharts/lib/component/Text.js:67:12)
[...]
```

Even if I pass static data from a const in the chart's file it still doesn't works.

When I tried Recharts without server side rendering, everything worked fine but as soon as I set SSR, I got this error.

I tried to remove the `data={this.props.data}` from the chart declaration so my page displayed correctly (without chart of course) but if if reset this, I still get this error.

I thought it was a bug as said in #39 (probably resolved but apparently not)

**Comment by magalhini** [comment]
I'm having the exact same issue, @piRstone. Did you manage to find a solution?

For what it's worth, I think the same issue applies whenever using a server-side development solution (like next.js or react-create-app do, for example). The components don't display because that development server can't find the `document` property.

Any leads would be much appreciated :)

**Comment by foobahh** [comment]
@piRstone @magalhini can be solved by rendering based on the execution environment, i used https://www.npmjs.com/package/exenv and just render a spinner if document is not defined.
