### ISSUE TITLE
Missing Properties in Type Definitions for TooltipPayload

### ISSUE THREAD

**Issue by tsinghammer** [recharts/recharts#3033]
- [ ] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62852](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62852)

### Steps to reproduce
See Definitely Typed PR

### What is expected?
In our project we need reference to the original line formatting in order to generate our custom tool tip. So far we have to treat the passed payload as any and just ignore this.

### What is actually happening?
See Definitely Typed PR

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 18 |
| System | X |
| Browser | X |

---
I've created a pull request to add the missing types here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62852
Do you think we can go with these?

**Comment by ckifer** [comment]
Noting here that _all_ properties on each `Line`, `Bar`, etc. _could_ be passed to the tooltip, these are just items that people might use often.

Since this is merged in definitely typed, will make a PR for parity within recharts types. Note that we shouldn't add n types for n consumers usecases though. Types can be extended.
