### ISSUE TITLE
Can't set domain prop of PolarRadiusAxis lower than 120

### ISSUE THREAD

**Issue by alexandernst** [recharts/recharts#3048]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/simple-radar-chart-forked-t8d9eo?file=/src/App.tsx)

### Steps to reproduce
Look at the RadiusAxis. It shows "120"

### What is expected?
It should show "100". Furthermore, the axis line is overflowing the RadarChart

### What is actually happening?
It shows "120"

| Environment | Info |
|---|---|
| Recharts | v2.1.6 |
| React | 18.0 |
| System | Mac OS |
| Browser | Chrome |

**Comment by ckifer** [comment]
Hi @alexandernst,

Since you have a data point that is greater than your specified domain max `100` the chart is attempting to not overflow the chart. The domain is not adjusting because in order to overflow data you need to set `allowDataOverflow` to true. (this overflows the chart at "Math" due to the `120`). 

As for the axis line overflow, if you were to move the axis line to any of the lines of the chart they would match up meaning the `120` in the axis line is the same value as the `120` at the vertex of each category. Change the `angle` prop to `30` in your example to see what I mean. 

Closing this as completed, feel free to comment back if you have any questions
