### ISSUE TITLE
Remove react/no-array-index-key comments

### ISSUE THREAD

**Issue by marcalexiei** [recharts/recharts#3273]
Follow to [discussion](https://github.com/recharts/recharts/pull/3270#discussion_r1084889331) in #3270

For every `eslint-disable-next-line react/no-array-index-key` we should find a valid string or number instead of using an index

**Comment by BuddhikaGeasman** [comment]
@ckifer If this is not resolved yet. Any chance I could take it?

**Comment by ckifer** [comment]
@BuddhikaGeasman there was a recent report of an issue in the latest comments here https://github.com/recharts/recharts/issues/4004 

If you can find the error mentioned there that would be more important than removing these lint ignores. I actually think removing these ignores is impossible without re-thinking some things. Any time we use data to try and address these there are duplicate key errors

**Comment by DrJShoff** [comment]
This error also appears in scatter chart when dots are drawn on top of each other. This causes duplications of dots if the chart is resized or the data updated as the chart can't keep track of all dots as they have the same key.

**Comment by imagineLife** [comment]
Perhaps components that render chartable items should have _(more) required unique props_.  

### Uniquely Identify Items
One recurring error in duplicate keys is revealed when 2 chartable items (pie slices, dots on a scatter, bars, could be more) have the same cartable "data": x values, y values, etc.

**One idea** to tackle this seems to be _set more required props_ for renderable elements: something like a "name", or "id". There does not seem to be enough required props that an be leveraged for a unique key when iterating over data to render.    


**Another idea** could be to add a required prop called uniqueId (or key or something) where developers who use recharges must bring-their-own key to recharts. This approach would perhaps be a bit more “breaking”. Recharges, itself, would “pass along” the key provided by the developer to the charting rendering. The benefit here would be that recharges, itself, stops “caring” about the key the way it is currently trying to.

**Comment by ckifer** [comment]
Imo we should only put this burden on the consumer if they are iterating through things themselves. If we iterate, we need to be the ones who ensure keys are unique. 

> set more required props for renderable elements

The consumer shouldn't have to have more data in their data in order to render a chart without errors

> developers who use recharts must bring-their-own key to recharts

This doesn't work because that key will be the same for every element of every component giving us the same problem we currently have

Not really sure of a great way - we can hash the whole object but that has the same chances of collision. We can generate a UUID based of the object but same thing, we can use a UUID but that negates the purpose...
