### ISSUE TITLE
Align value on X/Y axes

### ISSUE THREAD

**Issue by PointSingularity** [recharts/recharts#3284]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I currently have data that goes into the negative. Using the current API there is no way to align the axes and show the data points going into the negative. Currently, you can either show all the data with misaligned axes, or align the axes but the data is hidden.

```tsx
<YAxis
  dataKey="Height"
  type="number"
  tickCount={y.tickCount}
  interval={0}
  ticks={y.ticks}
  domain={['auto', 'auto']}

  allowDataOverflow={true}
/>;
<XAxis
  dataKey="Perimeter"
  domain={['auto', 'auto']}
  tickCount={x.tickCount}
  ticks={x.ticks}
  interval={0}
  type="number"

  allowDataOverflow={true}
/>;

```
![image](https://user-images.githubusercontent.com/56246797/214882543-884b97d9-3519-46d1-b3b5-199d0a11599f.png)

If I set the domain to [0, 'auto'] I get this, which is almost right, but the label is cut-off, and the lines are not shown below 0.
![image](https://user-images.githubusercontent.com/56246797/214887982-aef0855f-6f27-425b-b273-bb249a1d9efe.png)

[Code reproduction](https://stackblitz.com/edit/react-ts-dq9xqh?file=Chart.tsx,data.tsx,App.tsx)

### What does the proposed API look like?
Adding a property directly to the (Line)Chart component called 'alignAxes' that accepts a numerical value, which exists on both axes, which the component then tries to align.

Alternatively, it could be a similar property on both of the axes, that accepts the name of the other axis and the numerical value where they should align.

All of the data also needs to be shown, without being cut-off.

**Comment by ckifer** [comment]
Oh a reference line totally skipped my mind in the discussion :D

```jsx
<ReferenceLine
     y={0}
     strokeWidth={1.5}
     strokeOpacity={0.7}
     stroke="#666"
 />
```
not 100% sure if adding labels to that is completely doable though (1 label is for sure but not sure about all of the x-axis labels).

---

@PointSingularity if you can get your chart to look how you would like it with this solution we'll probably close this issue. I had thought that other charting libraries have the behavior you describe but it turns out they don't really.

Check out highcharts https://www.highcharts.com/demo/column-negative
https://www.highcharts.com/demo/area-negative

Agreed with @nikolasrieble on the above, we shouldn't introduce new API flags just to enable a certain behavior like this. We'll continue to rely on the domain specification for now. If research turns out that this use-case is valid I could see a case for allowing datapoints below the rendered x-axis. From a usability perspective though X-Axis labels might get covered or overlapped on which we don't really want.

**Comment by nikolasrieble** [comment]
The trick to get the ticks positioned in the right spot is to use a custom tick which renders the tick identically, but only shifted in position.

**Comment by PointSingularity** [comment]
@ckifer @nikolasrieble Thank you both for your detailed answers!

From my point of view, I wanted to have visual continuity with the 0, but I can see that introduces a lot of other problems I haven't thought through.

Using the reference line makes sense.

I manged to get a good [result](https://stackblitz.com/edit/react-ts-v6dzrb?file=Chart.tsx,data.tsx,App.tsx) !
Thanks again!

**Comment by nikolasrieble** [comment]
@PointSingularity Thank you for your input! Would you like to add your example to our website as an example for other to learn from and benefit?

**Comment by PointSingularity** [comment]
> @PointSingularity Thank you for your input! Would you like to add your example to our website as an example for other to learn from and benefit?

Sure thing 😄 
What do I need to do?

**Comment by nikolasrieble** [comment]
I recently added another users code example in this PR, you could follow the same pattern, that would be very appreciated! https://github.com/recharts/recharts.org/pull/245

**Comment by PointSingularity** [comment]
> I recently added another users code example in this PR, you could follow the same pattern, that would be very appreciated! [recharts/recharts.org#245](https://github.com/recharts/recharts.org/pull/245)

Yeah, I'll do that! (probably won't have time today/tomorrow though)
