### ISSUE TITLE
Vertical layout BarChart is rendering one bar less

### ISSUE THREAD

**Issue by joselisboaa** [recharts/recharts#3464]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-oyfsm2?file=/src/index.js)

### Steps to reproduce
Changing the layout to horizontal and the dataKey to XAxis the behavior changes and works normally

### What is expected?
For each array element render a bar (just like horizontal layout)

### What is actually happening?
Is rendering one bar less

| Environment | Info |
|---|---|
| Recharts | v2.4.2 |
| React | 18.2.0 |
| System | Windows  |
| Browser | Google chrome & Firefox |

**Comment by petii** [comment]
@joselisboaa Heyo, your example did not work for me. It was missing a react import and the initial rendering of the element, something like
```javascript
import React from "react";
import ReactDOM from "react-dom";

ReactDOM.render(<SimpleBarChat />, document.getElementById("root"));
```
And also in my experience, codesandbox does not play nicely with _ResponsiveContainer_.

For a minimal example something like this could be considered:
```jsx
    <BarChart
      width={500}
      height={300}
      layout="vertical"
      barSize={20}
      data={data}
    >
      <XAxis />
      <YAxis
        hide={true}
        interval={0}
        type="category"
        scale="point"
        dataKey="name"
      />
      {protocolTypes.map((entry, index) => (
        <Bar
          key={`bar-${index}`}
          fill={color?.[index % color.length]}
          dataKey={entry}
        />
      ))}
    </BarChart>
```
Which for me does not result in one bar less, but instead only shows three. The strange thing was that the X axis ticks were not in ascending order, so after explicitly specifying that it is a numeric axis (with `<XAxis type="number" />`) I arrived at the described behaviour.

For which the reasons I found are a combination of:
1.  Bar charts by default are making grouped bar charts which with the shape with the data you are providing for every point is creating a lot of "empty groups".
2. `scale="point"` interacts with the Y axis in a manner so that the first group's area extends out of the chart

For 1. you could switch to a stacked bar chart by including a _stackId_ on the _Bar_s, like:
```jsx
        <Bar
          key={`bar-${index}`}
          fill={color?.[index % color.length]}
          dataKey={entry}
          stackId="this can be anything, but should be shared across bars"
        />
```

For 2., not using point scale results in
grouped | stacked
--  | --
<img width="526" alt="Screenshot 2023-03-21 at 18 39 56" src="https://user-images.githubusercontent.com/2715418/226695476-e6df8e63-155d-4b4c-b403-8c11e0cf6bad.png">  |  <img width="526" alt="Screenshot 2023-03-21 at 18 40 10" src="https://user-images.githubusercontent.com/2715418/226695520-1f338210-3b50-4827-9eff-0b78ee45ebef.png">

Source: https://codesandbox.io/s/recharts-issue-template-forked-wvrfyv?file=/src/index.js
