### ISSUE TITLE
Bar Chart does not group bars centered on x-axis tick

### ISSUE THREAD

**Issue by karlrez** [recharts/recharts#3552]
- [X] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bar-graph-with-categories-u06ppv?file=/src/App.tsx)

### What is expected?
The groups of bars will be centered over the x-axis tick like this example:

![image](https://user-images.githubusercontent.com/47090434/233999158-6a6f51d0-5b0d-4a88-b623-b93f606bf246.png)

### What is actually happening?
The bars are showing either as left or right-aligned:
![image](https://user-images.githubusercontent.com/47090434/233999363-f5d6f0c3-3b29-419a-ba0b-1b02068caa13.png)

| Environment | Info |
|---|---|
| Recharts | v2.5.0 |
| React | 18.2.0 |
| System | Windows |
| Browser | Chrome |

**Comment by ckifer** [comment]
Hey there - this is because all of your categories are technically including all of the other categories as `null` datapoints.

If you see that jobs, machine, areas, tools all go in a row they are reserving space for the other categories that have been specified with your `type` x axis key.

Similar to this issue https://github.com/recharts/recharts/issues/2666

**Comment by karlrez** [comment]
hi @ckifer, thank you for this information. Yes, is a duplicate, so I will close this one.
