### ISSUE TITLE
Label at top of YAxis is not showing

### ISSUE THREAD

**Issue by jarodsim** [recharts/recharts#3590]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ibb.co/30kSf5R https://ibb.co/p1jfjJV https://ibb.co/rwWhxTN](https://ibb.co/30kSf5R https://ibb.co/p1jfjJV https://ibb.co/rwWhxTN)

### Steps to reproduce
Just add a label at the top of the Y axis

### What is expected?
That the label appear at the top of the Y axis

### What is actually happening?
it's not showing

| Environment | Info |
|---|---|
| Recharts | v2.6.2 |
| React | 18.2.0 |
| System | Operating System: Kubuntu 22.04 KDE Plasma Version: 5.24.7 KDE Frameworks Version: 5.92.0 Qt Version: 5.15.3 Kernel Version: 5.17.0-1020-oem (64-bit) Graphics Platform: X11 Processors: 8 × AMD Ryzen 3 3300X 4-Core Processor Memory: 15.5 GiB of RAM Graphics Processor: AMD Radeon RX 6600M |
| Browser | Google Chrome 113.0.5672.92 64 bits |

**Comment by ckifer** [comment]
Its there, its just being cut off because it is outside of the chart boundary.

` <YAxis label={{ value: "index", position: "top", offset: 10 }} />` - should get you roughly what you want.

Please see [this](https://github.com/recharts/recharts/issues/2354#issuecomment-758850445) for some insight on what label positioning options look like and why they act how they do

**Comment by ckifer** [comment]
Going to close this as stale, feel free to comment back to continue discussion
