### ISSUE TITLE
I can't show the legend of Rechart graph in docx

### ISSUE THREAD

**Issue by altay-oz** [recharts/recharts#3626]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-28jfjy)

### Steps to reproduce
Click the button and check the word document file.

### What is expected?
In the word document it is expected to get the legend correctly.

### What is actually happening?
In the word document, we only see it a very small portion of it in the upper left corner.

| Environment | Info |
|---|---|
| Recharts | v2.7.1 |
| React | 18.2.0 |
| System | Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux |
| Browser | Firefox 102.12.0esr (64-bit) |

**Comment by ckifer** [comment]
Did this work before or has it never worked?

If it never worked before (or even if it did really), without explicitly supporting chart exports as a feature there isn't really any action we can take on this besides creating that feature request (then after that is established this would be a supported issue). 

If you have an indication of why it isn't rendering and it is affecting something else as well then maybe it's worth it to fix this.

**Comment by altay-oz** [comment]
It never worked but I was expecting to have a well made docx with recharts' legend. 

The document renders correctly.

![Screenshot_2023-06-18_15-28-56](https://github.com/recharts/recharts/assets/8396667/ad8ea81b-6396-4870-aa38-7bab44ce55b5)

**Comment by nikolasrieble** [comment]
Wonderful example, I wish it would work for me. Following the link you sent, and clicking the export button, what I get is this file: 

[example.docx](https://github.com/recharts/recharts/files/11792110/example.docx)

and when I open it, I see 

<img width="644" alt="Screenshot 2023-06-19 at 21 23 20" src="https://github.com/recharts/recharts/assets/27995606/7918b3bf-eb0f-45cf-95a2-96c8a905ceb1">

That being said, if this worked, I would add it to the storybook examples right away.

**Comment by altay-oz** [comment]
The file above also works. I am using LibreOffice 7.0.4.2 in Debian 11.

![Screenshot_2023-06-19_21-53-02](https://github.com/recharts/recharts/assets/8396667/3c02cfb1-890d-49df-9823-8c8dc50a2a1c)

**Comment by ckifer** [comment]
Hmm, even if it works in specifically on Libre office in order to be considered a solution it should work and render as any image would. I pulled down the sandbox locally with the same result (can't see image).

But back to the issue with the legend. I think this may just be a timing thing - The chart is downloaded and is never actually rendered so I think internally all of the functions to calculate the position of the legend haven't finished yet. Can you add a timeout delay and see if the issue persists?

**Comment by ckifer** [comment]
Oh.... the blob that gets created is HTML output. If I paste only that output into a fiddle I get something like this: https://jsfiddle.net/d9a5swh8/

Could be that office / libre office behaves differently than a browser when rendering certain styles. Nothing really we can do about that.

**Comment by ckifer** [comment]
Going to close this as I believe it is out of scope of the library. It seems LibreOffice doesn't support html absolute positioning...hard to tell for sure, but this isn't a recharts issue

**Comment by MatthewSkingley** [comment]
I came upon this issue because my chart, which I actually happen to be writing eventually into a docx, does not contain a legend.

In a server-side context, I'm using `renderToStaticMarkup()` from react-dom paired with JSDOM to extract an the SVG representing the chart.

In my specific scenario, I simply could not see the legend because I'm working exclusively with SVG, and what's in the main `<svg>` tag, whereas the `<Legend>` component in Recharts renders outside of the SVG in pure HTML.

Because of this, I had to hack together my own legend and control the line colours so that they match. It might be nice to see a version of Recharts where the Legend component renders inside the parent SVG component with pure SVG syntax.

**Comment by ckifer** [comment]
Hi! This makes sense I think. 

Without supporting chart export explicitly, exporting remains out of scope or do at your own risk. 

There are benefits to the legend being html such as easier styling, positioning, familiarity, etc. 

Even so a change like this would be breaking and would need to happen in a major version release.

**Comment by JPVRS** [comment]
Just going to chime in here, I'm in need of a charting library that can be exported as SVG. Chart.js doesn't do it, D3 is not pleasant to work with IMO, and Recharts seemed to be perfect until I realized that none of the SVGs contained a legend. Really frustrating and I'm currently back to creating the charts by hand in Illustrator. Please add this.

**Comment by ckifer** [comment]
I hear you man, I do. 

The recharts team is two individuals right now who can only work on the project in their very small amounts of spare time. If someone wants to contribute something that would allow this then I'm all ears for ideas. Otherwise it would be very low on the priority list against other features and bugs and it would probably be on the order of years before it happened (unless we have a drastic change in regular contributors). 

Right now, fully supporting a chart export is just too much unfortunately

**Comment by JPVRS** [comment]
Fair enough… it’s easy to forget sometimes that people are maintaining these things with limited time and help. Thanks for what you do, even if it doesn’t fit my use case right now.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
