### ISSUE TITLE
Automatic bar width is set to zero when there is only one data point

### ISSUE THREAD

**Issue by Nicolapps** [recharts/recharts#3640]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tiny-bar-chart-forked-gppdsy?file=/src/App.tsx)

### Steps to reproduce
* Create a `BarChart` with a `XAxis` of type `number` and a `domain`
* Use a data set that has only one data point

### What is expected?
The bar has a width that makes it visible.

### What is actually happening?
The bar has a zero width by default, which makes it invisible.

| Environment | Info |
|---|---|
| Recharts | v2.7.2 |
| React | 18.2.0 |
| System | macOS Ventura 13.4 |
| Browser | Safari 16.5, Firefox 114.0.2, Chrome 114.0.5735.133 |

**Comment by Nicolapps** [comment]
It is worth noting that if your chart is affected by this behavior, it is possible to set manually `barSize` on `Bar` in the case where there is only one data point (and leave it `undefined` otherwise to keep using the automatic width).

**Comment by ckifer** [comment]
This behavior is the same in previous versions right? (I think it is)

**Comment by Nicolapps** [comment]
Yes, I have the same behavior with earlier versions.

**Comment by graup** [comment]
This is still broken and the `barSize` workaround doesn't work for me. Does anyone know any other workarounds?

**Comment by graup** [comment]
I created another example showing how this works (or doesn't work) with date axes: https://codesandbox.io/p/sandbox/tiny-bar-chart-forked-vk9fyv?file=%2Fsrc%2FApp.tsx

Here is what I expect:
![Screenshot 2024-03-19 at 11 41 19](https://github.com/recharts/recharts/assets/898549/2bb99284-5222-4267-9ec5-74491f7d4f20)
![expected](https://github.com/recharts/recharts/assets/898549/a9474dc3-38ef-44ef-b0e3-267a70aaeba8)

I don't believe the PR achieves what's in the second image, instead making the bar always 1/3 the width of the chart. How can we have one bar that's the size of one tick?

**Comment by graup** [comment]
After much digging, I have concluded that there is no easy & correct fix for this.

- The automatic bar size calculation in `getBandSizeOfAxis` uses the minimum distance between any two adjacent categorical values. This is smart because, with a numerical domain used categorically, we cannot determine the bar width just from the domain or axis ticks. Consider a domain of [0, 10] with one bar per whole number; we expect a bar to have a width of 1/10 of the chart width. Now if instead data points were on 0.5 increments, we expect a bar to have a width of 1/20.
- The corollary to this is that when we only have one data point on a numerical categorical axis, it is logically impossible to calculate how wide it should be. What does a single tick as "5" mean on the domain [0, 10]? We cannot know if this should be 1/10 or 1/20 wide.
- So in this case, we need some more information from the user. Currently, it is possible to provide an absolute `barSize` but this doesn't scale responsively.
  -  Maybe we could allow percentage values for `barSize`, so the user could calculate it themselves (e.g. `"10%"` if you expect 10 bars in one chart.
  - Alternatively, it would be nice to be able to provide a logical value, e.g. `barWidthInDomain=1` meaning "in this chart, one bar shall be 1 unit wide in my domain". Then we could use the axis.scale() method to determine coordinates of a virtual data point at (`ticks[0] + barWidthInDomain`) and thus use the existing `getBandSizeOfAxis` calculation. In other words, there needs to be a way for the user to tell us how to interpret the domain.

@ckifer @nikolasrieble does this make sense?

**Comment by nikolasrieble** [comment]
> feat(BarChart): support percentage for barSize. Fixes #3640 #4390

Love the writeup, agree very much. At this point it is mostly an aesthetic defaults question. Your solution makes sense, thank you for your contribution ❤️

**Comment by ckifer** [comment]
Released in https://github.com/recharts/recharts/releases/tag/v2.12.5
