### ISSUE TITLE
How to remove border when use BarChart with LinearGradient?

### ISSUE THREAD

**Issue by varnguyen** [recharts/recharts#3646]
Hi,

How to remove border when use BarChart with LinearGradient?

Here is the BarChart definition with LinearGradient:

````
<ResponsiveContainer width="100%" height="100%">
      <BarChart
        width={500}
        height={300}
        data={data}
        margin={{
          top: 0,
          left: -10,
          right: 0,
          bottom: 12
        }}
        barCategoryGap="100%"
      >
        <defs>
          <linearGradient
            id="colorUv"
            x1="0"
            y1="0"
            x2="0"
            y2="100%"
            gradientUnits="userSpaceOnUse"
           >
            <stop offset="0" stopColor="#01C27F" />
            <stop offset=".25" stopColor="#1aa67c" />
            <stop offset=".5" stopColor="#1aa67c" />
            <stop offset=".75" stopColor="#1aa67c" />
            <stop offset="1" stopColor="#293531" />
          </linearGradient>
        </defs>
        <XAxis
          dataKey="price"
          fontSize={11}
          reversed
          interval={0}
          tickSize={4}
        />
        <YAxis
          fontSize={11}
          tick={{ fontSize: 11 }}
          tickSize={4}
          padding={{ top: 15 }}
        />
        <Tooltip
          content={<CustomTooltip side="bids" />}
          cursor={false}
        />
      <Bar
          dataKey="vol"
          fill="url(#colorUv)"
          animationBegin={400}
          animationDuration={400}
          animationEasing="linear"
          radius={[1, 0, 0, 0]}
        />
      </BarChart>
    </ResponsiveContainer>
````

This is chart showing:
> ![current](https://github.com/recharts/recharts/assets/33864311/0c6fd339-2dcc-4556-b5c5-eca47bf6e002)

My expect:
> ![expect](https://github.com/recharts/recharts/assets/33864311/b3d517c1-24b8-48e9-a442-89ce5b842caa)

Thanks & Best regards!

**Comment by ckifer** [comment]
Hey there, 

Could you modify this sandbox to replicate your chart?
https://codesandbox.io/s/bar-chart-spacing-mq3g4n?file=/src/App.tsx

I kind of did, but I'm not sure what your data looks like. Using `-1` for `barCategoryGap` seems to work (though I know that isn't ideal)

**Comment by hieutt2-ssi** [comment]
Hi @ckifer,

barCategoryGap="-1" it working but why do you say isn't ideal ?

Example:
https://codesandbox.io/s/bar-chart-spacing-forked-3dg4gg?file=/src/App.tsx

Thanks & Best regards!

**Comment by varnguyen** [comment]
Hi @ckifer,

barCategoryGap="-1" it working but why do you say isn't ideal?

Example:
https://codesandbox.io/s/bar-chart-spacing-forked-3dg4gg?file=/src/App.tsx

Thanks & Best regards!

**Comment by ckifer** [comment]
Eh only because just as you say, the expectation would be at 0 you have no gap. Where -1 might cause some unwanted overlap. 

If it doesn't then all good! Later the library should probably adjust the behavior to align to the expectation

**Comment by varnguyen** [comment]
Anyway, thanks for your solution.

**Comment by torztomasz** [comment]
I am wondering if it’s possible to remove the gaps between bars without setting `barCategoryGap` to `-1`. The issue with this approach is that it causes the bars to overlap. This isn’t very noticeable for low quantity of data points, but for larger amounts, it looks quite off:

31 data points:
![Image](https://github.com/user-attachments/assets/37918946-81c3-4919-b727-9ef235d228a3)

~350 data points:
![Image](https://github.com/user-attachments/assets/d1eeb57a-9d8a-41fc-b3a1-e058de138eeb)

I believe the expected behaviour would be for `barCategoryGap: 0` to work as the issue creator described.

**Comment by torztomasz** [comment]
I have checked the code and seems that the issue lies in 374-377 lines of code when the `bandSize` is not an integer in `ChartUtils.ts` file:
```tsx
    let originalSize = (bandSize - 2 * offset - (len - 1) * realBarGap) / len;
    if (originalSize > 1) {
      originalSize >>= 0;
    }
```

Let's assume that:
* `bandSize = 97.5`
* `offset = 0`, because the `barCategoryGap` is set to 0
* `len = 1` as we are displaying one bar per category
* `realBarGap = 4` let's set it to the default value, it does not affect the calculations anyway

Given these parameters the `originalSize` is equal 97.5 but after the bitwise right shift by 0, which floors the value, it becomes 97. The 0.5 difference is what makes the gap. When the 376 line is commented out, the gap vanishes correctly. I am sure that the floor operation is there for a reason but can not discover why. I am happy to contribute a PR but some explanation would be helpful @ckifer
