### ISSUE TITLE
Getting cartesian coordinates for a mouse position

### ISSUE THREAD

**Issue by krispyp** [recharts/recharts#365]
Hi,

I'm creating a scatter plot, however I'm adding my own mouse so I can implement a rectangular selection. Given my mouse coordinates, is there any way I can calculate what the cartesian coordinates should be, eg:

getCartesianCoordinatesForMouse(mouseX, mouseY, width, height,...)

Thanks!

Chris

**Comment by xile611** [comment]
@krispyp You can add `onMouseEnter`, `onMouseLeave`, `onMouseMove`, `onClick` in `LineChart` (or `BarChart`, `AreaChart`, `ComposedChart`), and you'll get `chartX`, `chartY` in callback.

**Comment by krispyp** [comment]
Hi,

Thanks for the reply. Unfortunately I can't use this, as I'm using hammer.js to support touch interaction. I need some way to obtain the cartesian (chart) coordinates given some mouse coordinates.

**Comment by krispyp** [comment]
Also from looking at the code chartX/chartY are generated using:

export const calculateChartCoordinate = (event, offset) => (
  {
    chartX: Math.round(event.pageX - offset.left),
    chartY: Math.round(event.pageY - offset.top),
  }
);

So this doesn't actually give the cartesian coordinates, it gives the coordinates offset by the chart axes.

I think I need to use d3 scales.

**Comment by krispyp** [comment]
A bit of background. We're trying to add marquee rectangular drag selection to create a database query that will filter the points by their real X and Y data values (not pixels).

I can do this if I have access to your d3 scale which is internally as xAxis.scale() (in fact I'll want xAxis.scale.invert() to convert pixel values to data values). However you don't expose this anywhere that I can get at easily - e.g. it's not in the props of any customisable elements.

I'd like to make the change and put together a PR but I'd like to know how you would prefer to architect a solution. I need to be able to query, for a given (e.g.) ScatterChart, the xAxis and yAxis objects that you're currently initialising in `ScatterChart.render()`. 

Currently I'm looking at rendering a hidden ReferenceArea or something, because these include xAxis and yAxis in their props. Then using a React ref to expose this. This is quite a nasty hack.

**Comment by blank-blank-blank** [comment]
+1

**Comment by blank-blank-blank** [comment]
FWIW, you can sort of hack around this by setting a custom label class that calls a passed through props function to update the state with the dots x and y. with all of your dots x antd y values if you sort them by x and sort your original data by x you can match them up.

**Comment by kamekazemaster** [comment]
Anything new on this issue / feature request?

**Comment by LewisW** [comment]
You can work this out yourself by providing your own scale and then running this through invert. Here's some sample code:

```
const domain = d3.scaleTime().domain([d3.timeDay.floor(data[0].date), d3.timeDay.ceil(data[data.length - 1].date)]);
const tickFormat = domain.tickFormat();
const ticks = domain.ticks();
```

and then for the chart:
```
 <BarChart
                    data={data}
                    onMouseMove={e => {
                        console.log(domain.invert(e.chartX));
                    }}
            >
                <XAxis 
                       dataKey="date"
                       name = 'Time'
                       scale={domain}
                       ticks={ticks}
                       domain={domain}
                       tickFormatter={tickFormat}
                       type = 'number' />
            </BarChart>
```

You probably won't need to provide your own ticks etc. but I've included them just in-case they help. Also I'm using d3's scaleTime function but I assume you can replace it with an appropriate function for whatever unit you're using.

**Comment by sseira** [comment]
@LewisW this would require you inputing the range as well right? 
So in the case this graph is in a responsive container this wouldnt be enough

**Comment by zotijs** [comment]
Any workarounds for this one? I am using a `ResponsiveContainer` too as @sseira mentions in his comment above

**Comment by klintan** [comment]
> W, you can sort of hack around this by setting a custom label class that calls a passed through props function to update the state with the dots x and y. with all of your dots x antd y values if you sort them by x and sort your original data by x you can match them up.

Is this the only way to get the height of each bar without hovering the actual "bar" ? It would all be so much easier if the hovering was the "cursor"-area and not just the bar (internally recharts uses the "cursor" area it seems.

**Comment by vtarelkin** [comment]
@krispyp please provide any solution on this!

**Comment by vtarelkin** [comment]
@zotijs any luck on this?

**Comment by zotijs** [comment]
@vtarelkin nope nothing, sorry.

**Comment by evankirkiles** [comment]
@vtarelkin @zotijs I was able to implement a horizontal and vertical zoom in the style of Plotly using a similar technique to what LewisW described, though not using d3. It's based on the chart's cartesian coordinates, and not restricted to just data points like the example of zooming in the docs is.

<img width="847" alt="Screen Shot 2022-06-20 at 7 17 05 PM" src="https://user-images.githubusercontent.com/30581915/174689195-65fb640f-6d6f-4eaf-bc3e-3e0c6f3b660b.png">
<img width="859" alt="Screen Shot 2022-06-20 at 7 17 10 PM" src="https://user-images.githubusercontent.com/30581915/174689202-412d8b13-d98f-4d2c-8ad4-78b3cc4395a8.png">

It requires essentially rescaling the `chartX` and `chartY` of your mouse click (or `offsetX` and `offsetY`, depending on where you are listening to the events), based on the pixel scale of each axis. It's just math.

1. It's easy enough to be able to get the `offsetX`, `offsetY`, `clientWidth`, and `clientHeight`. Just wrap your `ResponsiveContainer` in a div that preserves its responsiveness (just give it the same styling and make the `ResponsiveContainer` fill that div with `width: 100%` and `height: 100%`. You need to create a `ref` to this div so we can get the bounding box values when we need them:

```typescript
const containerRef = useRef<HTMLDivElement>(null);
// ...
return (
  <div style={{ width: "100%", height: "100%" }} ref={containerRef}>
    <ResponsiveContainer width="100%" height="100%">
      // ...
    </ResponsiveContainer>
  </div>
)
```

2. Okay, so we can do that––and now we can access our `width` and `height` dims in real client-side pixel space. Now, you're also going to need to get the ranges of each axes, and their starting / ending values. If you're setting the domain yourself, you already have that, but if you don't want to have to calculate the data range yourself you can just listen into the `domain` attribute of each of your axes and nab the `dataMin` and `dataMax` values to get Recharts' calculation, apply padding, and save the domains to a `ref`. It's important you don't save to `state` here, as that will cause an infinite loop.
```typescript
const yDomain = useRef<[number, number] | null>(null);
const [yDomainState, setYDomainState] = useState<[number, number] | null>(null);
// ...
<YAxis
   type="number"
   domain={([dataMin, dataMax]: [number, number]) => {
      const padding = (dataMax - dataMin) * 0.1; // i thought this looked fine
      if (yDomainState) {
         yDomain.current = yDomainState;
      } else {
         yDomain.current = [dataMin - padding, dataMax + padding]];
      }
      return yDomain.current;
   }}
  // ...
/>
```

3. The if conditions above are meant to synchronize the domain with a `state` that is calculated by the user's zoom. But now with the `yDomain` reference, we can access the range of our y axis (just do the same for your x if you desire, i managed my X axis in a higher component because I was synchronizing across charts). Now, we can write a function that returns cartesian coords for mouse events on our original div and do whatever we'd like with them:

```typescript
// gets the axes position from a mouse click on the div
const getCartesianCoordinates = (
  e: React.MouseEvent<Element, MouseEvent>
): [number, number | null] | [null, null] => {
  if (!containerRef.current || !domain) return [null, null];
  const MARGIN_LEFT = 67;
  const MARGIN_TOP = 5;
  const MARGIN_RIGHT = 5;
  const MARGIN_BOTTOM = 34;
  const rect = containerRef.current.getBoundingClientRect();
  const x_p =
    (e.nativeEvent.offsetX - MARGIN_LEFT) /
    (rect.width - MARGIN_LEFT - MARGIN_RIGHT);
  const y_p =
    (e.nativeEvent.offsetY - MARGIN_TOP) /
    (rect.height - MARGIN_TOP - MARGIN_BOTTOM);
  const x_range = domain[1] - domain[0];
  let y_pos = null;
  if (yDomain.current) {
    y_pos =
      yDomain.current[1] - y_p * (yDomain.current[1] - yDomain.current[0]);
  }
  return [domain[0] + x_p * x_range, y_pos];
};
```

4. This will return you the correctly scaled cartesian coordinates of whatever click event you passed into it. The margins might be off by a pixel or two, I just eyed it––also not sure if they are different for other users, but they seem to hold across scaling the container. Now you can use the `getCartesianCoordinates` function in your MouseHandlers for the actual cartesian coordinates.

If you're still interested, I can write up a gist tomorrow to show the Plotly-like zoom reference areas. It's really a shame that Recharts makes this so difficult...

**Comment by vtarelkin** [comment]
@evankirkiles saw you comment on email. Didn't dig in it cause made it few month ago
 with such a func
```

    //The pixel bounds for the LineChart minus padding and transform to real values

    const getYGraphCoordinate = (param) => {
        const chartBoundsY = {min: cartesianGridRef.current.props.height - 10, max: 10};

        // Convert the pixel value from the cursor to the scale used in the chart
        const lowerPixelDifference = param - chartBoundsY.min;
        const pixelBoundsDifference = chartBoundsY.max - chartBoundsY.min;
        const step = lowerPixelDifference / pixelBoundsDifference;
        const boundsDifference = graphBounds.top - graphBounds.bottom;
        const value = boundsDifference * step;
        return Math.ceil(value + spectraBounds.bottom)
    };
```

where param in the func is

`     let yValue = getYGraphCoordinate(e?.chartY);`

and  x is `e.activeLabel`
