### ISSUE TITLE
Legend verticalAlign="top" in cartesian chart disables the accessibilityLayer

### ISSUE THREAD

**Issue by davidlyons** [recharts/recharts#3659]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://recharts.org/en-US/examples/SimpleLineChart](https://recharts.org/en-US/examples/SimpleLineChart)

### Steps to reproduce
1. Add `accessibilityLayer` prop to `<LineChart>`  
    or any cartesian chart component, LineChart, BarChart, AreaChart, etc.

    Press Run, focus the chart, then press the left or right keyboard arrow keys.  
    accessibilityLayer works as expected.

2. Add `verticalAlign="top"` to `<Legend />`

    Press Run, focus the chart, then press the left or right keyboard arrow keys.  
    accessibilityLayer no longer works.

### What is expected?
Keyboard arrows keys should move the tooltip and vertical cursor across the chart dots.

### What is actually happening?
The tooltip and vertical cursor disappears.

| Environment | Info |
|---|---|
| Recharts | v2.7.2 |
| React | 18.2.0 |
| System | macOS Ventura 13.4 |
| Browser | Chrome 114.0.5735.198 |

**Comment by ckifer** [comment]
Weird. No idea why that would effect anything 😅 

@julianna-langston want to take a look?

**Comment by julianna-langston** [comment]
I got it.

So, the accessibility layer gets the cursor to appear by spoofing a mouse movement along the top edge of the chart. When the legend is placed at the top of the chart, the cursort spoofs going over the _legend_, instead of the chart, so the cursor doesn't appear.

I have a PR that updates the mouse movement calculations to put it in the middle of the chart, which should give us some more resiliency on the math.

https://github.com/recharts/recharts/pull/3660

**Comment by ckifer** [comment]
Thank you!!

**Comment by ckifer** [comment]
merged in #3660 - will be in next release

**Comment by nikolasrieble** [comment]
Closing the issue, as the fix landed.

**Comment by davidlyons** [comment]
Thanks!
