### ISSUE TITLE
The tooltip does not include data from all charts

### ISSUE THREAD

**Issue by eno-tech0** [recharts/recharts#3669]
The tooltip only shows data for the Line graph, but nothing for the Area graph. How to display data for both Area and Line graphs in the tooltip? Here's an example with a problem: https://codesandbox.io/s/recharts-tooltip-with-different-data-kksx5s?file=/src/App.js
---

Edit from maintainer:

The tooltip does not include data from all charts _when a separate dataset is passed to chart prop `data` and specified on `Line/Area/etc` prop `data`_

**Comment by ckifer** [comment]
Hi,

This looks like its because you are using a separate dataset for each chart. Combining these will allow the domain to be calculated correctly for both datasets.

https://codesandbox.io/s/recharts-tooltip-with-different-data-forked-ww6hpj

Ideally your example should work, so I'll label this as a bug

**Comment by eno-tech0** [comment]
@ckifer Thanks for your help)

**Comment by ckifer** [comment]
Merged in #3733, will be out in next minor

**Comment by ckifer** [comment]
Released, closing!
