### ISSUE TITLE
Accepting function instead of dataKey 

### ISSUE THREAD

**Issue by tarrencev** [recharts/recharts#383]
It would be great if it were possible to pass a function that evaluates to a data points value instead of passing a `dataKey`

i.e.

```javascript
<Line dataKey="uv" />
```

could be equivalent to

```javascript
<Line value={ (data, index) => data[index]["uv"] } />
```

That would allow Recharts to make less assumptions about the passed `data`s format and would enable more use cases like computing values

**Comment by xile611** [comment]
@tarrencev Thanks! We'll think about this feature.

**Comment by loris** [comment]
Would be great, common use-case is to compute the value by adding multiple values together.

**Comment by bali182** [comment]
In my opinion it would be much better for `value` (or whatever the data accessor function's prop name is) to take a function `Array.map` would take, like this:

```
<Line value={ record => record.uv } />
<Line value={ (record, index) => record.uv } />
<Line value={ (record, index, data) => record.uv } />
```

Would this disrupt the current codebase much? Based on `dataKey` being a string I suspected that under the hood the data is simply retrieved by something like this:

const { dataKey, data /* wherever this comes from */ } = this.props
const values = data.map(record => record[dataKey])

So here the mapper function could be simply dropped in

**Comment by xile611** [comment]
I think it's easy to allow the `dataKey` to receive nested key like `'a.b.c'` now.

**Comment by tarrencev** [comment]
@xile611 I think passing nested keys misses out on a lot of the flexibility enabled by a mapper function and is also a breaking change, since
```
{  a.b.c: 1  }
```
is a valid object.

@bali182's solution seems ideal.

**Comment by loris** [comment]
@tarrencev agree, a mapper function gives way more flexibility. By the way, nested paths could be easily achieved with an helper function such as `get` in `lodash`:

```
import { get } from 'lodash/fp'
...
<Line value={get('a.b.c')} />
...
```

**Comment by xile611** [comment]
@tarrencev Nested keys means that we can get data in such case:

```js
  [{ today: { a: 1, b: 2 }, yesterday: { c: 1, d: 2 }, }]
```

by dataKey `'today.a'` or `'yeterday.d'`.

Anyway, I'll refactor recharts to allow the `dataKey` be a simple string, a nested string  or a map function.

**Comment by bali182** [comment]
@xile611  that's great news!  I'm not trying to pry, but wouldn't it semantically make more sense to not call the function version `dataKey`? Maybe keep dataKey as it is and introduce a new property? I know it would introduce some  complexity to check that dataKey and let's say dataFn are mutually exclusive, and also mess with proptypes, so it might not such a good idea. But passing a function to a prop named dataKey seems a bit strange...

**Comment by tarrencev** [comment]
@xile611 I understand, but in the case that someone is currently using a object with a "nested key string" as the key, like 
```
[{ today.a: 1 }]
````
introducing nested key strings would be a breaking change. Doesn't affect me, but just wanted to make sure it's considered

**Comment by xile611** [comment]
@tarrencev I think the developer should make sure that the `dataKey` can be used to map the correct values. We just provide three options to make it's more flexible to specify the values.  Do you agree?

**Comment by xile611** [comment]
@bali182 Yeah, I know it's not semantical to call a function as `dataKey`. But I want to use unified props for such case( add data in `LineChart` and specify a attribute in `Line`). Something just like [d3-shape stack](https://github.com/d3/d3-shape#stack_keys),  we can specify strings as keys or accessor functions as keys too.

Meanwhile I want to support series-like data too which will bring another props too...

**Comment by erayalakese** [comment]
I see that commit reverted. Any updates for nested data keys? @raviteja83

**Comment by ZephD** [comment]
Using a function is great. However, the legend key has no name, now. How to set?

**Comment by ZephD** [comment]
Use "name" field.

**Comment by rm-hull** [comment]
Can the documentation for `Area` and `Bar` be updated to reflect this prop can take a function (assuming they can?)

**Comment by rahul-nath** [comment]
I'm getting the following error when setting `dataKey` to a callback function:

`Warning: Encountered two children with the same key`

This is my callback function:
```

        const getVal = (val) => {
           if(x === "something")
               val[x]/1000
           else
               val[x]
        }

        return (
          <Area
            key={x}
            dataKey={getVal}
            type="monotone"
            name="test"
            unit="cm"
          />
```

**Comment by gaurav5430** [comment]
@rahul-nath your error is probably related to having duplicates in your data?
Do you not get this error when you use the dataKey as a value ?

**Comment by phyntom** [comment]
when I try to pass function reactchart is not displaying anything
`  
let data = [ {key: "TOKEN VEND COMPLETED",value: {count: 5, total: 26500, avg: 5300}]       
<BarChart width={600} height={300} data={props.items}>
            <XAxis dataKey='key' stroke='#8884d8' />
            <YAxis />
            <Tooltip />
            <Legend verticalAlign='top' height={36} />
            <CartesianGrid strokeDasharray='4 4' />
            {/* <CartesianGrid stroke='#ccc' strokeDasharray='5 5' /> */}
            <Bar name='number'  dataKey={() => getVal()} stackId='1' fill='#1d2834' />
`
can someone help me to make it work

**Comment by gaurav5430** [comment]
> when I try to pass function reactchart is not displaying anything. Sample of my data looks like this
> 
> `let data = [ {key: "TOKEN VEND COMPLETED",value: {count: 5, total: 26500, avg: 5300}];`
> 
> can someone help me to make it work

If you can add the code for how you are calling the function, or specifying on the Line component, people might be able to help.

**Comment by philgapp** [comment]
First off, I see this is closed, and I appreciate the discussion and quick work! Sorry for generally rehashing and being a noob.

Second, I am trying the following:

```
let getGenericValue = (x)=>{return x['ti']}
let getSpecificValue01 = (x)=>{return x['ti']['specific01']}
<Line type="monotone" dataKey={getGenericValue['specific']} name="sma200" stroke="#039BE5"  />
<Line type="monotone" dataKey={getSpecificValue01} name="ema12" stroke="#4CAF50" />
```

getSpecificValue01 works and plots on the chart correctly, as per JarLowrey's post.

getGenericValue doesn't work, I'm sure because I'm doing it wrong. Is there a way I could write a function to pull the nested name/value? 

I would prefer not to have a few dozen of the following for a series of charts for all my data points:
`let getSpecificXX = (x)=>{return x['ti']['specificXX']}`

Is there a solution that allows me to create a signal generic function and either pass the name of the nested key or somehow call the key from that resulting 'one-level-up' array/object (like I'm trying to do with getGenericValue above)?

Thank you very much, and please let me know if you need more info!

**Comment by gaurav5430** [comment]
I wouldn't expect `getGenericValue['specific']` to work. In my experience, recharts either accepts a simple/nested property accessor or a accessor function in the `dataKey`. `getGenericValue['specific']` is neither of those. it seems like `x` is your data, so unless i misunderstood, in this case you should just be able to use: 
`"ti.specific"` ?

`<Line type="monotone" dataKey={"ti.specific"} name="sma200" stroke="#039BE5"  />`

@philgapp

**Comment by philgapp** [comment]
@gaurav5430 thanks for the reply! 

x I think is the key, and the data? My object is multi-layered, and x in this case is the 0,1,2,3,etc. that was automatically assigned to the array I am pushing objects into and that I couldn't get into the chart otherwise.

So with your example I would need ti.**x**.specific - but that is a no-go because I need a loop (which the solution gives me, but I need a function for each and every 'x.specific' which are numerous and will even grow. I am sure with one or two functions I can build something more robust, but I was hoping there is just something I'm missing here that would work instead :)

**Comment by gaurav5430** [comment]
Oh ok, in that case, I misunderstood, If you can give an example data structure, I guess we might be able to fit in to one of the existing pattern or may be some suggestions to restructure the data

**Comment by gaurav5430** [comment]
Meanwhile. I have tried to document the different ways of passing in data, along with some workarounds as mentioned in this issue here: https://medium.com/@gaurav5430/exploring-recharts-different-ways-of-accessing-data-d9d6f2caf0b8?source=friends_link&sk=718cf5faa69a1d96db05e37063156a5c

**Comment by philgapp** [comment]
Thanks again, and also great article!

Here's part of the exact object I'm working with:

`ti: Array(60)
**0**:
date: "3/26/2020"
sig: undefined
_ti:_
ema12: 515.0655912203054
ema26: 575.240518854499
gap: -11.125
macd: -60.17492763419364
macdsig: -58.64504459007715`

The bold '0' is the x from my previous comments, an automatic key due to the way I push objects into the parent array. Then I am charting the data starting at `ema12` and below, and there are many more items than in this example under the second, lowest-level 'ti' object (italicized). My issue is in Recharts I can't call:

`dataKey=ti.**0**.ti.ema12`

... because the key increments with every `date:`.

Further with a single helper/accessor function like mentioned in this thread or in your article, I still can't get (for example) `dataKey={getValue(ema12)}`, where I could return the 0,1,2,3 etc. key and pass a parameter for the correct 0.ti.ema12 or (for another line on the chart) 0.ti.ema26. So far I'm stuck with a couple dozen accessor functions, one for every lowest-level data I want to plot.

Now for the noob question, is it just because I can't pass a parameter to a function created as 'const'? When I tried to create a normal function that could accept the parameter(s), I couldn't get the dataKey in Recharts to call it. I'm sorry too, I didn't document the error and would have to try that again to provide more detail.

Thanks for your brainpower!

**Comment by philgapp** [comment]
That was horrificly formatted sorry:
ti:
   0: (automatic key)
      date: (used as x axis)
      sig:
      ti:
         ema12: (and same level/location for all data I am plotting on y axis)

**Comment by gaurav5430** [comment]
so, if `ti` is `Array(60)` , are you going to plot 60 different Lines in the LineChart, where each element of array represents a Line?

Or does this 60 represent the data points? which means you would have 60 different dates on the x axis and the number of Lines would be decided by the multiple y values inside `_ti` ?

I am assuming it is the latter.

So your data is like:

```
[
  {
    "date" : "somedate",
    "_ti": {
      "y1" : "y value1 for Line 1",
      "y2" : "y value1 for Line 2",
      "y3" : "y value1 for Line 3"
    }
  },
  {
    "date" : "somedate",
    "_ti": {
      "y1" : "y value2 for Line 1",
      "y2" : "y value2 for Line 2",
      "y3" : "y value2 for Line 3"
    }
  },
  {
    "date" : "somedate",
    "_ti": {
      "y1" : "y value3 for Line 1",
      "y2" : "y value3 for Line 2",
      "y3" : "y value3 for Line 3"
    }
  }
]
```

which would lead to 3 Lines in the LineChart based on y1, y2, y3 , and the xAxis would be decided by the date value ?

If this is the case, you can bind your data like below:

```
<LineChart width={730} height={250} data={ti}>
  <XAxis dataKey="date" />
  <YAxis />
  <Line type="monotone" dataKey="_ti.y1" stroke="#8884d8" />
  <Line type="monotone" dataKey="_ti.y2" stroke="#8884d8" />
  <Line type="monotone" dataKey="_ti.y3" stroke="#8884d8" />
</LineChart>
```

You don't really need to do anything with the array keys, because the data that you bind to `LineChart` is expected to be an array, and the accessors or `dataKey` is for the object inside each array index. 

If my understanding of your data structure is incorrect, it would be helpful if you can create a non working jsfiddle/codesandbox with your data structure.

**Comment by TomlDev** [comment]
I want to add to this, that it can also be used for creating dataKeys based on the array index of a dataValue.
I have the following data, one object per day in a month:
```
[
            {
              'average-2022': 0.006333333333333968,
              'average-2023': 0.03999999999999915
            },
            {
              'average-2022': 0.01233333333333301,
              'average-2023': 0.014333333333334863
            },
[...]
            {
              'average-2022': 0.00333333333333267,
              'average-2023': 0.008333333333331677
            }
]
```
We see that we cannot pass a `dataKey` value to the chart component that will give us the number of days (1 to 31).

Fixed by the following code:
```
        <ComposedChart
          data={ history }
        >
          <YAxis />
          <XAxis
            dataKey={ value => history.indexOf(value) + 1 }     // <== Here we set the array's index as axis value
          />
          <Bar
            dataKey={ `average-${selectedYear}` }
          />
          <Line
            dataKey={ `average-${selectedYear - 1}` }
          />
        </ComposedChart>
```
To get the number of the day as X axis tick values:
![grafik](https://github.com/recharts/recharts/assets/48552168/3cde5209-2dfe-4785-9399-279969f9b236)
