### ISSUE TITLE
Error when passing new data to LineChart

### ISSUE THREAD

**Issue by VanDavv** [recharts/recharts#387]
When I try to update data for LineChart, i get the following errors
![image](https://cloud.githubusercontent.com/assets/5244214/20860445/c0a4ab34-b978-11e6-8a2a-f868d281d579.png)

**When the error occurs**
Full data for the chart was loaded, and the chart with two lines has rendered. Then user changes desired variables and when new data for the chart is passed (via props, the component is rerendering) the following error occurs. New data is generated correctly, but when they're passed to chart, the following errors occurs

**Example**
I don't use plain React to manipulate data, so it would take me some time to prepare a live example of this error. If it will be necessary i'll write one though

**Comment by xile611** [comment]
@VanDavv How about the version of recharts ? Live example or a simple project is required to reproduce your problem.

**Comment by ShortandSweet** [comment]
Similar here: 
```
CSSPropertyOperations.js:190 Uncaught TypeError: Cannot assign to read only property 'length' of object '#<CSSStyleDeclaration>'
setValueForStyles @ CSSPropertyOperations.js:190

warning.js:36 Warning: performUpdateIfNecessary: Unexpected batch number (current 2112, pending 2108)
...
```

Here's what is rendered:
```
  render() {
    return (
      <div>
      <LineChart width={300} height={200} data={this.state.data} margin={{top: 10, right: 10, left: 10, bottom: 10}}>
       <XAxis  dataKey="x" type="number" />
       <YAxis  interval={1} hide />
       <CartesianGrid strokeDasharray="0.25 5"/>
       <Legend /> 
        <Line name="Frequency2" type="number"  type="monotone" dataKey="y_freq_repeat" stroke="#82ca9d" strokeWidth={2}  
                  connectNulls={false}  strokeDasharray="1 1"/>
      </LineChart>     
      </div>

    );
  }
```
The dashed line (strokeDasharray) is drawn correctly 1 time on 2 when the data is modified (setState...). Otherwise, a full line replace it.
 
**To solve the issue for now:**
I avoid using strokeDasharray in <Line...> parameters or I add isAnimationActive={false} to it.

I'm a beginner at web development. But I believe the issue has something to do with the mix of strokeDasharray and animation. Perhaps the use of strokeDasharray isn't documented for Recharts :    [http://recharts.org/api#Line](http://recharts.org/api#Line). So am I using some unsupported parameters?

**Comment by VanDavv** [comment]
@ShortandSweet Yes, this was the cause of my error. Rerencering a linechart with StrokeDasharray causes chart to crash. Removing it solved this issue

**Comment by ShortandSweet** [comment]
Live example : 
[http://jsfiddle.net/x1yoboc7/249/](http://jsfiddle.net/x1yoboc7/249/)

When New data is press, the dashed line is redraw as a full line.

**Comment by charltongroves** [comment]
Still experiencing this bug. Initial renders of lines with stroke-Dasharray are fine, but on a setState rerender, they cause my chrome tab to completely freeze (no script error comes up).

Issue is fixed by passing `isAnimationActive={false}` to the line, or removing `stroke-Dasharray`.

Tested it on firefox and same thing happens, firefox reports that "A web page is slowing down your browser, what do you want to do, wait or stop it"

Just to reiterate, it's not a script error, and is happening during the webpage rendering (painting?) phase.
