### ISSUE TITLE
Dotted and solid line in line charts

### ISSUE THREAD

**Issue by aryanbhatt-0501** [recharts/recharts#3936]
The issue which is not created via https://recharts.github.io/recharts-issue-helper will be closed immediately.

---

How can I achieve both a dotted line and a solid line in a linechart. Up to a certain point I want the normal solid line, but after a point I want it to be dotted.

For reference: https://codesandbox.io/s/tiny-line-chart-r5z0f
How to make the line dotted after "Page D" in this?

注意：不是用 https://recharts.github.io/recharts-issue-helper 创建的 issue 会被立即关闭。

**Comment by ckifer** [comment]
Hi, I don't think this is currently possible. Generally, you would create two lines that start and end at the same place.

Since that isn't possible you could use this approach https://stackoverflow.com/a/67686926/8050147
https://codesandbox.io/s/tiny-line-chart-forked-k4zfwk?file=/src/App.tsx
But that approach has its limits as seen in the SOF comments there

**Comment by aryanbhatt-0501** [comment]
Thank you!
