### ISSUE TITLE
Missing index property in LabelProps

### ISSUE THREAD

**Issue by sKopheK** [recharts/recharts#3938]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/skophek/pen/poGRWVy](https://codepen.io/skophek/pen/poGRWVy)

### Steps to reproduce
check for `// INDEX available` comment

### What is expected?
TS does not complain about non-existing `index` property

### What is actually happening?
TS complains about non-existing `index` property

| Environment | Info |
|---|---|
| Recharts | v2.9.2 |
| React | 17.0.2 |
| System | Win11 up to date |
| Browser | don't use |

**Comment by ckifer** [comment]
Hi @sKopheK 

Do you mind moving your reproduction to codesandbox?
https://codesandbox.io/s/simple-bar-chart-forked-xvdz32

Its a lot easier to look at typescript errors there. Thank you

**Comment by ckifer** [comment]
Repro https://codesandbox.io/s/simple-bar-chart-forked-k297vg?file=/src/App.tsx

Looks what recharts actually renders under the hood is a `LabelList`
Which provides an `index` to `Label` [here](https://github.com/recharts/recharts/blob/master/src/component/LabelList.tsx#L61).

The `index` doesn't throw an error because of the unnecessary `as any` cast in `filterProps`

**Comment by ckifer** [comment]
PR up to fix

**Comment by sKopheK** [comment]
> Hi @sKopheK
> 
> Do you mind moving your reproduction to codesandbox? https://codesandbox.io/s/simple-bar-chart-forked-xvdz32
> 
> Its a lot easier to look at typescript errors there. Thank you

hi, sry, i'm in CET timezone, just woke up :) thanks for taking care of the issue

**Comment by nikolasrieble** [comment]
Released with https://github.com/recharts/recharts/releases/tag/v2.10
