### ISSUE TITLE
Trying to figure out proper typing for a custom Shape function being provided to a Bar chart.

### ISSUE THREAD

**Issue by roger-tbg** [recharts/recharts#4222]
I have this function:
```
const MultiPillBar = (props: BarProps) => {
	const { fill, x, y, width, height } = props

	const pillWidth = 25
	const pillHeight = 7
	const numberPillsAtAbout10pxPerPill = Math.floor(height! / 10)
	const bottomOfGraph = (y as number) + height! - 10

	const pills = Array.from(
		{ length: numberPillsAtAbout10pxPerPill },
		(_, i) => (
			<rect
				key={i}
				x={(x as number) + width! / 2 - pillWidth / 2}
				y={bottomOfGraph - i * 10}
				width={pillWidth}
				height={pillHeight}
				rx={5}
				ry={5}
				fill={fill}
			/>
		),
	)
	return pills
}
```

And i'm trying to figure out where the typing is wrong when used like this:

```
<Bar dataKey="count" fill={'#6832f5'} shape={MultiPillBar}></Bar>
```
![CleanShot 2024-02-22 at 13 56 16](https://github.com/recharts/recharts/assets/141795220/e59342f2-fc63-48ac-a5a4-25a93e753fc7)

**Comment by roger-tbg** [comment]
Also just noted (though it didn't fix it) I have:
```shape={MultiPillBar}```

but the example code for the TriangleBar (from the samples) has:
```shape={<TriangleBar/>}```

but changing my code to:
```shape={<MultiPillBar/>}```

results in a different error:
![CleanShot 2024-02-22 at 14 18 44](https://github.com/recharts/recharts/assets/141795220/0a931acd-9af6-4686-b784-af5ebf1fbd3d)

**Comment by ckifer** [comment]
^ the different error is because you are not passing properties to the component when you do it that way which BarProps expect. In order to properly do that you need to do `shape={(props) => <MultiPillBar {...props} />}`.

---

[![Edit bar-chart-with-customized-shape (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/bar-chart-with-customized-shape-forked-myhkq3?file=%2Fsrc%2FApp.tsx%3A109%2C1)

So this works, but the return type is wrong in the recharts code (apologies for that, legacy code).

**Comment by ckifer** [comment]
Since you're returning an array, it yells about the type.

You can do something like 
`<>{arrayResultHere}</>`  and it should accept it

**Comment by roger-tbg** [comment]
Do you recommend:
```shape={MultiPillBar}``` or
```shape={(props: BarProps) => <MultiPillBar {...props} />}```

just in general?

**Comment by ckifer** [comment]
If you are treating `MultiPillBar` like a React component, then `shape={(props: BarProps) => <MultiPillBar {...props} />}` because then you can add your own props.

If you are treating it like a function and that function only accepts `BarProps` (or whatever `shape` provides) then `shape={MultiPillBar}`. But its 100% preference

**Comment by ckifer** [comment]
the `shape` prop is for a single bar too generally. I'm not sure this would render as you expect it to (though it might already regardless of typescript)

**Comment by roger-tbg** [comment]
Thank you so much for all your help!  Really enjoying Recharts :)
