### ISSUE TITLE
Server-side rendering not working with Next.js

### ISSUE THREAD

**Issue by Titou325** [recharts/recharts#4336]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/Titou325/dev-recharts-next](https://github.com/Titou325/dev-recharts-next)

### Steps to reproduce
Clone the repository at https://github.com/Titou325/dev-recharts-next

Start the dev server by using `npm run dev`

Navigate to http://localhost:3000/

### What is expected?
The chart should be generated server-side and sent to the client.

### What is actually happening?
We get an error

```
node_modules/recharts/es6/component/TooltipBoundingBox.js (12:106) @ _inherits
 ⨯ TypeError: Super expression must either be null or a function
    at _inherits (webpack-internal:///(rsc)/./node_modules/recharts/es6/component/TooltipBoundingBox.js:19:113)
```

Based on basic research this seems to be linked with the server-side rendering. Adding the "use client" directive to the top of the Graph.tsx component fixes the issue but we lose server-side rendering.

| Environment | Info |
|---|---|
| Recharts | v2.12.3 |
| React | 18.2.0 |
| System | MacOS |
| Browser | Any |

---
This only seems to happen within a Next.js environment. In the same repo as provided above, you can run the command `npx tsx ./test.ts` that will use ReactDOMServer.renderToString() without a browser environment and the console will show the graph HTML without any error.

**Comment by ckifer** [comment]
Recharts has no explicit support for server side rendering. It's built for the browser environment only at this point in time as we call functions such as `getClientBoundingRect` and others that do not exist on the server. 
"use client"; is the solution. You can separate your components so that only your charts have to render client side

**Comment by Titou325** [comment]
Hi @ckifer, thank you very much for your prompt answer. I am a bit puzzled because charts *do work* in server-side rendering in a Node.JS backend project. However they specifically don't in a Next.JS environment.

It seems that there may be a component that detects a different runtime and triggers different rendering processes. Most notably, on our example that works server-side the generated code doesn't contain anything for tooltips but it seems that inside a Next project the Chart attempts to render tooltips hence causing the error.

Is there a way we could bypass the tooltips altogether? We have tried adding a `<Tooltip content={() => null} viewBox={{x: 0, y:0, width: 0, height: 0}} />` to try and opt-out of tooltips rendering but it doesn't seem to work.

Thanks for the input anyways, much appreciated!

**Comment by ckifer** [comment]
the `es6` path is probably being forced because I think Next uses the `type: module` field in the package.json (not sure about that 100%). This with the combination of some magic they are doing could cause the issue I guess?

I wonder, in that Node backend project if you tried to use `type: module` if you would get the same error or not

**Comment by Titou325** [comment]
Both projects are actually in the same folder, the node entrypoint is at https://github.com/Titou325/dev-recharts-next/blob/main/test.ts, inside the Next app. The Next app also imports the file at https://github.com/Titou325/dev-recharts-next/blob/main/src/app/page.tsx

I will try and see if tsx may do some shenanigans to get things working but it seems strange.

**Comment by ckifer** [comment]
definitely strange.

the component in question in the error is here https://github.com/recharts/recharts/blob/master/src/component/TooltipBoundingBox.tsx#L29. Its still a class component and it doesn't have a constructor or call `super`

If I do call the constructor though, its useless and I shouldn't have to in order to prevent errors
![image](https://github.com/recharts/recharts/assets/25180830/a6563f0d-d46d-4585-ba7a-b3396ffe3bf5)

**Comment by Titou325** [comment]
After a bit of investigating, it seems that the root cause is [lack of support for Class Components for server-side rendering in Next.js](https://nextjs.org/docs/messages/class-component-in-server-component). Although class components are now [legacy](https://react.dev/reference/react/Component), I think this would require a significant rewrite effort for Recharts.

Let's close this for now.

**Comment by ckifer** [comment]
Appreciate the investigation! Why would Next just make Class components break? 😅 Wild.

Anyways, we're doing a lot of refactoring that should enable us to move off of class components entirely - it'll just take a while.

Thanks!

**Comment by amitbeck** [comment]
> Recharts has no explicit support for server side rendering. It's built for the browser environment only at this point in time as we call functions such as `getClientBoundingRect` and others that do not exist on the server. "use client"; is the solution. You can separate your components so that only your charts have to render client side

@ckifer Correct, but could you please consider exporting this library's dist with a `"use client"` directive for convenience?
