### ISSUE TITLE
Tooltip Animation Settings

### ISSUE THREAD

**Issue by billcreative** [recharts/recharts#434]
I've been playing around with Recharts for the past couple of days and am finding the Tooltip animation very inconsistent. This could be due to the animation changing on every mouse move.

Here's a demo where I've extended the animationDuration to exaggerate what happens.
https://jsfiddle.net/Billsy/un16cwkd/3/

If you move from one bar to another slowly (keeping your mouse on the same Y axis) you can see the animation. However, move your mouse and the Tooltip jumps to your mouse position.

isAnimationActive={false} doesn't solve the issue and I also think this could be making the Tooltip appear jerky when the duration is shorter.

**Comment by ZephD** [comment]
Nice example.
This looks like the animation starts from the previous point to the new mouse location each mouse update.
If the mouse has moved a lot, the animation starts to play and the box starts to slide between the old and new locations.
However, _during an animation_, if the mouse moves a tiny amount more, the box snaps to the previous new location, then animates across the tiny distance.

This is my best guess...

**Comment by xile611** [comment]
@billcreative @ZephD Some bug happens in `Tooltip`, so that `sAnimationActive={false}` didn't work before. And I remove `<Animate>` in `Tooltip`, just [update style to animate the tooltip](https://github.com/recharts/recharts/blob/master/src/component/Tooltip.js#L167). 

[demo](https://jsfiddle.net/un16cwkd/4/)
