### ISSUE TITLE
Changing domain does not work properly with stacked area graph

### ISSUE THREAD

**Issue by peterhadlaw** [recharts/recharts#441]
If you're data contains stacked area graphs, with let's say one of the stacks at some point reaching 0, you can't set your domain to be, for example [50, 100]. It will still show the YAxis domain as [0,100]. If you remove the part of the stacks that has the data with points < 50, then the domain will be properly updated.

**Comment by xile611** [comment]
@peterhadlaw Can you create a jsfiddle demo ?

**Comment by loris** [comment]
Same issue here, here is a [jsfiddle demo](http://jsfiddle.net/ze8c333g/20/)
I just modified the documented [StackedAreaChart demo](http://recharts.org/#/en-US/examples/StackedAreaChart) to set `type="number" domain={[2000, 15000]}` on the `YAxis`. As you can see, the axis starts at 0 instead of 2000. It does not work with `auto` or `dataMin` neither. By the way, same issue with `BarChart` too.

**Comment by peterhadlaw** [comment]
@xile611 The result is essentially the same as the fiddle shared by @loris . @loris thank you for sharing.

**Comment by xile611** [comment]
@loris @peterhadlaw Add props `allowDataOverflow` in `YAxis`, and update to version 0.20.3.

[api](http://recharts.org/#/en-US/api/YAxis)
[demo](http://jsfiddle.net/ze8c333g/21/)
