### ISSUE TITLE
Tooltip not working on Area chart - mobile touch events

### ISSUE THREAD

**Issue by GregPhyn** [recharts/recharts#444]
Hi Guys,

I'm having problems getting recharts tooltip to work with mobile touch events for area charts.
I see that it has been fixed for lineCharts per https://github.com/recharts/recharts/issues/204

Any help with area charts?

Thanks!

**Comment by xile611** [comment]
The events of AreaChart and LinChart are implemented in the [generateCategoricalChart](https://github.com/recharts/recharts/blob/master/src/chart/generateCategoricalChart.js#L997).

**Comment by GregPhyn** [comment]
@xile611 I'm confused on how I'd implement that.
Do I need to simply 
Import "generateCategoricalChart" from "recharts" ?

**Comment by xile611** [comment]
@GregPhyn I mean, If touch events can work in LineChart, then touch events must work in AreaChart too, because both `LineChart` and `AreaChart` are generated by a high order component. As you can see in the [code of generateCategoricalChart](https://github.com/recharts/recharts/blob/master/src/chart/generateCategoricalChart.js#L997), we have bound `touchmove` event in the charts.

**Comment by GregPhyn** [comment]
@xile611 so what happens is touchEvents work once; i.e. touch on tooltip -> shows tooltip -> can't touch on any other tooltips... is this a known issue?

**Comment by yelynn2015** [comment]
I don't know why the touch event can work in Android, but not ios.

**Comment by Viral-Inc** [comment]
+1 ?

**Comment by yelynn2015** [comment]
Add the onClick in the Chart, then it can work!

**Comment by rockallite** [comment]
Even adding `onClick={null}` will enable mobile touch event in chart. I don't know why!

**Comment by leituo** [comment]
Why adding onClick={null} in the Chart component not work
