### ISSUE TITLE
Brush component is missing property `data`

### ISSUE THREAD

**Issue by forman** [recharts/recharts#4475]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://recharts.org/en-US/api/Brush](https://recharts.org/en-US/api/Brush)

### Steps to reproduce
Just visit https://recharts.org/en-US/api/Brush#data and read about the non-existent `data` property.

### What is expected?
Brush's `data`property should be used or it should not be documented.

### What is actually happening?
Brush's `data` property is not used but is documented.

| Environment | Info |
|---|---|
| Recharts | v2.12.6 |
| React | React-independent |
| System | System-independent |
| Browser | Browser-independent |

---
It took me over an hour to investigate why my Brush (that uses the `data` property as documented) didn't show. I then browsed through recharts code and found that `data` is (no longer?) a property of Brush and only the data passed to the chart is recognised.

**Comment by ckifer** [comment]
Brush needs other chart information in order to render including `data`. 

This was never meant to be an external property and shouldn't have been documented like one, but unfortunately there wasn't a great distinction between the two from the start. 

That being said
`data` is still there https://github.com/recharts/recharts/blob/master/src/cartesian/Brush.tsx#L27 as a prop, so it might be something else causing it not to render for you?

**Comment by ckifer** [comment]
For example https://master--63da8268a0da9970db6992aa.chromatic.com/?path=/story/examples-cartesian-brush-in-surface--in-surface

**Comment by ckifer** [comment]
Going to close this since it doesn't seem to be an issue, please comment back and I'll re-open if needed
