### ISSUE TITLE
The `Area chart` is displaying in the incorrect position.

### ISSUE THREAD

**Issue by sohagmahin** [recharts/recharts#4713]
## What is the current behavior?
 Answer: The area chart is displayed incorrectly. like Y-axis value: 107 but it's showing on position 70. See the screenshots below.
 
<img width="605" alt="Screenshot 2024-07-01 at 2 32 31 PM" src="https://github.com/recharts/recharts/assets/35423413/352b444b-0473-48ef-a414-02afe0e8aa06">

Here is the sample code: https://codesandbox.io/p/sandbox/simple-line-chart-forked-2zjv4t

## What is the expected behavior? 
The chart area should display up to the position indicated by the tooltip marker.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
   recharts: 2.x.x
   Browser: all browser

**Comment by ckifer** [comment]
Hi, this is because of `type="basis"` on your `Area` component

`curveBasis` is a d3 function that produces a cubic spline
https://d3js.org/d3-shape/curve#curveBasis

If you remove that then the data looks correct again.

This makes sense if you look at the definition of a [b-spline](https://en.wikipedia.org/wiki/B-spline) which prioritizes smoothness. Because that point is a peak, its going to render lower than the actual value due to the b-spline formula.

`type="monotone"` might be what you want to get your smooth spline that matches the values on the chart
https://d3js.org/d3-shape/curve#curveMonotoneX

**Comment by ckifer** [comment]
I'm going to close this as a non-issue, feel free to comment back if you have questions

**Comment by sohagmahin** [comment]
Thanks 🙏🏿  @ckifer . It works.
