### ISSUE TITLE
v2.9.3+ tooltip does not render on right half of Line graph

### ISSUE THREAD

**Issue by Forfold** [recharts/recharts#4717]
## Do you want to request a feature or report a bug?
Bug, [reference PR to dep update](https://github.com/target/goalert/pull/3861)

## What is the current behavior?
After upgrading from `v2.9.2`, we noticed that our tooltip does not render on the right half of our Line graph. This happens on an upgrade to `v2.9.3` or any future release. [This PR seems to be the only change?](https://github.com/recharts/recharts/pull/3932) When I hover over the line that does not render a tooltip, my console log in the tooltip's `content` prop _does_ still show.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via codesandbox or similar.

**[Codesandbox Link](https://codesandbox.io/p/sandbox/simple-line-chart-forked-ply72f?file=%2Fsrc%2FApp.tsx)**

Left side of graph, mouseover a line:
![Screenshot 2024-07-02 at 8 58 50 AM](https://github.com/recharts/recharts/assets/11381794/129a3ae9-7b97-478c-95cb-f502f9bf49b6)

Right side of graph, mouseover a line:
![Screenshot 2024-07-02 at 8 58 56 AM](https://github.com/recharts/recharts/assets/11381794/b3a22af1-df22-4e02-9241-d993aab5966e)

## What is the expected behavior?
Tooltip renders as expected

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Chrome, Yes, `v2.9.2`

**Comment by ckifer** [comment]
Remove the `data` prop from the high level chart. Then your Tooltip will render normally.

This shouldn't have been a breaking change though.. still looking into it

**Comment by Forfold** [comment]
Oooh that was simple. Thank you @ckifer! Hoping you can find the breaking change soon.

This was the only change I noticed from an upgrade to 2.9.2 to 2.9.3:

```
const { data = chartData } = child.props;
```

->

```
const data = (child.props.data ?? chartData).slice(state.dataStartIndex, state.dataEndIndex + 1);
```

**Comment by ckifer** [comment]
No problem!

Your `data` array that you pass into the high level chart is not in the form that recharts knows how to react to since it consists of nested series. None of the datakeys that you reference in the chart itself are within that structure. If all of your data a flat array of objects and your series were instead different keys per line
i.e.
```
data = [
  {
    name: 'xAxis1'
    series1: 100
    series2: 300
  }
]
```

Then your data prop on the high level chart would work as expected.

I think this is a side-effect of that expectation - one or the other dataset has to take precedence at some point. We should always prefer the dataset on the child, but in this case there is a conflict for some reason

**Comment by ckifer** [comment]
Actually this makes a lot of sense and is a bug.

Notice that the first 4 datapoints are the ones with the tooltip - this is because your high level array of objects has 4 items. Those `dataStartIndex`/`dataEndIndex` are slicing the data the tooltip gets unexpectedly because it is referencing the length of the top level dataset

@HHongSeungWoo fyi since this was your PR if you'd like to address it feel free

**Comment by Forfold** [comment]
Sounds good! I'm working on flattening the data we pass in anyways to make it more in-line with the expected approach.

I made the data the same as what you recommended, such as
```
{
    "timestamp": "2024-06-23T07:00:00.000Z",
    "Global time-frame Usability Service": 2,
    "Forward Automated Optimization Service": 1,
    "Lead eco-centric Tactics Service": 2,
    "Legacy Synchronised Assurance Service": 2
}
```


Do you know what the new dataKeys should be, if you don't mind? Struggling to get it to render so far. I set the new `dataKey` to the `series.serviceName` and the `XAxis` to `timestamp`. Before it was `dayTotal` and `date`, respectively. However I know these are wrong:

```
<Line
  dataKey={series.serviceName}
  name={series.serviceName}
/>
```

```
<XAxis
 dataKey='timestamp'
```

**Comment by ckifer** [comment]
Fixed in alpha https://www.npmjs.com/package/recharts/v/2.13.0-alpha.5
