### ISSUE TITLE
[React js] Line component doesn't extend the line to the edges of the chart area

### ISSUE THREAD

**Issue by ngohuytrieu** [recharts/recharts#4744]
## Do you want to request a feature or report a bug?
I don't know, if it hasn't been integrated then it is a feature otherwise it is a bug

## What is it?
I have chart data like below, I am drawing a Line Chart using Line component
<img width="1251" alt="image" src="https://github.com/recharts/recharts/assets/54321995/05f6d796-3b33-4d2a-b3ed-b22541ccdb3e">

I want the data line draw a line from data point that has value to other data points that have values, ignoring any data point in between that has no value (like an image)

```javascript
const data = [
  { name: '0', value: null },   // Start point (could be adjusted as needed)
  { name: '1', value: null },
  { name: '2', value: 2 },
  { name: '3', value: null },
  { name: '4', value: 4 },
  { name: '5', value: null },
  { name: '6', value: null },   // End point (could be adjusted as needed)
];
...
<LineChart width={400} height={300} data={data}>
  <XAxis dataKey="name" />
  <YAxis />
  <Line type="monotone" dataKey="value" connectNulls={true} />
</LineChart>
```

## What is the current behavior?
The data line doesn't extend the line to the edges of the chart area from the first and the last defined point

## What is the expected behavior?
I want the data line to extend the line to the edges of the chart area from the first and the last defined point

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts: `^2.12.7` This is the only version that I use
Browser: `chrome:126.0.6478.127`
OS: `macOS`

**Comment by ckifer** [comment]
Hi - I'm confused - you have connectNulls as true which is working correctly. All non-null datapoints are being connected past the nulls that exist. 

The problem with what you want is that there is nothing to connect to on your last data point since the value is null. 

We can't go to 0 else we'd always have to replace null with 0 which isn't what people generally want. 

You could appended a synthetic datapoint to the end of your data with 0 value and that would connect the line

**Comment by ckifer** [comment]
Closing this as stale
