### ISSUE TITLE
Labels hide for horizontal bar chart when we have a lot of options

### ISSUE THREAD

**Issue by MainaMwangiy** [recharts/recharts#4756]
## Do you want to request a feature or report a bug?
I want to report a bug
## What is the current behavior?
If we have a lot of data and options, it only shows some few labels the rest are by default hidden.
## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via codesandbox or similar 
This is the code sandbox - https://codesandbox.io/p/sandbox/combined-barline-chart-nwht2w
## What is the expected behavior?
Can I show the options labels?
## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
^2.1.9

**Comment by ckifer** [comment]
Hello! 

I'm not sure what you mean?

What labels? Are you talking about the XAxis labels, YAxis labels? Some other labels?

**Comment by ckifer** [comment]
If you are talking about the categories, try `interval={0}` on your `YAxis`. Warning that labels will overlap

**Comment by MainaMwangiy** [comment]
Hello. 
Either x-axis or y-labels. It depends with the layout of the chart. 
If you check from this link, the data has the labels being from Page A - Page S. But it only shows the one in the screenshot below. Please check on the https://codesandbox.io/p/sandbox/combined-barline-chart-nwht2w

Is it possible to show all the labels on the axis? 

![image](https://github.com/user-attachments/assets/63c3ac68-6e90-477f-a6d2-27653f2bf31f)

**Comment by MainaMwangiy** [comment]
Yes. Adding `interval={0}` on y-axis labels overlap. So, as this doesn't address my issue, is there a property I can add to have a scroller on the chart? Like if we have 50 items, based on the default height, then we show only about 15 items that don't hide the labels. then the rest of the items to be shown on a scroller. Can this be done?

**Comment by ckifer** [comment]
I'm not sure how that would be possible.

Either we hide certain ticks because they collide or we let them collide. There are different options for interval that do different things but all of them besides interval 0 will try to collision detect and remove certain ticks from rendering. 

If we did that the chart would have to overflow the container because we'd need more height/width so the labels don't overlap. That's a jarring difference from what's currently in place. 

There's a few issues that exist around supporting horizontal scroll but they haven't been priority

**Comment by MainaMwangiy** [comment]
Hello. Is there a documentation to check other options of interval that I can use to check and learn about to this? And are you planning on adding this in the near future?

**Comment by ckifer** [comment]
https://recharts.org/en-US/api/XAxis#interval

> are you planning on adding this in the near future

Depends on what near means - we're working on 3.0 right now which is mostly about stability and maintainability. Larger features such as this will be worked on after that. Since this project is based on volunteer time, we don't have timelines that we can give.

Theres a lot of duplicate issues on this

**Comment by ckifer** [comment]
Going to close this as a duplicate and an answered question

Feel free to track the oldest one of those issues (https://github.com/recharts/recharts/issues/1364). I'll try to clean up the duplicates and track only that one
