### ISSUE TITLE
brush positioning with a single data item

### ISSUE THREAD

**Issue by tryonelove** [recharts/recharts#4844]
## Do you want to request a feature or report a bug?
I was wondering if it's the expected behavior when you pass a single data item to a chart with Brush, the traveller is rendered fully zoomed in.

![image](https://github.com/user-attachments/assets/ed482d47-2247-4c6f-9c14-34c1524f98bd)

## What is the current behavior?

Traveller is rendered with the same start and end position.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via codesandbox or similar (template: https://codesandbox.io/p/sandbox/simple-line-chart-v25dl4).

https://codesandbox.io/p/sandbox/bar-chart-with-brush-forked-qs947f

## What is the expected behavior?

I'd expect the traveller to fill the entire Brush, indicating that it's actually all data that can be shown at the moment.

![image](https://github.com/user-attachments/assets/a925a610-ab58-4a76-b08f-1a11c6b80196)

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts 2.12.7, Chrome, Windows 11. Did not work in previous versions.

**Comment by ckifer** [comment]
Yeah that is currently the expected behavior.

If I have many data items and I reduce it to 1 with the brush then that is how it renders 
<img width="649" alt="image" src="https://github.com/user-attachments/assets/bdfe829d-1770-4a33-bef1-26385b829908">

If I start with one data item that is also how it renders. 1 === 1 so technically it should be at the same start and end position.

Maybe it should have them extended or maybe it should have the area filled in but not show the grab points at all since there is nothing to move. 

But not a bug, and to change something like this would be breaking. If we were to change it we would need some rationale I think -what do other libraries with Brush components do?

**Comment by ckifer** [comment]
Going to close this as stale
