### ISSUE TITLE
Hover and clickable tooltip

### ISSUE THREAD

**Issue by Vlad-Polyakov-24** [recharts/recharts#4909]
## Do you want to request a feature or report a bug?

request

## What is the current behavior?

Hello! First of all, thank you for the awesome library!

Here's my question: I need dynamic elements on the tooltip, such as a nested tooltip or buttons. Currently, the tooltip has a "trigger" property that allows me to fix the tooltip on click, hover over it, and interact with different components inside.

## What is the expected behavior?

I have implemented the click functionality: hover over a point on the chart - the tooltip appears - click on the same point - the tooltip gets fixed, and you can hover over it and interact with the elements inside the tooltip.

Is it possible to keep the tooltip "active" without clicking on the point on the chart?
The desired flow: hover over a point on the chart - the tooltip appears, and you can immediately hover over it without clicking - interact with the elements on the tooltip.

P.S. Attaching a screenshot of how it looks.
![screen](https://github.com/user-attachments/assets/32e80dc9-fede-433b-b7ab-996e34afa02b)

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
recharts: 2.13.0-alpha.4, Google Chrome, Safari

**Comment by ckifer** [comment]
Thanks!

I don't think this is a good idea because of the following:

* We're aiming to improve accessibility moving forwards. Hover actions in general are bad for accessibility, but especially when there are additional actions to perform within an already hovered element
* How does recharts determine if you would like to close the tooltip or not? I don't think we accurately can (automatically at least). This might make the experience different for different custom tooltip implementations

@julianna-langston if you want to comment on accessibility implications of this at all

What you can (or will/should be able to) do however, is manage active state of the tooltip yourself. 
i.e. control the tooltip with state - storing an index/active state and changing that as you hover a new item. _Unfortunately_ you can change `active` on tooltip right now, but not fully control the active index. Hopefully we'll make that possible in 3.x

**Comment by Vlad-Polyakov-24** [comment]
I understand what you mean and generally agree, but work is work :)

Regarding states: Yes, I did that. By manipulating the `active` prop, I was able to achieve clickable functionality. However, because it's not possible to attach event handlers to the `Tooltip`, I can't correctly track events on the tooltip and therefore can't manage the state properly.

As an alternative, I'll try creating a custom tooltip using `Customized` — as I understand, it will offer more flexibility in configuration.

In any case, thanks for the response!

**Comment by ckifer** [comment]
I hear you :D

You would have to attach event handlers to `Scatter` or `Line` or whatever it might be rather than to Tooltip itself.

FYI Customized will be deprecated in 3.0 and replaced with hooks. https://github.com/recharts/recharts/discussions/4437

**Comment by Vlad-Polyakov-24** [comment]
> FYI Customized will be deprecated in 3.0 and replaced with hooks. https://github.com/recharts/recharts/discussions/4437

I’ll keep that in mind, thanks! And yes, custom components were definitely needed)

> You would have to attach event handlers to Scatter or Line or whatever it might be rather than to Tooltip itself.

Yep, i'm already doing that. I'm updating the my `customHover` state based on `onMouseEnter/onMouseLeave` on the `Scatter`, which controls the `active` prop for the `Tooltip`. This works for the points on the chart, but not for the `Tooltip` itself.

I also tried adding event handlers to the `ScatterChart` to track `event.target` and find the `Tooltip` using a `ref`, but that didn't work since you can't attach a `ref` to the `Tooltip`. + the event I get from `ScatterChart` has the type `CategoricalChartFunc`, which doesn't allow me to access the `target`.

**Comment by Vlad-Polyakov-24** [comment]
I managed to achieve the desired functionality using event handlers on a `custom tooltip component`, so I'm closing the issue. Thanks for your help!
