### ISSUE TITLE
XAxis Ticker showing wrong dates in BarChart

### ISSUE THREAD

**Issue by estevan-r** [recharts/recharts#5000]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
_Note: I'm using Recharts via Shadcn's Chart components._

The dates I've provided in the chart data range from Sep 1 to Sep 7 but are being displayed in a range from Aug 31 to Sep 6. The start and end dates seem to be primarily affected. I'm using the same code provided by Shadcn but with my own data. 

The dates are formatted to dates and then local date strings in the XAxis tickFormatter prop, which works fine. I've spent some time in the docs and tried troubleshooting but I can't figure out what is causing this.

This bug also persists on Shadcn's site when viewing the 'Bar Chart - Interactive' component. The dates don't match the date range provided in their example data either.
[https://ui.shadcn.com/docs/components/chart](url)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
[https://stackblitz.com/edit/rechart-data-bug?file=src%2Fcomponents%2Fmy-barchart.tsx](url)

## What is the expected behavior?
I expect the same date range in my data to be displayed in the preview. I hope there's a solution for this.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts v2.12.7 and alpha 
Chrome version 127.0.6533.122

**Comment by ckifer** [comment]
This isn't a recharts or a shadcn issue, but rather a timezone issue.

The `Date` constructor is going to take in your date string as if it was UTC. `toLocalDateString` (or any other method) will then take that date as UTC and convert it to the browsers local timezone. Sept 1 at 00:00:00 UTC is still August 31st in some parts of the world (the US) which is why it shows your date as Aug 31.

You can prove this by changing `toLocalDateString` to `toUTCString` in your formatters

**Comment by ckifer** [comment]
I'm going to close this since it isn't a recharts issue, happy to discuss here if you have any questions/issues

**Comment by estevan-r** [comment]
Ah, I see. I totally overlooked that. Thanks for the quick reply!
