### ISSUE TITLE
Sankey Chart labels are cut off

### ISSUE THREAD

**Issue by kevinmachstudio** [recharts/recharts#5155]
## Do you want to request a feature or report a bug?

Report a bug

## What is the current behavior?

The labels at the right side are cut off. Not sure if it's a width related issue inside the Sankey component. I used this tutorial from https://recharts.org/en-US/api/SankeyChart and tried to make a custom node component that would be like the one in the example since it wasn't provided.

<img width="1132" alt="image" src="https://github.com/user-attachments/assets/fabc5bf7-a2e0-4bd0-9f28-c6354391da3e">

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via codesandbox or similar (template: https://codesandbox.io/p/sandbox/simple-line-chart-v25dl4).

Here's the sandbox: https://codesandbox.io/p/sandbox/simple-line-chart-forked-mshkdh

## What is the expected behavior?

Labels should not be cut off

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

 "recharts": "^2.13.0". Tested in Safari and Chrome. Doesn't seem to be working in previous versions

**Comment by ckifer** [comment]
It looks like you just need some more right margin to make room in the svg

**Comment by ckifer** [comment]
https://codesandbox.io/p/sandbox/sankey-chart-bug-labels-cut-off-forked-3q4mfl?workspaceId=d53913d8-85a8-463b-9dc1-f7770946ba51

margin needs manually adjusted at this point in time. There might be potential improvements in the future where we can automatically account for label width but that would be a feature request rather than a bug. Going to close this for now
