### ISSUE TITLE
Responsive PieChart label cut

### ISSUE THREAD

**Issue by wkwiatek** [recharts/recharts#517]
Chart is being responsively changed according to the size but label (if they're to long) seems not to be considered in the measurements which means they're cut in some circumstances. 

JSFiddle with repro: http://jsfiddle.net/6rtyqjf8/

**Comment by xile611** [comment]
@wkwiatek It's recommended to render labels inside the sectors.

**Comment by softwaremeisterei** [comment]
how do you render Labels inside?

**Comment by yaroslav-perec** [comment]
I had the same problem, and I solved it, I added prop `minWidth` to `ResponsiveContainer` and added `overflow: auto` to my `div` inside which is located `ResponsiveContainer`

**Comment by fgiarritiello** [comment]
@yaroslav-perec Could you show us your ResponsiveContainer class pls?

**Comment by yaroslav-perec** [comment]
@fgiarritiello sure,

```
<div className="content">    
	<ResponsiveContainer minWidth={500}>
  		<PieChart>
   			<Pie data={data01} cx="50%" cy="50%" outerRadius={50} fill="#8884d8" />
   			<Pie data={data02} cx="50%" cy="50%" innerRadius={60} outerRadius={80} 
                                fill="#82ca9d" label />
  		</PieChart>
  </ResponsiveContainer>
</div>

```
CSS:

```
.content {
  overflow: auto;
}
```

**Comment by temoke-levelops** [comment]
> how do you render Labels inside?

Old comment. I know. But this needs clarification. By "render the labels inside sectors", they DO NOT mean something like this. 

```
<Sector>
   <Label>My label!</Label> // Label goes inside Sector component!
</Sector> 
```

They just mean don't draw anything outside of the pie. So, if you have this cool idea to have labels on the outside of your pie chart, that's too bad, because you're not allowed, because you'll face this overflow issue. 

One thing you can try, I suppose, is to draw a secret invisible donut around everything. That way your labels will tEcHnICaLLy be inside the pie chart. I'm gonna try that now. Wish me luck.
