### ISSUE TITLE
Show arrow icon tooltip with Piechart.

### ISSUE THREAD

**Issue by ajay-studio137** [recharts/recharts#5204]
## Do you want to request a feature or report a bug?
Feature

## What is the current behavior?
No arrow icon in Tooltip for Piechart.

## What is the expected behavior?
Show arrow icon in tooltip.

I want to show the tooltip with the arrow icon for pie chart. Let me know if we have any solution for this functionality. 

As of now, I am showing a custom Tooltip but showing a fixed arrow icon with custom tooltip makes it look bad. I would like to customize the position of Tooltip so that it shows at the mouse position. 

Thank You for Reading this.
Good Luck.

**Comment by ckifer** [comment]
What do you mean my arrow icon? Can you give an example?

**Comment by ckifer** [comment]
This is currently possible https://codesandbox.io/p/sandbox/pie-chart-with-customized-label-forked-svxp66

You can make a custom tooltip and add CSS to it in order to each the desired outcome
<img width="186" alt="image" src="https://github.com/user-attachments/assets/d80f0d55-eed3-45d4-88f7-11cbe625e4b4">

I made this one controlled so that you can adjust where it renders too

**Comment by ajay-studio137** [comment]
Hi Coltin,

Thank you for solution. I was thinking of moving to another library but looks like I don't. Opens up a lot of possibility.

I want to add this as one of the official example of Tooltip for Piechart.

Thank You.

**Comment by ckifer** [comment]
If you'd like to make a PR to add the example as documentation feel free to! Thanks!

**Comment by ckifer** [comment]
Going to close this one for now
