### ISSUE TITLE
onDoubleClick and onContextMenu for AreaChart

### ISSUE THREAD

**Issue by abarreau** [recharts/recharts#5254]
Hello,

I would like to know if it's possible to have in the v2 version bindings for `onContextMenu` and `onDoubleClick` props on `AreaChart` (right now, only `onMouseDown`, `onMouseUp`, `onMouseMove`, `onMouseEnter` and `onMouseLeave` are implemented)?

My use case is that I want to be able to do separate actions on click, double click and right click. I know the `Area` component already have these props, but it doesn't suit my use case as I want to be able to click outside of drawn areas to perform said actions.

Is there maybe a workaround?

If a new feature is possible on the v2 release, I'm willing to open a PR if someone can roughly guide me through the process of implemeting this.

Thanks for your feedback!

**Comment by ckifer** [comment]
Adding new click handlers can vary wildly in terms of effort and testing needed. 

A few questions:

* do you need to access data from recharts in the click handler or is the normal browser event ok?
* where exactly are you trying to click? Anywhere on the chart or exclusively on the dots/lines/shaded area?

**Comment by abarreau** [comment]
> * do you need to access data from recharts in the click handler or is the normal browser event ok?

I need to access data from recharts yes. Specifically I need to know where my click position is related to both x and y axis scales.

My use case is that I'm trying to add a `ReferenceLine` at the specified mouse event position on right click or double click.

> * where exactly are you trying to click? Anywhere on the chart or exclusively on the dots/lines/shaded area?

![rechart](https://github.com/user-attachments/assets/335cac43-0a4c-4c0e-8da6-1612ba20f10a)

Anywhere in the red area.

**Comment by ckifer** [comment]
Ok so that is on the top level chart. 

If you just needed the click events, that's a bit easier (just let them be passed through correctly as props). Since you need more than that. It will take a bit more + testing, etc. on mobile right now but I will link in the master branch where you would add this. 

Personally, I don't want to implement this until maybe 3.1. But if we did it here we would have to include it in 3.0 as well and there is going to be difference in how events are handled there. 


All for this change, but getting through won't be a priority (for me) for a bit longer. Appreciate the willingness to put up a PR yourself 🙏

**Comment by abarreau** [comment]
I just opened a PR regarding this feature request: https://github.com/recharts/recharts/pull/5255

Any feedback is appreciated. Thanks for your help again @ckifer

**Comment by ckifer** [comment]
released in 2.14.0
