### ISSUE TITLE
people: do yourselves a favor and switch to Highcharts

### ISSUE THREAD

**Issue by voltuer** [recharts/recharts#5382]
this project has serious [issues open for over 7 years ](https://github.com/recharts/recharts/issues/490), it's a joke, don't waste your time

**Comment by ckifer** [comment]
Highcharts is an awesome project and I totally encourage its use. 

When a library is built by a team that gets paid to do things and invest time in things, it's going to be better, have features added, get support. 

When a library is maintained by volunteers who have lives outside and jobs outside of library maintenance it's going to be a product of the time and effort available which tends to be little. 

This is the communities charting library, any one is free and encouraged to participate in contribution so that recharts is better. I picked this library up a few years ago after is started to go unmaintained by the original authors, otherwise it would have hundreds more issues than it does today. Be the change you want to see, nothing is free.

**Comment by ckifer** [comment]
Going to close this as irrelevant to this project, appreciate your feedback.
