### ISSUE TITLE
Possible to "flip" the Area/Line charts to show the lowest values on top?

### ISSUE THREAD

**Issue by martin-svk** [recharts/recharts#545]
Hello,

is it possible to achieve something like this? (Note the higher the YAxis value is the lower the line goes).

![screen shot 2017-03-02 at 17 32 23](https://cloud.githubusercontent.com/assets/4971956/23517104/a65c277e-ff6f-11e6-9046-2129b8e1fbda.png)

I tried to play with `YAxis` `domain` and also `AreaCharts` `baseValue` but none of them did the trick. 

Thanks.

**Comment by martin-svk** [comment]
If anyone has this need as well:

I needed to have this working now, so i did a simple trick with inverting my numeric `Y value` in dataset `value * -1` and then used formatters to make it positive again when rendering in `Y axis` and tooltips, but it would be better if this had a native setting, because this just feels very hacky.

**Comment by Eric24** [comment]
Good fix! But I agree, this should be possible by setting an "invert" flag on the axis. I had originally thought that it could be done by setting the domain to [high, low], but that's problematic when you use calculated domains.

**Comment by ryanand26** [comment]
I think it's now possible to invert the axis using the 'reversed' prop.

**Comment by martin-svk** [comment]
@ryanand26 Yes it is!

**Comment by Georgeevergreen0** [comment]
> @ryanand26 Yes it is!

Is not in the docs

**Comment by stevanstajo0** [comment]
> 
> 
> If anyone has this need as well:
> 
> I needed to have this working now, so i did a simple trick with inverting my numeric `Y value` in dataset `value * -1` and then used formatters to make it positive again when rendering in `Y axis` and tooltips, but it would be better if this had a native setting, because this just feels very hacky.

I want similar feature but I have two more conditions.
1. I need to use Area having `dataKey` for Line chart.
2. I need to show several Line charts into one graph.

Among several Line charts, only one is required to inverse `YAxis`, and I tried `reversed` prop for this Line.
All point data has positive values. No negative values. So Area will be drawing under each Line chart.

The problem is the inverted line chart's Area is drawing on top of Line.
And I need to draw it under Line like others.

Because I need to integrate several Line charts into one, I cannot use the trick - changing `Y value` in dataset as `value * -1`.
Is there any way to show Area below the Line in regardless Line's YAxis is reversed or not?

Thanks.

**Comment by griselmatosm** [comment]
@stevanstajo0 Hi, I have a similar feature. Did you find a solution?
Thanks a lot in advance!

**Comment by DawidWraga** [comment]
Hi @stevanstajo0 @griselmatosm I also have a similar feature. Did either of you find a solution?

Thank you in advance as well!

**Comment by ckifer** [comment]
I'm confused on what the issue is here still @DawidWraga do you mind creating a reproduction of your situation and sharing here?

https://codesandbox.io/p/sandbox/simple-area-chart-forked-tqsht7

**Comment by DawidWraga** [comment]
Hi thanks for asking @ckifer 

The code sandbox you shared demonstrates my problem - the filled area is showing above the line instead of below.

I need to visualise race results so we want 1 to be towards the top as this is more intuitive. However, when I use reversed on the Y axis then it leads to the filled area being on top which does not look right.


I've worked around this by using some very hacky solution - the actual values are inverted, the Y axis is hidden, and I'm using custom tooltip to show the  non-inverted values. But this breaks the gradient and means I can't show Y axis.

See demo here [https://trt-site.vercel.app/results/6065/myresults/164045](https://trt-site.vercel.app/results/6065/myresults/164045)

I'd really appreciate any help with this! Thanks in advance.

**Comment by ckifer** [comment]
Try setting `baseValue` on `Area` to your max datapoint. It will treat that as the new `0`

![image](https://github.com/user-attachments/assets/8affb3d2-a815-4b16-a9b3-ed2dc2abce64)

**Comment by DawidWraga** [comment]
Wow @ckifer you are an absolute saviour, this solution works perfectly and I'm super grateful for your help. 

I wish you all of the best brother
