### ISSUE TITLE
<CartesianGrid /> ignores props

### ISSUE THREAD

**Issue by nickbytes** [recharts/recharts#557]
Do you want to request a feature or report a bug? Bug

What is the current behavior?
CartesianGrid ignores `x ,y, width, height, horizontalPoints, verticalPoints` props.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/9y45ut13/).

http://jsfiddle.net/zm89jyrp/

What is the expected behavior?
I would have expected there to be horizontal lines as specified by `let horizontalPoints = [100, 200, 300, 400];` I would have also expected the grid to start at `x={20} y={20}`. Discovered when tried to limit the size of the CartesianGrid.

Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts? Chrome. Haven't used previous versions.

**Comment by jonahkagan** [comment]
I've noted this happens when you use `CartesianGrid` inside `ScatterChart`, since `ScatterChart` computes the `horizontalPoints` and `verticalPoints` props and passes them into `CartesianGrid`. Perhaps these props weren't actually intended for customization, but merely for internal communication between the components? I would vote for them being implemented for customization, since it would be super useful to be able to customize the grid!

**Comment by fangj** [comment]
It also happens when use `CartesianGrid` inside `LineChart`

**Comment by oshalygin** [comment]
+1 on this one, would love to help.

**Comment by mrt123** [comment]
any movement on this ? verticalPoints is published in API therefore CartesianGrid should use it

**Comment by mrt123** [comment]
Meanwhile for those who need either vertical or horizontal lines on a graph ... i propose to use :  
`referenceLines = myAxisTicks.map(t=><ReferenceLine x={t}/>` 
`<LineChart>{referenceLines}</LineChart>`
Where myAxisTicks is array of numbers.
Customise to suit your needs as per documentation : http://recharts.org/en-US/api/ReferenceLine
