### ISSUE TITLE
Cannot create category type scattered plot chart.

### ISSUE THREAD

**Issue by kdipika** [recharts/recharts#562]
Can some one please help me to create a scattered plot chart with a category type axis. 
The code in this fiddle does not seem to plot anything
http://jsfiddle.net/9xjjuwkk/30/

const {ScatterChart, Scatter, XAxis, YAxis, CartesianGrid, Tooltip, Legend} = Recharts;
const data = [{x: 'A', y: 200}, {x: 'B', y: 100}]

const SimpleScatterChart = React.createClass({
	render () {
  	return (
    	<ScatterChart width={400} height={400} margin={{top: 20, right: 20, bottom: 20, left: 20}}>
      	<XAxis dataKey={'x'} type='category' name='stature' unit='cm'/>
      	<YAxis dataKey={'y'} name='weight' unit='kg'/>
      	<Scatter name='A school' data={data} fill='#8884d8'/>
      	<CartesianGrid />
      	<Tooltip cursor={{strokeDasharray: '3 3'}}/>
      </ScatterChart>
    );
  }
})

ReactDOM.render(
  <SimpleScatterChart />,
  document.getElementById('container')
);

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/9y45ut13/).
http://jsfiddle.net/9xjjuwkk/30/

What is the expected behavior?

Expected to display category on x axis

Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

**Comment by Grumlen** [comment]
I've had the exact same problem with trying to use the 3D scatter. I managed to find a workaround for the ticks on the axes by using an array of numbers instead of categories and the tickFormatter prop for <XAxis/>, but the labelFormatter prop for <Tooltip/> doesn't seem to work at all for scatterplots. This means that the tooltip still displays the numbers instead of the categories that I am trying to format it to display.

**Comment by xile611** [comment]
@Grumlen Try the latest version 1.0.0-beta.1
