### ISSUE TITLE
Toggle an element in chart by clicking legend

### ISSUE THREAD

**Issue by ziofat** [recharts/recharts#590]
I don't think set opacity is enough for toggling an element in chart. The tooltip will still show the element number and a dot will appear when mouse over the chart.

reference to #329 

I have to remove the line element when I toggle it and using my own legend component to prevent the legend item disappear from legend.

It will be great to have a show/hidden prop for cartesian components.

**Comment by namezero** [comment]
+1

**Comment by IanVS** [comment]
My solution has been to just blank out (set to `""`) all unwanted data keys when I hover one of the legend items.  This keeps the legend items for the other series, but essentially removes all of their data, thus setting them to zero.

**Comment by tmaiaroto** [comment]
This would definitely be a welcome addition. In the meantime, I've kept track of all series components (```<Bar />```, ```<Line />```, etc.) visibility in state. Then have the legend click handler change that state. It doesn't do true/false but rather sets a string ```hidden``` or ```visible``` and that is then used as a ```className``` prop on each component. Click handler simply calls ```setState()``` and it hides immediately. It does this without the need to create a whole new ```<Legend />``` component because when you click on the legend item it will pass along data for that series. I've tagged my series with ID values that are used in the state object.

ie. ```this.state.componentVisibility[data.payload.classID]``` which is what changes and is what is set for that class name prop.

While it's a fairly straight forward CSS solution (class name change on state change), the downside here being there's no animation. The charts don't re-render or adjust in any way. It looks a little funny with a stacked bar chart, which is something to note when building something like this...

Do you want the stacked bar chart to redraw when one series is hidden? For example, when there's two series in the stacked bar chart and the bottom is hidden, there's this gap beneath the top one. Since it's now effectively a simple regular bar chart, should it re-render and adjust the axis and such?

Most of the time simply toggling visibility is fine, but I think there's some scenarios like this to be aware of.

**Comment by vinicius5581** [comment]
Is anyone working on this?

**Comment by IanVS** [comment]
@vinicius5581 have you tried my approach? It works very well for us.

**Comment by jonthies** [comment]
I used a combination of the approaches by @IanVS and @tmaiaroto.  Works perfectly.

*  Have a visibility state for each component (Line, Area, ...)  by dataKey.
*  If its visibility is hidden, simply add a space to the dataKey value of the component. It will remain in the Legend and the component will disappear. 
*  In the Legend's event handler (I used `onClick`) trimming off the space in event.dataKey (`const dataKey = _.trim(event.dataKey`), then toggle the visibility state.

**Comment by SorcRR** [comment]
@jonthies can show me a fiddle example of your solution? Thanks!

**Comment by RafaPolit** [comment]
I need this as well, with added functionality to actually 'mimic' the mouse over event on a chart with the legend, as described in #784 

It would be great.

**Comment by sarahradial** [comment]
+1

**Comment by juampick** [comment]
+1

**Comment by jooohhn** [comment]
+1

**Comment by codeplay2015** [comment]
+1

**Comment by swiftfoot** [comment]
@SorcRR  Here's an example JSFiddle of @jonthies approach:

http://jsfiddle.net/x7dvL69z/93/

Click on the pv or uv in the legend to select 

One thing I've noted is that the y-axis adjusts to better fit the selected line.  I think I'd like it better if the y-axis kept it's original domain.  Let me know if anybody can figure that part out.

**Comment by SorcRR** [comment]
Thanks!

**Comment by RafaPolit** [comment]
What if I would like to render the tooltip that appears when hovering a bar by hovering the legend?

**Comment by ipluser** [comment]
+1

**Comment by Kaishiyoku** [comment]
+1

**Comment by ashirvadgupta** [comment]
I have implemented it for Line Chart.
Please have a look into the below JS Fiddle
http://jsfiddle.net/ashirvadgupta/5fyfp6jp/

**Comment by lidermanrony** [comment]
+1

**Comment by VanDavv** [comment]
I've found some [custom toggable legend](https://gist.github.com/abhirathore2006/7fa73328be7ff45b785d727fb19fffa6) and adapted it for my purpose. Original one allows you to select one item, whereas my implementation let's you turn on/off specific items. Code can be found here:

https://codesandbox.io/s/k5no4l0n97

**Comment by claudiadaniela** [comment]
> I used a combination of the approaches by @IanVS and @tmaiaroto. Works perfectly.
> 
> * Have a visibility state for each component (Line, Area, ...)  by dataKey.
> * If its visibility is hidden, simply add a space to the dataKey value of the component. It will remain in the Legend and the component will disappear.
> * In the Legend's event handler (I used `onClick`) trimming off the space in event.dataKey (`const dataKey = _.trim(event.dataKey`), then toggle the visibility state.

I adapted the code according to some of your suggestions:
https://codesandbox.io/s/rechartsstackedbarcharts-with-generic-and-toggled-legend-dfqif

**Comment by oneillsp96** [comment]
Another option is to just build the legend yourself outside of Recharts.  Using an object that tracks the show-hide state, like this: const showHideStates = {
showBarA: true,
showBarB: true
},
you can then modify this object on legend click, and wrap each bar in a conditional like this:

{showHideStates.showBarA &&
    <Bar>
}

This will cause a full rerender of the chart, so you'll get the animations when you show-hide

**Comment by vtarelkin** [comment]
hide = {boolean} did all the trick, sad it's not in the docs

**Comment by rachitpsolanki** [comment]
From the code adapted from @claudiadaniela sandbox  I have created my version of the code 
https://codesandbox.io/s/recharts-with-legend-toggle-dqlts

**Comment by freestyle09** [comment]
@rachitpsolanki great work ;) Thanks!

**Comment by YuryBobkov** [comment]
> hide = {boolean} did all the trick, sad it's not in the docs

Work clear, thx!

**Comment by yognsk1** [comment]
Thanks guys, its looks working for bar/line charts but not for pie chart.
Please help me to fix this.

:)
