### ISSUE TITLE
Tooltip support for reference lines

### ISSUE THREAD

**Issue by peternoyes** [recharts/recharts#613]
## Do you want to request a feature or report a bug?

Feature Request

## What is the current behavior?

Today there is no way to have a tooltip show for a reference line. The label for a reference line can only show a small amount of information because it is easily occluded by other data on the chart. I would like to show a longer string when the user user hovers over the reference line.

**Comment by xile611** [comment]
@peternoyes  You can render customized `Tooltip` content like [this demo](http://recharts.org/#/en-US/examples/CustomContentOfTooltip).

**Comment by SalilUCSF** [comment]
@xile611 There is no Tooltip support for ReferenceLine, ReferenceDot, or ReferenceArea components. Your answer to the above question is not helpful - will this be supported in the future or am I misreading the docs?

**Comment by abhatia-lix** [comment]
@SalilUCSF , you are correct, there is no Tooltip support for ReferenceLine, ReferenceDot, or ReferenceArea components

**Comment by SalilUCSF** [comment]
@xile611 @abhatia-lix I have opened an issue for this: #1512

**Comment by Brijeshlakkad** [comment]
do we now have atooltips for ReferenceLine, ReferenceDot, or ReferenceArea components?

**Comment by mahmonirbkh** [comment]
Is there any update related to supporting tootips for ReferenceDot?

**Comment by ckifer** [comment]
Thanks for commenting, it gives me visibility. I re-opened the other issue in this thread because it has more +1s. 

But no I don't think anything has been done related to this. 

I also am not sure it's a valid use-case? Why not just use a straight line if you need a tooltip?

**Comment by tran-simon** [comment]
@ckifer 
> I also am not sure it's a valid use-case? Why not just use a straight line/single scatter/etc if you need a tooltip?

I would like to use a ReferenceArea to mark a section of my line chart and it would be great to be able to have a tooltip on it to explain to the user what the reference area represents

**Comment by ckifer** [comment]
@tran-simon thanks for commenting rather than just giving thumbs downs! 

The other issue https://github.com/recharts/recharts/issues/1512 remains open - from my understanding this would be a decently sized undertaking.

Apologies for saying it isn't a valid use-case, upon reflection of my previous statement it certainly is valid. Using an existing component in a composed chart would be a way of enabling this now, as a workaround, as opposed to waiting for true tooltip support in reference components. The priority of which may vary - if anyone wants to take up the linked task we can get the long term vision moving!

**Comment by joshenx** [comment]
any intentions to progress this?

**Comment by ckifer** [comment]
Intentions sure, but it'll have to be after 3.0
