### ISSUE TITLE
only displays dots not the lines

### ISSUE THREAD

**Issue by sughanpandita** [recharts/recharts#616]
const React =require("react");
const {LineChart, Line, CartesianGrid, YAxis, XAxis, Tooltip,Legend} =require("recharts");
const demo = require('../../../resources/demo-util');

const data = [];
for (var i = 0; i < json.length; i++)
{
    var mtrcs = json[i];

    var mtrName=mtrcs.name;
    var mtrMemory=mtrcs.metrics.memory;
    var mtrCpu=mtrcs.metrics.cpu;
    var mtrTime=mtrcs.metrics.time;

   data.push({

        name:mtrName,
        cpu:mtrCpu,
        memory : mtrMemory,
        time:mtrTime

    });

}
class Rechart extends React.Component{

    render(){

        return(

          <div>
              <LineChart width={1300} height={400} data={data} margin={{top: 5, right: 30, left: 20, bottom: 5}}>
                  <XAxis dataKey="time"/>
                  <YAxis/>
                  <CartesianGrid strokeDasharray="3 3"/>
                  <Tooltip/>
                  <Legend />
                  <Line type="monotone" dataKey="cpu" stroke="#8884d8" activeDot={{r: 8}}/>
                  <Line type="monotone" dataKey="memory" stroke="#82ca9d" />
              </LineChart>
          </div>
      );

    }
}
module.exports=Rechart;

**Comment by xile611** [comment]
@sughanpandita 

You can hide line by css:

```css
.recharts-line .recharts-curve {
  stroke: none;
}
```

or you can done by specifying the stroke of line and dot：

```jsx
  const dotStyle = { stroke: '#8884d8' };

  <Line type="monotone" dataKey="cpu" stroke="none" dot={dotStyle} activeDot={{r: 8}}/>
```

**Comment by tristanreid** [comment]
I also have this problem, with versions v1.0.0-alpha.2 and v0.22.4.

The issue is not that we want only dots, it is that only dots are appearing, even though the stroke property is set.  I was able to resolve this with setting `connectNulls={true}`.  

![image](https://user-images.githubusercontent.com/5175589/28496793-ca736f72-6f28-11e7-9730-bf078cfb511d.png)

It seems that since all lines use the same data source, if the lines don't have entries for every date there is a problem.

![image](https://user-images.githubusercontent.com/5175589/28496830-0e4d17c4-6f2a-11e7-92e4-3d7f1b331887.png)

**Comment by tristanreid** [comment]
Following up on my own comment:  The above was due to a coding error on my part, I was grouping input data by timestamp, and checked for equality without using `dt.getTime()`, so I ended up with multiple points at the same x-axis position in different data elements.  

This seems to have been the reason for the unexpected nulls.  If anyone else has the issue described above, diagnose by setting `connectNulls={true}`, and if this allows your lines to appear, you may have an issue similar to what I've described above.
