### ISSUE TITLE
[Bug] No animation when changing dataKey if data is not recreated

### ISSUE THREAD

**Issue by howardya** [recharts/recharts#846]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
Data provided to the charts will only be animated if it is recreated on every render. 

For instance, this is perfect http://jsfiddle.net/qbmg1567/581/ 

However, if the data is constant and not recreated on every render, then the animation will not work. For instance, http://jsfiddle.net/qbmg1567/582/ this one will not animate the changes when we press the button. 

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/qbmg1567/).
http://jsfiddle.net/qbmg1567/581/ 
http://jsfiddle.net/qbmg1567/582/

## What is the expected behavior?
Expect both http://jsfiddle.net/qbmg1567/581/ and http://jsfiddle.net/qbmg1567/582/ to have animation

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
NA

**Comment by 951759534** [comment]
I also met the same problem

**Comment by Rahulkr204** [comment]
@howardya did you find any solution ?

**Comment by tomtobac** [comment]
Facing the same issue too

**Comment by brakon** [comment]
What I found is the animation is not triggered if your component rerenders several times in a row. This can happen if the render method is being called even if the data you are passing doesnt change.

To fix this, I added a shouldComponentUpdate to the component contaning the chart, and had it only render when the data did indeed change.

**Comment by acontreras89** [comment]
I'm not sure why this is closed, I'm still facing this issue as of today.

**Comment by AnthonyCrowcroft** [comment]
also still experiencing this as well. Were there any good work arounds.

**Comment by arabold** [comment]
For everybody coming here: I found a workaround for this issue. The hint is actually in the title of this bug report: Simply recreate the data when the `dataKey` changes. For example, if `data` is your chart data, use something like this:

```ts
  const chartData = useMemo(() => data.slice(), [dataKey, data])
  return (
    <BarChart data={chartData}> ... </BarChart>
  )
```

Performance should be acceptable for most scenarios but it would be great if this could be fixed in the library itself instead of requiring the above workaround.

**Comment by muba00** [comment]
I had the same problem, I solved it by adding **<BarChart key={Math.random()} .....**

**Comment by max-crcl** [comment]
> I had the same problem, I solved it by adding **<BarChart key={Math.random()} .....**

That solved it for me, too - thx!

**Comment by raptomonu** [comment]
> I had the same problem, I solved it by adding **<BarChart key={Math.random()} .....**

Thanks Buddy

**Comment by NodeJoSe** [comment]
> ```ts
> const chartData = useMemo(() => data.slice(), [dataKey, data])
> ```

This is the correct answer, I had to `memoize` the `chartData` to avoid re-renders. 

Also, avoid using `Math.random()` as this will cause the chart to flicker when there are multiple `re-renders`

**Comment by NodeJoSe** [comment]
> Reference

This is the correct answer, I had to `memoize` the `chartData` to avoid re-renders. 

Also, avoid using `Math.random()` as this will cause the chart to flicker when there are multiple `re-renders`

**Comment by NodeJoSe** [comment]
> > For everybody coming here: I found a workaround for this issue. The hint is actually in the title of this bug report: Simply recreate the data when the `dataKey` changes. For example, if `data` is your chart data, use something like this:
> > ```ts
> >   const chartData = useMemo(() => data.slice(), [dataKey, data])
> >   return (
> >     <BarChart data={chartData}> ... </BarChart>
> >   )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Performance should be acceptable for most scenarios but it would be great if this could be fixed in the library itself instead of requiring the above workaround.
> 
> Thank you for your help. I resolve the bug

This is the correct answer, I had to `memoize` the `chartData` to avoid re-renders. 

Also, avoid using `Math.random()` as this will cause the chart to flicker when there are multiple `re-renders`

**Comment by charpeni** [comment]
I stumbled across the same issue, thank you for tracking it here!

I wanted to give some clarifications regarding the solutions proposed in this thread, but there's also a potential solution with its own pull request later on.

Regarding the first proposed solution of spreading the array of data within another array:

```tsx
<ComposedChart data={[...myCustomData]} >
```

It's just a way to force the reference to change while keeping the same data, by doing that, we'll force the transition between our two states even though we changed `dataKey`. Unfortunately, it also means that we're creating new data on every single render! It seems bad and it is bad, it could lead to unexpected behaviors if multiple re-renders happen.

@arabold later on proposed to combine this solution but memoized it based on `dataKey`. IMO, I believe this is the only acceptable solution here that doesn't involve changing Recharts. It forces the `data` to change if `dataKey` changes but retains the same reference through re-renders if it doesn't. Still not perfect because it's not explicit how `dataKey` could affect our `data`, especially since comparing both values will end up identical.

Regarding the other proposal to use `key={Math.random()}`, please don't do that!

Doing so will nuke React internals as the key prop will effectively get something different on every render, and therefore, the component will always be re-render. It's even worse than creating a new `data` reference because it fires the whole component lifecycle. We didn't achieve an animation between two states with this proposal, we achieved an animation like it's the first time we rendered the chart:

https://github.com/recharts/recharts/assets/7189823/fd7b7ef4-c971-41d5-930f-ae9e90e8639f

If that's the animation you want, you can still pass the `dataKey` as the value of `key` prop, meaning that we'll force the chart to fully re-render when `dataKey` changes. But it won't nicely animate between two states within the chart!



___

Good news, I dug into the code and found the reason why this is happening and opened a pull request with a proposal: https://github.com/recharts/recharts/pull/3870.

The reason why this is happening is behind the [`getDerivedStateFromProps`](https://react.dev/reference/react/Component#static-getderivedstatefromprops) lifecycle function:

https://github.com/recharts/recharts/blob/9b6046b141be493f64291909fe8439c5fae715de/src/chart/generateCategoricalChart.tsx#L1207-L1214

It means that the animation between two states will only happen if at least one of the listed props here changes: `data`, `width`, `height`, `layout`, `stackOffset`, `margin`, and `children`. One way to assert this is that changing `stackOffset`, which uses a primitive type, simultaneously changing the `dataKey` used on the chart's elements will trigger the animation between the two states as expected. Unfortunately, that behavior isn't explicit at all.

I proposed introducing a `dataKey` prop on the chart component itself to explicitly use the same mechanism as inner elements to determine whether we animate the transition between the two states. The same prop will be used and tracked by `getDerivedStateFromProps` in addition to `data`. There is no need to manually change the reference of `data` in order to trick Recharts into believing the data changed, we will be able to track it explicitly via `dataKey`. 

Here's how it changed the experience within our application:

#### Default behavior where it just happens

https://github.com/recharts/recharts/assets/7189823/ce205f7d-5a4e-4cc9-a69e-818797e20e72

#### Using `key` prop

https://github.com/recharts/recharts/assets/7189823/fb8c58eb-9ba0-4c33-8009-dabe4a12819c

#### Using `dataKey` prop (as proposed in https://github.com/recharts/recharts/pull/3870)

https://github.com/recharts/recharts/assets/7189823/b00c547c-6313-4259-ab63-c196020e4ab3

**Comment by nikolasrieble** [comment]
Released with https://github.com/recharts/recharts/releases/tag/v2.10, thank you @charpeni

**Comment by BjornGjorv** [comment]
> Released with https://github.com/recharts/recharts/releases/tag/v2.10, thank you @charpeni

Thanks for the notification! Will try i out at work tomorrow 👍
