### ISSUE TITLE
Reference Area does not cover entire area specified

### ISSUE THREAD

**Issue by aarohmankad** [recharts/recharts#847]
## Do you want to request a feature or report a bug?

Report a Bug

## What is the current behavior?

Even though I am specifying the boundaries of the Reference Area, there are parts of the graph left uncolored.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/qbmg1567/).

http://jsfiddle.net/y7zb5h12/

![image](https://user-images.githubusercontent.com/3311321/29630781-2dfeb81c-87f2-11e7-8b87-f8f50b4e5078.png)

## What is the expected behavior?

When I specify the boundaries of the Reference Area as the full domain/range of the graph, I expect that entire area to be covered.

**Comment by messerc** [comment]
I'm still unclear on what your issue is - everything seems to be working as intended within the fiddle. You're defining `x1, x2, y1, y2` explicitly within the `<ReferenceArea />` component and it's correct.

**Comment by aarohmankad** [comment]
I wanted the spaces that aren't covered to be covered. Currently expanding any of  `x1, x2, y1, y2` makes the reference area disappear

**Comment by remojansen** [comment]
@aarohmankad I'm not sure but maybe this is what you are looking for https://github.com/recharts/recharts/pull/931 ?

**Comment by faeron** [comment]
I think I have the same issue as @aarohmankad had, so I. In my case, I want the reference area to represent a threshold range, to see if the data exceeds it at some point.

The reference area is only drawn if both y-values are in range of the y-Axis domain.
Now I would expect, that even if I set the y2 value outside of that domain, that the reference area will adapt and still render, but with the upper/lower y-value set to the min/max values of the y-Axis domain.

Here a sample I borrowed and updated from first post:
https://codesandbox.io/s/m72oxy7oqy

#931 is part of the solution, because now I can omit x values, as it should span the full x range.

If that is the desired behavior for ReferenceArea, I think the fix would be to check in https://github.com/recharts/recharts/blob/master/src/cartesian/ReferenceArea.js#L69-L91 first if the values are in their respective axis domain, before scaling them.
