### ISSUE TITLE
Create other mouse events on brush

### ISSUE THREAD

**Issue by magdalko** [recharts/recharts#859]
Hi,

How to access for example onMouseUp event in Brush? There is only available "onChange" but I really need onMouseUp. I tried different approaches but was not successful. Any ideas? :)

**Comment by xile611** [comment]
Sorry for not handling your issue in time, please try the latest version. If the problem persists, please submit the issue according to the issue specification.

**Comment by sharabiania** [comment]
This is still not implemented eh?

I've tried: `<Brush onMouseUp={handler} />` but nothing happens.

Also we need `onDragEnd` for brush.

**Comment by bsplosion** [comment]
Ran into this today as well.  Since the event emitted has no details besides brushed indices, there's no way to tell the handler's state which makes it very difficult to trigger events accurately for users.  I'm debouncing for 750ms and resetting after any further emits of `onChange` but unfortunately some users are pausing their drags for long enough to have the event fire anyway.  

`onMouseUp`, or particularly `onDragEnd` would be much more appropriate than `onChange` for most uses of an emitted brush event.

**Comment by ckifer** [comment]
released in 2.9
