### ISSUE TITLE
Time axis not working

### ISSUE THREAD

**Issue by tobia** [recharts/recharts#876]
## Do you want to request a feature or report a bug?

This is either a bug or a missing piece of documentation.

See also https://github.com/recharts/recharts/issues/274#issuecomment-274824705

## What is the current behavior?

I cannot figure out how to make `scale="time"` work at all.

## Steps to reproduce

Here: http://jsfiddle.net/euks6bth/

I would like to activate `scale="time"` on that chart. I have tried several XAxis specifications, including the following:

	<XAxis dataKey="week"/>
	<XAxis dataKey="date"/>
	<XAxis dataKey="week" scale="time"/>
	<XAxis dataKey="date" scale="time"/>
	<XAxis dataKey="week" scale="time" type="number"/>
	<XAxis dataKey="date" scale="time" type="number"/>
	...

In the dataset `week` is a string in the format `YYYY-MM-DD` (with weekly resolution) while `date` is a Date object parsed from that string.

## Expected behavior

One of those combinations should activate the D3 timeScale, which would compute ticks at suitable intervals (probably 1 per year, judging by the available space.)

Instead `<XAxis dataKey="week"/>` creates a generic category axis (as it should), `<XAxis dataKey="date"/>` has too many ticks and no labels, and all the others fail to display anything.

## Versions, browser, OS

I have only tested the latest 1.0.0-alpha.4 with Chromium 60 on Linux

**Comment by Hyllesen** [comment]
I'm struggling with this as well. Did you find a solution?

**Comment by jakubjanczyk** [comment]
This might not exactly solve the issue, but there is a workaround that works for me. However, it requires changing format of your data.

This one would work:
`<XAxis dataKey="date" scale="time" type="number"/>`
if `date` has number instead of Data, so in this case it would be number of milliseconds of given date. And then you would need to format it properly with `tickFormatter`.

Full example:
`<XAxis dataKey='time' tickFormatter={tickFormatter} type='number' scale='time' domain={['dataMin', 'dataMax']} ... />
` 

`domain` was also necessary for me, so only those values I provided are displayed on chart.

And here is my `tickFormatter` function:

`const tickFormatter = (tick) => moment(tick).format('HH:mm')`
