### ISSUE TITLE
Examples are not working on the website http://recharts.org/#/en-US/examples/

### ISSUE THREAD

**Issue by KalpanaPagariya** [recharts/recharts#918]
## Do you want to request a feature or report a bug?
Bug
## What is the current behavior?
Examples are not working http://recharts.org/#/en-US/examples/SimpleAreaChart

**Comment by atorov** [comment]
The error message in the browser console is:
Failed to load resource: the server responded with a status of 404 ()
https://npmcdn.com/react-dom@16.0.0/dist/react-dom.min.js

**Comment by ahmadsholehin** [comment]
Examples are fetching react@16.0.0 and react-dom@16.0.0, which just got released. How can this be fixed?

**Comment by davidfufu** [comment]
Experiencing same issue. I've ran the demo script for the git repo, but it doesn't have everything.

**Comment by ThePianoDentist** [comment]
it's effort.

but I was able to view the examples by 

- clicking the Js-fiddle link.
- click external resources
- delete the react-with-addons and react-dom links
- replace them (with the add button) with https://npmcdn.com/react@^15/dist/react-with-addons.min.js
and https://npmcdn.com/react-dom@^15/dist/react-dom.min.js
- move them both up the order to just below browser.js (addons above dom)

if desperately need to see examples now

**Comment by gaearon** [comment]
Sorry about this. React 16 changed the URLs. So it would be reasonable to pin examples to a specific version (in this case, 15) rather than use the implicit `latest` version.

Even if we provided fallbacks for old style URLs, the “React with addons” build doesn’t exist anymore. So it would have to be fixed anyway.

The new URLs are:

http://npmcdn.com/react@16/umd/react.development.js
http://npmcdn.com/react-dom@16/umd/react-dom.development.js

**Comment by xile611** [comment]
The examples have been updated.

**Comment by gaearon** [comment]
Thanks!
