### ISSUE TITLE
Use of peerDependencies or dependencies?

### ISSUE THREAD

**Issue by dmr** [recharts/recharts#919]
In our project we use "d3-scale" 1.0.6.
If recharts would define d3-scale >= 1.0.4 as a peerDependency then we would not need to include both bundles into our build.

We have the same problem/topic with prop-types, core-js and lodash.

What do you think, are you interested in a pull request to change these dependencies to peerDependencies?

**Comment by RickWong** [comment]
Terrible that recharts includes both `lodash` and `lodash-es` in dependencies. That needlessly increases the bundle size.

**Comment by RickWong** [comment]
I could be mistaken. This is my `yarn.lock` file:

```

recharts@1.1.0:
  version "1.1.0"
  resolved "https://registry.yarnpkg.com/recharts/-/recharts-1.1.0.tgz#2ceea5f7438ba32eff54126b1136d5295f1dfbf8"
  dependencies:
    classnames "2.2.5"
    core-js "2.5.1"
    d3-interpolate "^1.1.5"
    d3-scale "1.0.6"
    d3-shape "1.2.0"
    lodash "~4.17.4"
    lodash-es "~4.17.4"
    prop-types "^15.6.0"
    react-resize-detector "1.1.0"
    react-smooth "1.0.0"
    recharts-scale "0.3.2"
    reduce-css-calc "1.3.0"
```

**Comment by TrySound** [comment]
@RickWong `yarn.lock` is not responsible to what is bundled. How look your `recharts` imports?

**Comment by RickWong** [comment]
I suspect `react-smooth` to be the culprit, it requires `lodash`, while the `recharts` selects `lodash-es`.

**Comment by msholty-fd** [comment]
This type of thing seems like a no-brainer, and a very simple PR to open. I intend to open a PR to update this later today.

If you go into your node_modules in a project that has recharts, and delete the lodash folder in `recharts/node_modules`, and also add `lodash` to `peerDependencies` rather than `dependencies`, it removes lodash from `recharts` part of the bundle and makes it use the installed lodash instead.

Side-by-side comparison:
With lodash listed in `dependencies`:
![screen shot 2019-02-11 at 10 32 01 am](https://user-images.githubusercontent.com/13840573/52573532-5dbf6e00-2de8-11e9-9ca7-d79473c17857.png)

With lodash listed in `peerDependencies` and not shipped in the `recharts` dep:
![screen shot 2019-02-11 at 10 32 12 am](https://user-images.githubusercontent.com/13840573/52573534-5f893180-2de8-11e9-9c73-1608ce293b74.png)

**Comment by damianobarbati** [comment]
@TrySound referring to:
> lodash is used only with commonjs entry point (main field in package.json)
> lodash-es is used only with esm entry point (module field in package.json)

This means that importing "recharts" with webpack always results in "lodash" instead of "lodash-es", right?

I also see the following when `yarn why lodash`:
   - Hoisted from "recharts#react-smooth#lodash"

I'm trying to dedupe the `lodash` / `lodash-es`.
I'm afraid that using `recharts` implies importing `lodash` thus I should stop using `lodash-es` in my `recharts` projects and switch to `lodash` to not have both libs: correct?

**Comment by damianobarbati** [comment]
@RickWong did you figure this out? Is lodash because of react-smooth required by recharts?

**Comment by RickWong** [comment]
@damianobarbati No solution. Using `lodash`.
