### ISSUE TITLE
RadialBar props not working

### ISSUE THREAD

**Issue by juliussohn** [recharts/recharts#955]
Changing most of the RadialBar props has no effect, including: minAngle, maxAngle, startAngle, endAngle, clockWise.

I tested it in the  [example in JSFiddle](http://jsfiddle.net/4qo7ba5L/?utm_source=website&utm_medium=embed&utm_campaign=4qo7ba5L)

**Comment by tongyy** [comment]
It appears that it removed the related props at this [diff ](https://github.com/recharts/recharts/commit/8dfd83dc5e2f6e32958cec16f3009ddc14600cc0#diff-232275603e425a80513a3b40847f82b8)

**Comment by thomax** [comment]
Nice to know it's not my fault that I can't get RadialBar to behave :)

**Comment by thomax** [comment]
I use `PieChart` as a temporary workaround.

**Comment by xile611** [comment]
Because only one group of bar is supported in Recharts 0.x. We want to support multi groups of bar in 1.0+ just like <BarChart />, so we move the props `startAngle`, `endAngle` to RadialBarChart.

![image](https://user-images.githubusercontent.com/6111424/32935928-306bc4e2-cbad-11e7-9310-a00313d35bd3.png)

And If you have specified the props `starAngle`, `endAngle`, `clockWise` is no longer needed, so this two props are removed.

The props `minAngle` and `maxAngle` are used to specify  the domain of `PolarAngleAxis`, so they are removed too. Try to set the `domain` of `PolarAngleAxis` after I resolve some bug.

**Comment by xile611** [comment]
Try to set the range of `PolarAngleAxis` in recharts 1.0.0-beta.3
