### ISSUE TITLE
Add itemSorter to Legend

### ISSUE THREAD

**Issue by mzr-certi** [recharts/recharts#975]
## Do you want to request a feature or report a bug?
Feature

## What is the current behavior?
Items in Legend are not sortable

## What is the expected behavior?
Legend exposes a `itemSorter` prop that allows the user to sort the legend items, same way its done with Tooltip in #151.

**Comment by tomas-lejdung** [comment]
This issue is quite old, but I hope that I can help someone from wasting their time like I did by having to read the source code to hunt down the problem.

It appears that the sorting method has been changed from the standard Array.prototype.sort to [lodash.sortBy](https://lodash.com/docs/4.17.15#sortBy) that works differently. It either accepts an array of strings which represents the keys in the object, or a function that takes ONE argument (the item) and returns the value of which it should be sorted by. 
From the Lodash docs
> Creates an array of elements, sorted in ascending order by the results of running each element in a collection thru each iteratee. This method performs a stable sort, that is, it preserves the original sort order of equal elements. The iteratees are invoked with one argument: (value).

The itemSorter has to be a function due to the restrictions set in the Tooltip component. 
If we want to sort by value in descending order:
```
<Tooltip itemSorter={(item) => (-item.value)} />
```
And if you want to see all keys provided by _item_ object, simply log the item to the console
```
<Tooltip itemSorter={(item) => {console.log(item); return -item.value;}} />
```

I do not agree with the change from Array.prototype.sort the _.sortBy as it will always sort in ASC order, and because the sorted array is not exposed there is no trivial way to reverse it. The value can be sorted in DESC order by negating the value, but it will not be that easy with a string (for example if you want to sort by item.name).

**Comment by BugsBunny338** [comment]
Followup to @xile611 :

I needed to sort by item.name, so my workaround was to name the dataKeys as '1', '2', '3' etc. and then I did <Tooltip itemSorter={(item) => -parseInt(item.name)} />. I then used <Tooltip formatter={(value, name, props) => myMapping[name] /> to get nice names.

**Comment by istanfield09** [comment]
Is the Legend component sortable? I'm a bit confused why this issue was closed. It looks like Tooltip is sortable but Legend is not.

**Comment by agzam** [comment]
Nudging on this. Can someone suggest the best way of sorting the legend data? Why was this issue closed? Legend doesn't appear to have `itemSorter`.
