### ISSUE TITLE
[feature]: Manual redraw/refresh graph possibility

### ISSUE THREAD

**Issue by daphnesmit** [recharts/recharts#992]
I can't get my pieChart to redraw when moving to another page and coming back.
At this point you can't redraw the graph when the data doesn't change. So when you come back from another page, the chart doesn't redraw/animate and so my custom labels (called at animationEnd) are not rendered anymore.

**Comment by xile611** [comment]
@daphnesmit When you move to another page, how about the first page? Was the first page been removed or just been hidden?  If you just hide the first page, PieChart can't check the update. It's right for PieChart don't update when nothing has changed.

**Comment by jamesjryan** [comment]
+1 for this. I'm dynamically changing a second chart axis - recharts doesn't seem to be aware of this and isn't redrawing.

If the data changes - it rerenders just fine. Would be great if you could expose the internal handler so we could fire it manually.

**Comment by daveabes** [comment]
Still having this issue.

Dynamic chart properties does not cause chart content to redraw.

But tooltip and axis data is redrawn as we are using manual components....

Is resolve your side yet????

**Comment by dkloke** [comment]
One external way to do this is to change the `key` property of the chart component to make React re-render it. Unfortunately this also affects React's/browser's current focus and can set off other re-renders if one isn't careful.

Here I'm using a useState hook containing an integer in the parent component and passing it through props  to modify the chart's key, this redraws the whole chart including axes:
```
    <ComposedChart
      key={"kickMe"+chartKicker}
      ....
```
Then in the parent:
```
    const kickTheChart = ()=>setChartKicker(chartKicker+1);
```
Since this is a one-way operation, it can be put inside of a setTimeout or async/Promise to make sure it fires late. Awful, I know.

**Comment by xile611** [comment]
Change the key of Chart is workaround.
Keep Tooltip visible is about [another issue](https://github.com/recharts/recharts/issues/855)
